### PR TITLE
fix: Nature Power displays as Normal with Aerilate

### LINKED ISSUE #5976: [Bug] Nature Power displays as Flying with Aerilate
### Describe the bug

Nature Power displays as Flying Type in the Move Menu when a Pokemon has an -ate Ability.

Metronome and Mimic also have this issue

'OverrideMoveEffectAttr' seems to be the common attr

### Reproduction

```
	MOVESET_OVERRIDE: [MoveId.NATURE_POWER, MoveId.WEATHER_BALL, MoveId.METRONOME, MoveId.TERRAIN_PULSE],
	ABILITY_OVERRIDE: AbilityId.AERILATE,
```

### Expected behavior

Certain moves should consistently display as Normal Type

https://github.com/user-attachments/assets/ed36201b-20f7-4b85-ba26-2268fd29ca6b

Image

### Screenshots / Videos

https://github.com/user-attachments/assets/cbf2a9fd-cd84-4560-a91b-e1e3209ee138

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by malex-bear**
## What are the changes the user will see?

When a species has type changing abilities such as Aerilate, Pixilate, Refrigerate or Galvanize, moves that call other moves (Nature Power, Metronome, Mimic, ...) will now be displayed with their original type in the moves menu, even if their type would be changed by the ability during battle.

## Why am I making these changes?

As reported in #5976, these moves were being displayed with their ability-modified type in the moves menu.

This change makes the move display consistent with expected behavior and avoids showing misleading information to the player.
Fixes #5976.

## What are the changes from a developer perspective?

Moves affected by this issue appear to share the 'OverrideMoveEffectAttr' attribute.

The getMoveType method in `src/fields/pokemon.ts` is used in `src/ui/handlers/fight-ui-handlers.ts` to determine a move's displayed type. However, it did not account for whether a move has this attribute. 

Updated that logic by adding a conditional statement in getMoveType, so that moves affected are not shown with a modified type in the moves menu.

## Screenshots/Videos

<details><summary>Before</summary>

Screenshot from 2026-03-24 17-04-08

</details>
<details><summary>After</summary>

Screenshot from 2026-03-24 17-03-25

</details>

## How to test the changes?

All unit tests passed. 

To test the changes, I used the src/overrides.ts file by changing: 
```ts
const overrides = { MOVESET_OVERRIDE: [MoveId.NATURE_POWER, MoveId.METRONOME, MoveId.WEATHER_BALL, MoveId.MIMIC],
  ABILITY_OVERRIDE: AbilityId.AERILATE,
  STARTING_BIOME_OVERRIDE: BiomeId.TOWN,
} satisfies Partial<InstanceType<OverridesType>>;
```

It is possible to change the MOVESET_OVERRIDE to test other moves that are affected by the same ability (for ex: ASSIST, SLEEP_TALK). Additionally, other type-changing abilities were tested like Pixilate, Refrigerate and Galvanize. As a control, I also tested with a non-type changing ability such as Levitate.

## Checklist

- The PR content is correctly formatted:
  - [x] **I'm using `beta` as my base branch**
  - [x] **The current branch is not named `beta`, `main` or the name of another long-lived feature branch**
  - [x] I have provided a clear explanation of the changes within the PR description
  - [x] The PR title matches the Conventional Commits format (as described in [CONTRIBUTING.md](https://github.com/pagefaultgames/pokerogue/blob/beta/CONTRIBUTING.md#pr-title-format))
- [x] The PR is self-contained and cannot be split into smaller PRs
- The PR has been confirmed to work correctly:
  - [x] I have tested the changes manually
  - [x] The full automated test suite still passes (use `pnpm test:silent` to test locally)
  - [~] I have created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes if necessary
- [x] I have provided screenshots/videos of the changes (if applicable)
  - [~] I have made sure that any UI changes work for both the default and legacy UI themes (if applicable)

Are there any localization additions or changes? If so:
- [~] I have created an associated PR on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repository
  - If so, include a link to the PR here: _____
- [~] I have contacted the Translation Team on Discord for proofreading/translation

Does this require any additions or changes to in-game assets? If so:
- [~] I have created an associated PR on the [assets](https://github.com/pagefaultgames/pokerogue-assets) repository
  - If so, include a link to the PR here: _____

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -2435,7 +2435,17 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
 
     applyMoveAttrs("VariableMoveTypeAttr", this, null, move, moveTypeHolder);
 
-    applyAbAttrs("MoveTypeChangeAbAttr", { pokemon: this, move, simulated, moveType: moveTypeHolder, opponent: this });
+    // Moves that are overridden by an ability (ex.Aerilate) should not have their type
+    // changed by MoveTypeChangeAbAttr
+    if (move.getAttrs("OverrideMoveEffectAttr").length === 0) {
```
Comment (DayKev) [inline src/field/pokemon.ts]:
```suggestion
    if (!move.hasAttr("OverrideMoveEffectAttr")) {
```

**Review by DayKev — DISMISSED** [review]
Seems good, would prefer `!move.hasAttr(...)` over `move.getAttrs(...).length === 0` though.

**Review by DayKev — DISMISSED** [review]

File: src/field/pokemon.ts [hunk 2]
```diff
@@ -2443,7 +2435,17 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
 
     applyMoveAttrs("VariableMoveTypeAttr", this, null, move, moveTypeHolder);
 
-    applyAbAttrs("MoveTypeChangeAbAttr", { pokemon: this, move, simulated, moveType: moveTypeHolder, opponent: this });
+    // Moves that are overridden by an ability (ex.Aerilate) should not have their type
```
Comment (Bertie690) [inline src/field/pokemon.ts]:
```suggestion
    // Moves that are overridden by an ability (e.g. Aerilate) should not have their type
```

**Review by Bertie690 — CHANGES_REQUESTED** [review]
@malex-bear 
Currently, the check for `OverrideMoveEffectAttr` means Future Sight will still display as Psychic Type when used by a Normalize Pokemon.

From what I can tell, the attribute that should be checked is instead the one for move-calling moves (which does not currently include Nature Power, but will after #6858 is merged).

I'm not sure whether we want to block this PR until mine is merged or merge yours first and add the fix in mine, but it otherwise looks good.

**Review by damocleas — DISMISSED** [review]
Why would we want normal moves to display as a normal type move if an ability changes it? Champions footage has even shown that it changes visibly there, and to me and many others it is much better than way.

Moves that would be unaffected like Metronome and Mimic I can see though, as long as they do not contribute to type boosting items, as type changing items base off of the changed type.

Weather ball also should be affected though, even if it calls another move- ideally changing with the active weather.

**Comment by malex-bear** [comment]
Just updated the description to clarify this applies to moves that call other moves.

**Review by DayKev — APPROVED** [review]

**Comment by DayKev** [comment]
> Currently, the check for `OverrideMoveEffectAttr` means Future Sight will still display as Psychic Type when used by a Normalize Pokemon.
> 
> From what I can tell, the attribute that should be checked is instead the one for move-calling moves (which does not currently include Nature Power, but will after #6858 is merged).
> 
> I'm not sure whether we want to block this PR until mine is merged or merge yours first and add the fix in mine, but it otherwise looks good.

@Bertie690
I think it'll be better to change it in your PR.
