### PR TITLE
fix(ability): Costar now copies allied crit stages

### LINKED ISSUE #6988: [Bug] Costar doesn't copy critical hit stages
> When a Pokémon with Costar enters the battle, it copies an ally's stat stages for itself. This includes the ally's [critical-hit](https://bulbapedia.bulbagarden.net/wiki/Critical_hit) ratio.
- https://bulbapedia.bulbagarden.net/wiki/Costar_(Ability)

```ts
/** Attempt to copy the stat changes on an ally pokemon */
export class PostSummonCopyAllyStatsAbAttr extends PostSummonAbAttr {
  override canApply({ pokemon }: AbAttrBaseParams): boolean {
    if (!globalScene.currentBattle.double) {
      return false;
    }

    const ally = pokemon.getAlly();
    return !(ally == null || ally.getStatStages().every(s => s === 0));
  }

  override apply({ pokemon, simulated }: AbAttrBaseParams): void {
    if (simulated) {
      return;
    }
    const ally = pokemon.getAlly();
    if (ally != null) {
      for (const s of BATTLE_STATS) {
        pokemon.setStatStage(s, ally.getStatStage(s));
      }
      pokemon.updateInfo();
    }
  }
  // ...
}
```

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
Costar will now copy the crit stages of the user's ally.

## Why am I making these changes?
- Fixes #6988 

## What are the changes from a developer perspective?
`PostSummonCopyAllyStatsAbAttr` now copies the `BattlerTag`s used to implement crit stages.

## How to test the changes?
`pnpm test:silent costar`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR
- [x] The PR is self-contained and cannot be split into smaller PRs
- [x] I have provided a clear explanation of the changes
- [x] The PR title matches the format described in [CONTRIBUTING.md](https://github.com/pagefaultgames/pokerogue/blob/beta/CONTRIBUTING.md#-submitting-a-pull-request)
- [x] The full test suite still passes (`pnpm test:silent`)
  - [x] I have created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes

### CODE REVIEW

**Review by Bertie690 — APPROVED** [review]

File: test/test-utils/helpers/classic-mode-helper.ts [hunk 1]
```diff
@@ -63,6 +63,7 @@ export class ClassicModeHelper extends GameManagerHelper {
     }
   }
 
+  // TODO: change to `startBattle(...species: NonEmptyTuple<SpeciesId>)`
```
Comment (Bertie690) [inline test/test-utils/helpers/classic-mode-helper.ts]: Actually this should be capped at 6 length - the maximum valid party size is 6 members.

Comment (DayKev) [reply test/test-utils/helpers/classic-mode-helper.ts]: ~Wdym? A party can have 6 pokemon.~
Oh I misunderstood.
