### PR TITLE
[Refactor/Bug/Ability] Reworked BattleData, fixed Rage Fist, Harvest, Belch + Implemented Cud Chew

### LINKED ISSUE #4658: [Bug] On Reload; First-turn Moves and Gigaton can be used Successively, Torment Loses Last-used Move, Truant does not Force Skip Turns,
### Describe the bug

Moves and Abilities that rely on moveHistory and turnCount do not load properly after refreshing or saving and quitting.

- This affects Moves and Abilities that rely on getLastXMoves to determine whether a move should succeed or fail when used.
Includes Torment, Gigaton Hammer/Blood Moon
-Moves that rely on Move History such as Torment do not keep track of the move used in the previous wave, allowing any move to be selected on reload.
-Includes Encore and Disable
-Battler Tags are still saved on reload, so under Torment inflicted the previous wave, using a move will not let you use it again the next turn.

- Moves that rely on TurnCount such as First Impression, Fake Out, and Mat Block are immediately able to be used again on a new wave after reloading

### Reproduction

Use any of the above moves, observe that you can use the moves again when the move would normally not succeed.

If Encore, notice that the enemy's move fails rather than Encores your last-used move.

### Expected behavior

These moves and abilities should not forget that they were used the wave before when you reload or refresh

### Screenshots / Videos

First Impression on Reload

https://github.com/user-attachments/assets/aa03f96b-7ff7-41f4-83d4-21e00fb2059d

**Normal First Impression**

https://github.com/user-attachments/assets/f4cd4bd5-ab2b-44e3-9e54-4716a80b17fe

Gigaton Hammer on Reload

https://github.com/user-attachments/assets/ced43951-25eb-4061-9edd-56f05a5dec1d

Gigaton Hammer on Refresh

https://github.com/user-attachments/assets/529251c6-6ba9-460b-80ab-f46f8bbb3f45

Disable failing after reloading

https://github.com/user-attachments/assets/2ebe42ad-318d-408e-884e-f851723dc4ae

Torment on Beta, the last move can be selected

https://github.com/user-attachments/assets/803160d2-2b5d-4a80-8a0d-97eb38f2d29f

Truant

https://github.com/user-attachments/assets/1877c6ce-f2b0-4957-af55-e2a912c132f9

https://github.com/user-attachments/assets/fc1686cd-93a1-40d0-bb98-48158724aa1e

### Session export file

Tormented Pokemon Session Data, taken from BETA, post-fix

[TormentRELOAD.txt](https://github.com/user-attachments/files/17358857/TormentRELOAD.txt)

### Additional context

https://github.com/pagefaultgames/pokerogue/blob/0a4c12387b5992e1f14f53a0f8e6b493a0390ad0/src/field/pokemon.ts#L4995
```
export class PokemonBattleSummonData {
  /** The number of turns the pokemon has passed since entering the battle */
  public turnCount: number = 1;
  /** The list of moves the pokemon has used since entering the battle */
  public moveHistory: TurnMove[] = [];
}
```
Might be relevant as those seem to be the BattlerTags affected

FirstMoveCondition Moves were changed recently to not be able to be used by a pokemon if it stayed in between waves.
 https://github.com/pagefaultgames/pokerogue/pull/4168
 -Balance might be reverting this due to player feedback, which would make FirstMoveCondition Moves appear to function correctly

Does not affect Gorilla Tactics post-([Bug] Move Restriction Battler Tag bugs)
https://github.com/pagefaultgames/pokerogue/pull/4536

Encore and Disable have a Bug with their Move Histories
https://discord.com/channels/1125469663833370665/1289982467838836756

Moves that use copymoveattr are unaffected as they don't seem to target the last move used from a previous wave. (Copycat, Mimic, Mirror Move)

### LINKED ISSUE #5073: [Bug] Using Covet or Thief on a Harvested Berry Crashes the game
### Describe the bug

Using Covet or Thief on a Harvested Berry Crashes the Game

-Pluck, Bug Bite, and Magician do not crash the game.
-The game does not crash if the Berry chosen had not been harvested.
-If Thief/Covet do not choose a Berry that has been harvested when a Pokemon is holding multiple items, the game does not crash.
-If Thief/Covet would target a Berry of the same Type, that existed after the first one was consumed and pushed to memory, the game does not crash. The game crashes if Thief/Covet is used again after the harvested berry is created.

Link to Discord's Bug Report (Calyrex crash when using Covet on harvested berry)
https://discord.com/channels/1125469663833370665/1305262017925353472

### Reproduction

Use Covet or Thief and steal an item against a Pokemon that has created a consumed Berry through Harvest.

Start run with any Pokémon, Slugma/Desolate Land, Fennekin/Magician, Run from the first wave to set up Perma-Desolate Land on the second wave
```
BATTLE_TYPE_OVERRIDE: "odd-doubles",
STARTING_MOVESET_OVERRIDE: [Moves.THIEF, Moves.PLUCK, Moves.TACKLE, Moves.METAL_CLAW],

OPP_LEVEL_OVERRIDE: 20,
OPP_ABILITY_OVERRIDE: Abilities.HARVEST,
OPP_MOVESET_OVERRIDE: [Moves.SPLASH],
OPP_HELD_ITEM_OVERRIDE: [name: "BERRY", type: BerryType.ENIGMA, count: 1],
```

### Expected behavior

Game should not crash, Thief/Covet User should gain the Berry.

### Screenshots / Videos

HarvestCovetConsole

Crashes if the Berry was Harvested

https://github.com/user-attachments/assets/58461a42-8eb4-4efc-a3e3-bd3064c8ced3

No Crash if the berry was not Harvested

https://github.com/user-attachments/assets/067df436-e7b1-441f-8e2a-a2cfd9179279

Magician Stealing a Harvested Berry does not Crash

https://github.com/user-attachments/assets/1fce15d5-b1fb-4602-93b0-dcb32d6ce170

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### LINKED ISSUE #5092: [Bug] Harvest Berries can Stack same-type Berries with Pokemon in the Party
### Describe the bug

When a Pokemon's Harvest ability is activated, Berries search for an available stack, by Berry type.
-If the closest stack from the first to last Pokemon is the Harvest User, then the Berry will go to the User. (user would have multiple berries of that type)
-Berry stacks being full is irrelevant, and the Berry will still go to that Pokemon.
-In Doubles, if another Berry is Harvested before the next Slot's when neither would have a Berry after that turn, usually due to having greater Speed, the second Berry will go to the Pokemon who harvested their Berry first.

Link to Discord's Bug Report (Harvest just doesn't)
https://discord.com/channels/1125469663833370665/1260009161744449586

### Reproduction

Activate Harvest while you have 1 of a type of Berry, and a Pokémon in your Party has a Berry of that type.

Restart runs until you get Sunny Weather.
1. Catch the first Magikarp, do not get Thunder Waved.
2. In the Rewards Screen, give the Rewarded Lum Berry to the caught Magikarp.
3.  In the next Battle, use Splash
4. The berry has magically teleported to the Magikarp in your Party, and it now has 2 Lum Berries.
```

	STARTING_BIOME_OVERRIDE: Biome.VOLCANO,

	STARTING_LEVEL_OVERRIDE: 40,
	MOVESET_OVERRIDE: [Moves.SPLASH],
	ABILITY_OVERRIDE: Abilities.HARVEST,

	OPP_SPECIES_OVERRIDE: Species.MAGIKARP,
	OPP_MOVESET_OVERRIDE: [Moves.THUNDER_WAVE],

	ITEM_REWARD_OVERRIDE: [{name: "BERRY", type: BerryType.LUM}],
	STARTING_HELD_ITEMS_OVERRIDE: [{name: "BERRY", type: BerryType.LUM, count: 1}],

```

### Expected behavior

Harvested Berries should only go to the Harvest User.

### Screenshots / Videos

Harvested Berries can go to the Party's Berry Stacks

https://github.com/user-attachments/assets/2827daf4-c4f7-49da-950e-0612fae72ced

Only Occurs if the other Pokemon has the correct type of Berry

https://github.com/user-attachments/assets/8702340f-32e0-48d5-b221-7006692878dc

Harvested berries stay on the user if they have a Berry stack of that type

https://github.com/user-attachments/assets/a2814f2d-d3c7-4d44-85b9-d60aa60ef8dd

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### LINKED ISSUE #5093: [Bug] Harvested Berries Disappear After Reloading a Run
### Describe the bug

After a Berry is harvested by Harvest and the run is exited and reloaded, Harvested berries are lost.
-If the Berry was moved to, or was Harvested onto a Party member, the Berry is not lost.

Link to Discord's Bug Report (Multiple berry bugs seemingly caused by harvest)
https://discord.com/channels/1125469663833370665/1293365514567155722

### Reproduction

Harvest a Berry with Harvest. Progress the wave, then reload the run.

```
	MOVESET_OVERRIDE: [Moves.SPLASH],
	ABILITY_OVERRIDE: Abilities.HARVEST,

	OPP_MOVESET_OVERRIDE: [Moves.THUNDER_WAVE],

	STARTING_HELD_ITEMS_OVERRIDE: [{name: "BERRY", type: BerryType.LUM, count: 1}, {name: "BERRY", type: BerryType.PETAYA, count: 1}],
```

### Expected behavior

Harvested Berries should not be lost on reload.

### Screenshots / Videos

1 Lum

https://github.com/user-attachments/assets/e8391958-a664-43fa-92bf-cdd721e1595a

2 Enigma

https://github.com/user-attachments/assets/56c997f3-1056-4846-94eb-21bab46222a6

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### LINKED ISSUE #5100: [Bug] Harvest Deletes Every Berry Consumed in Memory after That Berry is Harvested
### Describe the bug

If Harvest would produce a Berry Harvested in a Battle where multiple Berries were Harvested, any Berry that was consumed after it and was moved to the User's Berry memory is lost.
-Berries do not need to all be consumed in the same turn.

Example: (From order of Liechi, Ganlon, Petaya, Apicot, Salac)
(After triggering all of them at once)
- Apicot is Harvested, so as Salac was consumed later, it is cleared from memory
- Ganlon is Harvested, so as Petaya, Apicot, and Salac were consumed later, they are cleared from memory
- Liechi is Harvested, so as Ganlon, Petaya, Apicot, and Salac were consumed later, they are cleared from memory.

Link to Discord's Bug Report (Harvest Doesn't Return Berries?)
https://discord.com/channels/1125469663833370665/1295252012690051105

### Reproduction

Use Harvest after consuming multiple Berries in one turn, such as by being knocked to low health, or by Nuzzle with Enigma and Lum Berries. Notice that if the first Berry that was consumed was harvested, new berries are no longer harvested.

```
	STARTING_WAVE_OVERRIDE: 11,
	STARTING_BIOME_OVERRIDE: Biome.PLAINS,

	MOVESET_OVERRIDE: [Moves.SPLASH, Moves.DISABLE, Moves.RECOVER],
	ABILITY_OVERRIDE: Abilities.HARVEST,

	OPP_LEVEL_OVERRIDE: 40,

	OPP_MOVESET_OVERRIDE: [Moves.SUNNY_DAY, Moves.FALSE_SWIPE],

	STARTING_HELD_ITEMS_OVERRIDE: [
	{name: "BERRY", type: BerryType.LIECHI, count: 1},
	{name: "BERRY", type: BerryType.GANLON, count: 1},
	{name: "BERRY", type: BerryType.PETAYA, count: 1},
	{name: "BERRY", type: BerryType.APICOT, count: 1},
	{name: "BERRY", type: BerryType.SALAC, count: 1}
	
	]


```

### Expected behavior

Harvest should not clear the User's Berry consumption memory when the first Berry is harvested.

### Screenshots / Videos

https://github.com/user-attachments/assets/bbea35d4-d407-4d3f-9178-e47be2285211

Berry Memory is kept when the first berry is not harvested before the second

https://github.com/user-attachments/assets/af400cc9-cae1-4331-a71e-943cff4be54b

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### LINKED ISSUE #5667: [Bug] Belch resets on new wave, ignores Harvested berries for condition
### Describe the bug

Belch currently checks based off of Harvest's `berriesEaten` array for its `moveConditionFunc`, meaning it won't work if Harvest successfully recovers all berries eaten this battle. (Harvest removes stuff from the array on recovery)
Also it doesn't save per battle due to the underlying issue with harvest...

### Reproduction

1. Get belch + harvest
2. get berry
3. eat berry and roll harvest proc (or go in sunlight)
4. click belch

### Expected behavior

Belch should have a separate tracker from harvest for this exact reason.

### Screenshots / Videos

_No response_

### Session export file

_No response_

### User data export file

_No response_

### Additional context

I have not verified this myself but am 100% sure this is an issue
Someone doing manual verification would be nice

### PR DESCRIPTION
**Pull request by Bertie690**
## What are the changes the user will see?
1. Cud chew now tracks and spits up berries eaten. 
2. Harvest works and tracks berries munched between waves.
3. Belch works with Harvest.
4. Rage Fist still works even on existing saves.
5. All moves relying on battleSummonData work correctly on reload.

## Why am I making these changes?
GIRAFFE GO BRRRRR
Fixes #5093 
Fixes #5092 
Fixes #5100 
Fixes #5667
Fixes #5073 
Fixes #4658 

### MAJOR CHANGES:
1. `PokemonBattleData` has had several properties split off into a new class called `PokemonWaveData`. The former now solely contains variables intended to be preserved between battles, while the latter holds all the _old_ trackers that were reset each wave.
    - Since literally everything that used to be in `BattleData` was being reset per-wave (erroneously or not), this has no impact on old saves.
    - `BattleData` is now included inside `PokemonData` to be saved and preserved between waves.
2. All 4 `PokemonXXXData` classes have been made guaranteed not to be nullish and have thus had _most_ existing optional chains and similar checks removed. (If any remain, please let me know as random useless checks = bad)
    - This (alongside the prior renaming) accounts for the bulk of the changed files.
3. All instances where berries are eaten now update a pokemon's `BattleData` through a method on `Pokemon` (`recordEatenBerry`)

### Minor Changes:

4. Harvest now actually has tests, doesn't make berries over cap and doesn't duplicate berries!
5. Rage Fist no longer stores its counter inside `CustomPokemonData` in favor of the new `BattleData` class.
6. Belch has its own `BattleData` boolean tracker rather than being tied to harvest.
7. Cud chew now uses 2 trackers inside `SummonData` and `TurnData` to track berries eaten, with the former shoved into the latter as part of its `postTurnApply()` function.
    - For those wondering, I made it an ability related thing to shut off the tracking via neutralizing gas.
8. Added many more comments to existing functions.
9. Removed `SummonDataPrimer` in favor of just _not_ resetting summonData during summonPhase. It should have never been reset there to begin with so... yeah
10. `PokemonBattleSummonData` has been renamed to `PokemonTempSummonData` to better elucidate its role as a temporary storage entity. `moveHistory` has been moved into `PokemonSummonData` to fix the last resort bug.

## Screenshots/Videos
Covet no crash on harvested berry
https://github.com/user-attachments/assets/897c4e19-d591-4abe-a844-91302dbdaed6

Cud Chew re-eats berries
https://github.com/user-attachments/assets/af4ba023-0690-4402-a9b6-cc3b1442f039

Cud chew preserved between waves
https://github.com/user-attachments/assets/1f40d9ad-1a5f-43db-908d-e8985a5979c3

Cud chew preserved between reloads
https://github.com/user-attachments/assets/d7d5061b-fc84-4e45-b864-583f641a90db

## How to test the changes?
Automated tests mainly; local dev overrides if you really want to I suppose?

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
  - The Harvest fixes relies on the BattleData segregation and such to work, and a lot of it was de-janking related areas.
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
~~  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

### CODE REVIEW

**Comment by Bertie690** [comment]
FWIW, any ideas on which changes might be blowing up the past few test runs would be greatly appreciated.

**Comment by Bertie690** [comment]
Fixes #5093 
Fixes #5092 
Fixes #5100 
Fixes #5667

**Comment by DayKev** [comment]
> Fixes #5093 Fixes #5092 Fixes #5100 Fixes #5667

That should go in the main PR description (under the "why" section) so they are automatically linked to be closed when this PR is merged.

**Comment by Bertie690** [comment]
Requesting update of #3503 for this PR.
Cud chew/rage fist/harvest now fully implemented

File: src/data/pokemon-species.ts [hunk 1]
```diff
@@ -878,6 +879,23 @@ export default class PokemonSpecies extends PokemonSpeciesForm implements Locali
     return this.name;
   }
 
+  /**
+   * Pick and return a random {@linkcode Gender} for a {@linkcode Pokemon}.
+   * @param id The personality value of the pokemon being generated.
+   * @returns THe selected gender for this Pokemon, rolled based on its PID.
```
Comment (DayKev) [inline src/data/pokemon-species.ts:885]: This is based on gens 3-5, not current gens which just use a random number. We should just use normal RNG for this.

File: src/overrides.ts [hunk 2]
```diff
@@ -104,8 +104,16 @@ class DefaultOverrides {
...
+  /**
+   * Set to `true` to force Paralysis and Freeze to always activate,
+   * or `false` to force them to not activate (or clear for freeze).
+   */
   readonly STATUS_ACTIVATION_OVERRIDE: boolean | null = null;
+  /**
+   * Set to `true` to force confusion to always trigger,
+   * or `false` to force it to never trigger.
+   */
+  readonly CONFUSION_ACTIVATION_OVERRIDE: boolean|null = null;
```
Comment (DayKev) [inline src/overrides.ts:116]:
```suggestion
  readonly CONFUSION_ACTIVATION_OVERRIDE: boolean | null = null;
```

File: src/phases/battle-end-phase.ts [hunk 3]
```diff
@@ -58,9 +58,10 @@ export class BattleEndPhase extends BattlePhase {
       globalScene.unshiftPhase(new GameOverPhase(true));
     }
 
+    // reset pokemon wave turn count, apply post battle effects, etc etc.
```
Comment (DayKev) [inline src/phases/battle-end-phase.ts:61]:
```suggestion
```

File: src/phases/battle-end-phase.ts [hunk 4]
```diff
@@ -81,6 +82,7 @@ export class BattleEndPhase extends BattlePhase {
       }
     }
 
+    // lapse all post battle modifiers that should lapse
```
Comment (DayKev) [inline src/phases/battle-end-phase.ts:85]:
```suggestion
```

File: src/phases/berry-phase.ts [hunk 5]
```diff
@@ -8,47 +13,65 @@ import { BooleanHolder } from "#app/utils/common";
...
 
     this.end();
   }
+
+  /**
+   * Attempt to eat all of a given {@linkcode Pokemon}'s berries once.
+   * @param pokemon The {@linkcode Pokemon} to check
+   */
+  eatBerries(pokemon: Pokemon): void {
+    // check if we even have anything to eat
```
Comment (DayKev) [inline src/phases/berry-phase.ts:36]:
```suggestion
```

File: src/phases/berry-phase.ts [hunk 6]
```diff
@@ -8,47 +13,65 @@ import { BooleanHolder } from "#app/utils/common";
...
+    const hasUsableBerry = !!globalScene.findModifier(m => {
+      return m instanceof BerryModifier && m.shouldApply(pokemon);
+    }, pokemon.isPlayer());
+    if (!hasUsableBerry) {
+      return;
+    }
+
+    // Check if any opponents have unnerve to block us from eating berries
```
Comment (DayKev) [inline src/phases/berry-phase.ts:44]:
```suggestion
```

File: src/phases/berry-phase.ts [hunk 7]
```diff
@@ -8,47 +13,65 @@ import { BooleanHolder } from "#app/utils/common";
...
+    if (cancelled.value) {
+      globalScene.queueMessage(
+        i18next.t("abilityTriggers:preventBerryUse", {
+          pokemonNameWithAffix: getPokemonNameWithAffix(pokemon),
+        }),
+      );
+      return;
+    }
+
+    // Play every endless player's least favorite animation
```
Comment (DayKev) [inline src/phases/berry-phase.ts:56]:
```suggestion
```

File: src/phases/berry-phase.ts [hunk 8]
```diff
@@ -8,47 +13,65 @@ import { BooleanHolder } from "#app/utils/common";
...
+    globalScene.unshiftPhase(
+      new CommonAnimPhase(pokemon.getBattlerIndex(), pokemon.getBattlerIndex(), CommonAnim.USE_ITEM),
+    );
+
+    // try to apply all berry modifiers for this pokemon
```
Comment (DayKev) [inline src/phases/berry-phase.ts:61]:
```suggestion
```

File: src/phases/berry-phase.ts [hunk 9]
```diff
@@ -8,47 +13,65 @@ import { BooleanHolder } from "#app/utils/common";
...
+    for (const berryModifier of globalScene.applyModifiers(BerryModifier, pokemon.isPlayer(), pokemon)) {
+      if (berryModifier.consumed) {
+        berryModifier.consumed = false;
+        pokemon.loseHeldItem(berryModifier);
+      }
+      // No need to track berries being eaten; already done inside applyModifiers
+      globalScene.eventTarget.dispatchEvent(new BerryUsedEvent(berryModifier));
+    }
+
+    // update held modifiers and such
```
Comment (DayKev) [inline src/phases/berry-phase.ts:71]:
```suggestion
```

File: src/phases/encounter-phase.ts [hunk 10]
```diff
@@ -342,8 +336,9 @@ export class EncounterPhase extends BattlePhase {
     }
 
     for (const pokemon of globalScene.getPlayerParty()) {
+      // Only reset wave data, not battle data
```
Comment (DayKev) [inline src/phases/encounter-phase.ts:339]:
```suggestion
      // Currently, a new wave is not considered a new battle if there is no arena reset
      // Therefore, we only reset wave data here
```

File: src/phases/move-phase.ts [hunk 11]
```diff
@@ -186,7 +186,7 @@ export class MovePhase extends BattlePhase {
 
     this.lapsePreMoveAndMoveTags();
 
-    if (!(this.failed || this.cancelled)) {
+    if (!this.failed && !this.cancelled) {
```
Comment (DayKev) [inline src/phases/move-phase.ts:189]:
```suggestion
    if (!(this.failed || this.cancelled)) {
```
There's a Biome rule that would do the opposite of what you did (aka make it look like it used to). Why did you change this?

File: src/phases/new-biome-encounter-phase.ts [hunk 12]
```diff
@@ -7,17 +7,16 @@ export class NewBiomeEncounterPhase extends NextEncounterPhase {
   doEncounter(): void {
     globalScene.playBgm(undefined, true);
 
+    // reset all battle data, perform form changes, etc.
```
Comment (DayKev) [inline src/phases/new-biome-encounter-phase.ts:10]:
```suggestion
```

File: src/phases/next-encounter-phase.ts [hunk 13]
```diff
@@ -9,9 +9,10 @@ export class NextEncounterPhase extends EncounterPhase {
   doEncounter(): void {
     globalScene.playBgm(undefined, true);
 
+    // Reset all player transient wave data/intel.
```
Comment (DayKev) [inline src/phases/next-encounter-phase.ts:12]:
```suggestion
```

File: src/system/game-data.ts [hunk 14]
```diff
@@ -1198,13 +1198,18 @@ export class GameData {
             }
           }
 
+          // load modifier data
+
```
Comment (DayKev) [inline src/system/game-data.ts:1202]:
```suggestion
```

File: src/system/game-data.ts [hunk 15]
```diff
@@ -1342,68 +1347,68 @@ export class GameData {
   }
 
   parseSessionData(dataStr: string): SessionSaveData {
+    // TODO: Add `null`/`undefined` to the corresponding type signatures for this
+    // (or prevent them from being null)
+    // If the value is able to *not exist*, it should say so in the code
+
```
Comment (DayKev) [inline src/system/game-data.ts:1353]:
```suggestion
```

File: src/utils/common.ts [hunk 16]
```diff
@@ -515,8 +502,8 @@ export function capitalizeString(str: string, sep: string, lowerFirstChar = true
   return null;
 }
 
-export function isNullOrUndefined(object: any): object is undefined | null {
-  return null === object || undefined === object;
+export function isNullOrUndefined(object: any): object is null | undefined {
+  return object === null || object === undefined;
```
Comment (DayKev) [inline src/utils/common.ts:506]: Technically the other way was better (you're not allowed to assign to `null` or `undefined`).

File: src/utils/data.ts [hunk 17]
```diff
@@ -0,0 +1,44 @@
...
+
+ * If a property in `src` does not exist in `dest` or its `typeof` evaluates differently, it is skipped.
+ * If it is a non-array object, its properties are recursed into and checked in turn.
+ * All other values are copied verbatim.
+ * @param dest The object to merge values into
+ * @param source The object to source merged values from
+ * @remarks Do not use for regular objects; this is specifically made for JSON copying.
+ * @see deepMergeObjects
+ */
+export function deepMergeSpriteData(dest: object, source: object) {
```
Comment (DayKev) [inline src/utils/data.ts:24]: Wanna make sure @SirzBenjie takes a look at this change

**Review by DayKev — COMMENTED** [review]
Partial review.

Comments should explain "why", not "what", unless the "what" is non-obvious (and usually that means the code should be refactored so that the "what" becomes obvious rather than adding comments).

File: src/phases/move-phase.ts (hunk 11 above)
Comment (Bertie690) [reply src/phases/move-phase.ts:189]: that is actually a very good question lol

File: src/utils/data.ts (hunk 17 above)
Comment (Bertie690) [reply src/utils/data.ts:24]: also that comment needs to be fixed

File: src/phases/move-phase.ts (hunk 11 above)
Comment (Bertie690) [reply src/phases/move-phase.ts:189]: Which rule is that again

Comment (DayKev) [reply src/phases/move-phase.ts:189]: https://biomejs.dev/linter/rules/use-simplified-logic-expression/
Specifically the fourth example that includes `const r4 = !boolExpr1 || !boolExpr2;`

File: src/data/pokemon-species.ts (hunk 1 above)
Comment (Bertie690) [reply src/data/pokemon-species.ts:885]: alright then

File: src/phases/battle-end-phase.ts (hunk 3 above)
Comment (Bertie690) [reply src/phases/battle-end-phase.ts:61]: Would this do?

File: src/phases/next-encounter-phase.ts (hunk 13 above)
Comment (Bertie690) [reply src/phases/next-encounter-phase.ts:12]:
```suggestion
    // Reset all player transient wave data/intel before starting a new wild encounter.
    // We exclusively reset wave data here as wild waves are considered one continuous "battle"
    // for lack of an arena transition
```

**Review by SirzBenjie — APPROVED** [review]

File: src/field/pokemon.ts [hunk 18]
```diff
@@ -350,13 +357,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
   public fusionCustomPokemonData: CustomPokemonData | null;
   public fusionTeraType: PokemonType;
 
-  private summonDataPrimer: PokemonSummonData | null;
+  public customPokemonData: CustomPokemonData = new CustomPokemonData;
```
Comment (DayKev) [inline src/field/pokemon.ts:360]:
```suggestion
  public customPokemonData: CustomPokemonData = new CustomPokemonData();
```

File: src/field/pokemon.ts [hunk 19]
```diff
@@ -350,13 +357,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
-  public battleSummonData: PokemonBattleSummonData;
-  public turnData: PokemonTurnData;
-  public customPokemonData: CustomPokemonData;
+  /* Pokemon data types, in vaguely decreasing order of precedence */
+
+  /**
+   * Data that resets only on *battle* end (hit count, harvest berries, etc.)
+   * Kept between waves.
+   */
+  public battleData: PokemonBattleData = new PokemonBattleData;
```
Comment (DayKev) [inline src/field/pokemon.ts:368]:
```suggestion
  public battleData: PokemonBattleData = new PokemonBattleData();
```

File: src/field/pokemon.ts [hunk 20]
```diff
@@ -350,13 +357,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+  /** Data that resets on switch or battle end (stat stages, battler tags, etc.) */
+  public summonData: PokemonSummonData = new PokemonSummonData;
```
Comment (DayKev) [inline src/field/pokemon.ts:370]:
```suggestion
  public summonData: PokemonSummonData = new PokemonSummonData();
```

File: src/field/pokemon.ts [hunk 21]
```diff
@@ -350,13 +357,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+  /** Wave data correponding to moves/ability information revealed */
+  public waveData: PokemonWaveData = new PokemonWaveData;
```
Comment (DayKev) [inline src/field/pokemon.ts:372]:
```suggestion
  public waveData: PokemonWaveData = new PokemonWaveData();
```

File: src/field/pokemon.ts [hunk 22]
```diff
@@ -350,13 +357,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+  /** Per-turn data like hit count & flinch tracking */
+  public turnData: PokemonTurnData = new PokemonTurnData;
```
Comment (DayKev) [inline src/field/pokemon.ts:374]:
```suggestion
  public turnData: PokemonTurnData = new PokemonTurnData();
```

File: src/field/pokemon.ts [hunk 23]
```diff
@@ -7706,49 +7742,105 @@ export interface AttackMoveResult {
...
+  /**
+   * An array of all moves this pokemon has used since entering the battle.
+   * Used for most moves and abilities that check prior move usage or copy already-used moves.
+   */
+  public moveHistory: TurnMove[] = [];
+
+  constructor(source?: PokemonSummonData | Partial<PokemonSummonData>) {
+    if (!isNullOrUndefined(source)) {
+      Object.assign(this, source)
+      // TODO: Do we need these mapping statements?
```
Comment (DayKev) [inline src/field/pokemon.ts:7796]: We do, since the save data doesn't contain the entire class structure.
```suggestion
```

File: src/field/pokemon.ts [hunk 24]
```diff
@@ -723,11 +717,38 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
     }
   }
 
+  /** Generate `abilityIndex` based on species and hidden ability if not pre-defined. */
+  public generateAbilityIndex(): number {
```
Comment (DayKev) [inline src/field/pokemon.ts:721]:
```suggestion
  private generateAbilityIndex(): number {
```

File: src/field/pokemon.ts [hunk 25]
```diff
@@ -844,13 +865,14 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
       );
     }
     if (this.getFusionSpeciesForm()) {
-      const fusionFormIndex = !!this.summonData?.illusion && useIllusion ? this.summonData?.illusion.fusionFormIndex : this.fusionFormIndex;
-      const fusionShiny = !!this.summonData?.illusion && !useIllusion ? this.summonData?.illusion.basePokemon!.fusionShiny : this.fusionShiny;
-      const fusionVariant = !!this.summonData?.illusion && !useIllusion ? this.summonData?.illusion.basePokemon!.fusionVariant : this.fusionVariant;
+      // TODO: why is fusionFormIndex using illusion if defined but fusionShiny/variant aren't?
```
Comment (DayKev) [inline src/field/pokemon.ts:868]: https://discord.com/channels/1125469663833370665/1176874654015684739/1365931115449159740
```suggestion
```

File: src/field/pokemon.ts (hunk 23 above)
Comment (Bertie690) [reply src/field/pokemon.ts]: For the `loadMove` one at least, all it does is simple property assignment

File: public/locales
[the remark this answers is not in the document]
Comment (Bertie690) [reply public/locales:1]: no
got to run `git update submodule --init --recursive' or whatever

File: src/field/pokemon.ts [hunk 26]
```diff
@@ -7776,6 +7866,12 @@ export class PokemonTurnData {
    * forced to act again in the same turn
    */
   public extraTurns = 0;
+  /**
+   * All berries eaten by this pokemon in this turn.
+   * Saved into {@linkcode PokemonBattleData | BattleData} by {@linkcode Pe at turn end.
```
Comment (DayKev) [inline src/field/pokemon.ts:7871]: Incomplete comment.

File: src/field/pokemon.ts [hunk 27]
```diff
@@ -4915,45 +4936,41 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
   }
 
-  findAndRemoveTags(tagFilter: (tag: BattlerTag) => boolean): boolean {
-    if (!this.summonData) {
-      return false;
-    }
+  /**
+   * Find and remove all {@linkcode BattlerTag}s matching the given function.
+   * @param tagFilter a function dictating which tags to remove
+  */
```
Comment (DayKev) [inline src/field/pokemon.ts:4955]:
```suggestion
   */
```

File: src/field/pokemon.ts [hunk 28]
```diff
@@ -7706,49 +7741,104 @@ export interface AttackMoveResult {
   sourceBattlerIndex: BattlerIndex;
 }
 
+/**
+Persistent in-battle data for a {@linkcode Pokemon}.
+Resets on switch or new battle.
+*/
```
Comment (DayKev) [inline src/field/pokemon.ts:7747]:
```suggestion
 * Persistent in-battle data for a {@linkcode Pokemon}.
 * Resets on switch or new battle.
 */
```

File: src/data/mystery-encounters/encounters/the-winstrate-challenge-encounter.ts [hunk 29]
```diff
@@ -222,7 +222,8 @@ function endTrainerBattleAndShowDialogue(): Promise<void> {
           globalScene.triggerPokemonFormChange(pokemon, SpeciesFormChangeAbilityTrigger);
         }
 
-        pokemon.resetBattleData();
+        // Each trainer battle is "supposed" to be a new fight, so reset all per-battle activation effects
```
Comment (DayKev) [inline src/data/mystery-encounters/encounters/the-winstrate-challenge-encounter.ts:225]:
```suggestion
        // Each trainer battle is supposed to be a new fight, so reset all per-battle activation effects
```

File: src/field/pokemon.ts (hunk 26 above)
Comment (Bertie690) [reply src/field/pokemon.ts:7871]: oops will edit tmr morning

**Comment by DayKev** [comment]
<details><summary>Graphics are broken</summary>
<p>

https://github.com/user-attachments/assets/e94b7d01-9d8e-453b-a000-2f19bc2e2f40

</p>
</details>

File: src/data/abilities/ability.ts [hunk 30]
```diff
@@ -4035,79 +4036,153 @@ export class PostTurnResetStatusAbAttr extends PostTurnAbAttr {
...
+
+    if (!this.berriesUnderCap.length) {
+      return false;
+    }
+
     // Clamp procChance to [0, 1]. Skip if didn't proc (less than pass)
-    const pass = Phaser.Math.RND.realInRange(0, 1);
-    return !(Math.max(Math.min(this.procChance(pokemon), 1), 0) < pass) && this.itemType === "EATEN_BERRIES" && !!pokemon.battleData.berriesEaten;
+    const pass = randSeedFloat();
+    return Phaser.Math.Clamp(this.procChance(pokemon), 1, 0) >= pass;
```
Comment (DayKev) [inline src/data/abilities/ability.ts:4077]:
```suggestion
    return Phaser.Math.Clamp(this.procChance(pokemon), 0, 1) >= pass;
```

File: src/data/moves/move.ts [hunk 31]
```diff
@@ -2686,16 +2695,22 @@ export class EatBerryAttr extends MoveEffectAttr {
 
     const heldBerries = this.getTargetHeldBerries(pokemon);
     if (heldBerries.length <= 0) {
+      // no berries makes munchlax very sad...
```
Comment (DayKev) [inline src/data/moves/move.ts:2698]:
```suggestion
```

File: src/data/moves/move.ts [hunk 32]
```diff
@@ -2711,46 +2726,69 @@ export class EatBerryAttr extends MoveEffectAttr {
...
+
+  /**
+   * Internal function to apply berry effects.
+   *
+   * @param consumer - The {@linkcode Pokemon} eating the berry; assumed to also be owner if `berryOwner` is omitted
+   * @param berryOwner - The {@linkcode Pokemon} whose berry is being eaten; defaults to `consumer` if not specified.
+   * @param updateHarvest - Whether to prevent harvest from tracking berries;
+   * defaults to whether `consumer` equals `berryOwner` (i.e. consuming own berry).
+   */
+   eatBerry(consumer: Pokemon, berryOwner: Pokemon = consumer, updateHarvest = consumer === berryOwner) {
```
Comment (DayKev) [inline src/data/moves/move.ts:2738]: If this is an internal function then it should be `protected` or `private`
```suggestion
   protected eatBerry(consumer: Pokemon, berryOwner: Pokemon = consumer, updateHarvest = consumer === berryOwner) {
```

File: src/data/moves/move.ts [hunk 33]
```diff
@@ -2711,46 +2726,69 @@ export class EatBerryAttr extends MoveEffectAttr {
...
+   * @param move - The {@linkcode Move} being used
+   * @param args N/A
+   * @returns `true` if the function succeeds
    */
   apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
+    // Stealing fails against substitute
+    if (move.hitsSubstitute(user, target)) {
+      return false;
+    }
+
```
Comment (DayKev) [inline src/data/moves/move.ts:2769]: This should be handled automatically in move effect phase now. If it's not then that's a bug.
```suggestion
```

File: src/phases/berry-phase.ts [hunk 34]
```diff
@@ -8,47 +13,63 @@ import { BooleanHolder } from "#app/utils/common";
...
+    globalScene.unshiftPhase(
+      new CommonAnimPhase(pokemon.getBattlerIndex(), pokemon.getBattlerIndex(), CommonAnim.USE_ITEM),
+    );
+
+    for (const berryModifier of globalScene.applyModifiers(BerryModifier, pokemon.isPlayer(), pokemon)) {
+      if (berryModifier.consumed) {
+        berryModifier.consumed = false;
+        pokemon.loseHeldItem(berryModifier);
+      }
+      // No need to track berries being eaten; already done inside applyModifiers
```
[the remark this answers is not in the document]
Comment (Bertie690) [reply src/phases/berry-phase.ts:67]: No it's in general
Normally everywhere that consumes berries is supposed to call `consumer.recordEatenBerry` to push to the battleData arrays and such, but here it's already done when the berry modifiers are applied

File: src/phases/switch-summon-phase.ts [hunk 35]
```diff
@@ -240,6 +241,7 @@ export class SwitchSummonPhase extends SummonPhase {
       }
     }
 
+    // No need (or particular use) resetting turn data here on initial send in
```
[the remark this answers is not in the document]
Comment (Bertie690) [reply src/phases/switch-summon-phase.ts:244]: fake out isn't in turn data - it's in summon data
Turn data isn't saved to the file and is set to its zero value by default anyways (I made sure of that)

**Review by SirzBenjie — APPROVED** [review]

**Comment by DayKev** [comment]
It turns out that `BattleSummonData` was not saved in the save data, but by moving it into `SummonData` those fields will now be added to the save data, increasing save file size.

File: src/phases/switch-summon-phase.ts (hunk 35 above)
[the remark this answers is not in the document]
Comment (DayKev) [reply src/phases/switch-summon-phase.ts]: So the behavior is changed then. The original reason for this not applying to "Initial Switch" was because of bugs if it did.

File: src/utils/data.ts (hunk 17 above)
Comment (SirzBenjie) [reply src/utils/data.ts:23]: it's good.

**Review by SirzBenjie — APPROVED** [review]

**Review by SirzBenjie — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]
