### PR TITLE
[P2 Bug] Revert to normal form when Pokémon is fainted

### LINKED ISSUE #4029: [Bug] Aegislash's Stance Change does Not Revert to Shield Forme upon Fainting
### Describe the bug

Aegislash does not revert to shield forme when fainted by a move. This allows it to be sent out in Blade Forme after being revived.

-Aegislash only reverts to Shield Forme when it is recalled from the field. Otherwise, it never reverts to Blade Forme.

Link to Discord's Bug Report: (stance change not working properly)
https://discord.com/channels/1125469663833370665/1280252752634576947

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

Aegislash should revert to Shield Forme upon fainting.
https://replay.pokemonshowdown.com/gen9customgame-2194759718-teekv7nn3cye4h2sh7qhii811un5tf4pw

### Screenshots / Videos

Screenshot (292)

After reviving

https://github.com/user-attachments/assets/c6dc939c-fb92-43a8-806e-f711019616a0

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by torranx**
## What are the changes the user will see?
all pokemon that changed form and fainted in battle will now revert to their normal form

## Why am I making these changes?
closes #4029 , this not only affects Aegislash but all other pokemon that can change form like Castform, Cramorant, etc

## What are the changes from a developer perspective?
added form change trigger in faint-phase

### Screenshots/Videos
Castform

https://github.com/user-attachments/assets/af0193ea-e13e-46cf-ad2b-efed00ac7701

Meloetta

https://github.com/user-attachments/assets/623fe16f-1067-4911-85fc-0c3b288d4008

Aegislash

https://github.com/user-attachments/assets/9c9050f8-707a-4e1b-a810-973b9dd821af

Xerneas

https://github.com/user-attachments/assets/aefa77f5-f82f-4f22-b55e-0024f427f293

Cramorant

https://github.com/user-attachments/assets/24b0ed6a-4762-4bf8-a7e3-513880b9d3e2

## How to test the changes?
Overrides used, change species accordingly:
```
{
  STARTER_FORM_OVERRIDES: {
    [Species.MELOETTA]: 1,
    [Species.CASTFORM]: 1,
    [Species.AEGISLASH]: 1,
    [Species.XERNEAS]: 1,
    [Species.CRAMORANT]: 1,
  },
  STARTER_SPECIES_OVERRIDE: Species.CRAMORANT,
  OPP_LEVEL_OVERRIDE: 50,
}
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

File: src/phases/faint-phase.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ import { ToggleDoublePositionPhase } from "./toggle-double-position-phase";
 import { GameOverPhase } from "./game-over-phase";
 import { SwitchPhase } from "./switch-phase";
 import { VictoryPhase } from "./victory-phase";
+import { SpeciesFormChangeActiveTrigger } from "#app/data/pokemon-forms.js";
```
Comment (flx-sta) [inline src/phases/faint-phase.ts:20]: Groundhog day
```suggestion
import { SpeciesFormChangeActiveTrigger } from "#app/data/pokemon-forms";
```

**Review by flx-sta — CHANGES_REQUESTED** [review]

**Review by DayKev — APPROVED** [review]

**Review by CodeTappert — APPROVED** [review]

**Review by frutescens — APPROVED** [review]
