### PR TITLE
[Refactor] `Pokemon.leaveField()` (fixes epic weather abilities)

### LINKED ISSUE #3385: [Bug] Desolate Land persists when the Pokemon is switched out during the transition between a double battle & single battle
### Describe the bug

Desolate Land persisted even when the Pokemon with the ability was switched out during the transition between a (wild) double battle to a (wild) single battle.

### User data export file

[data_YamitheYin.txt](https://github.com/user-attachments/files/16513378/data_YamitheYin.txt)

### Session export file

[sessionData1_YamitheYin.txt](https://github.com/user-attachments/files/16513386/sessionData1_YamitheYin.txt)

### Expected behavior

Harsh sunlight is supposed to dissipate when the only ability holder of Desolate Land leaves the field.

### Screenshots / Videos

https://github.com/user-attachments/assets/18aaacb4-e147-4a9b-8b7d-1238629261f3

### What OS did you observe the bug on?

PC/Windows

### If other please specify

_No response_

### Which browser do you use?

Chrome

### If other please specify

_No response_

### Additional context

_No response_

### LINKED ISSUE #5158: [Bug] Legendary Weather (Desolate Land, Primordial Sea, Delta Stream) persist past Biome Transition, Trainer Transition, ME Transition
### Describe the bug

Legendary Weather; Desolate Land, Primordial Sea, and Delta Stream does not disappear on Pokemon recall on Biome Transitions, Trainer Battle Transitions, and Mystery Encounter Transitions.
-This can have profound effects on battles from that point on, as the weather lasts until a Pokemon with a Weather Ability is sent out.
- It might also revert back with Biome Weather.

The block of code that seems to clear the Arena's Terrain and Weather does not seem to include Legendary Weather
https://github.com/pagefaultgames/pokerogue/blob/f3256ec5d4c1a900d093768977374464f32339cb/src/field/arena.ts#L685

Link to Discord's Bug Report (Primordial sea active even when manaphy not in)
https://discord.com/channels/1125469663833370665/1294538878404788234

### Reproduction

Choose Kyogre and Castform, you'll need to switch Primal Kyogre back in to activate Heavy Rain.

```
    STARTING_WAVE_OVERRIDE: 11,

    OPP_MOVESET_OVERRIDE: [Moves.SPLASH],

    MYSTERY_ENCOUNTER_RATE_OVERRIDE: 123,

    MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.GLOBAL_TRADE_SYSTEM,
    ITEM_REWARD_OVERRIDE: [{name: "FORM_CHANGE_ITEM", type: FormChangeItem.BLUE_ORB}],

    STARTING_MODIFIER_OVERRIDE: [{name: "MEGA_BRACELET"}],

```
Or, change starting wave to 3, Primal evolve Kyogre, and watch Heavy Rain not dissipate on recall from the Endless Biome Transition 5 -> 6 or the Classic Youngster.

### Expected behavior

Heavy Rain, Delta Stream, and Harsh Sun should not persist while their user is not on the field.

### Screenshots / Videos

Heavy Rain persists after GTS has started, Pokemon removed from Party

https://github.com/user-attachments/assets/7862031a-3f6b-4a36-b697-b528eb4f970f

Gravity is cleared but Heavy Rain is not on transition to a Trainer Battle

https://github.com/user-attachments/assets/564689df-e64c-40f9-8d55-96fbf01b5397

Heavy Rain exists after Weird Dream despite Primal Kyogre being Transmogrified.

Image

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Wlowscha**
## What are the changes the user will see?
Epic Weather (EW) ends properly when no mons with Desolate Land/Primordial Sea/Delta Stream are on the field. 

## Why am I making these changes?
Fixing the EW abilities offer a chance to rework a bit the logic for pokemon leaving the field. In the current code, the Pokemon class has a leaveField method which handles clearing data, resetting forms, and calling globalScene.field.remove(pokemon). This function is called in some cases, for example when a pokemon switches out, but not in others, for example when a pokemon faints or is caught: in the latter cases, similar logic is handled directly in FaintPhase or AttemptCapturePhase. Standardizing the logic in all cases allows to implement the ending condition for the EW abilities in a very straightforward manner. It also makes things easier in case in the future other effects with similar logic are introduced.

Fixes #3385
Fixes #5158 
Closes #3493

## What are the changes from a developer perspective?
1) Removed the PreSwitchOutClearWeatherAbAttr and PostFaintClearWeatherAbAttr. These abilities only handle specific cases of a more general condition (leaving the field). Note in particular that in all other cases (Regenerator, Natural Cure, Zero to Hero) the PreSwitchOut attributes trigger _only_ when the pokemon is switched out, but not when the pokemon is recalled, for example being in the second slot when passing from a double to a single battle.

2) Introduced a new PreLeaveFieldClearWeatherAbAttr which extends the new PreLeaveFieldAbAttr class. This attribute class is now applied as a part of the pokemon.leaveField() method.

3) The pokemon.leaveField() has been updated to:
3.1) Remove all tags generated by the pokemon that is switching out (this was already done in the various cases where leaveField() was called);
3.2) Give the option to pass the destroy=true option to globalScene.field, which was requested in some mystery encounters.

4) Where pokemon.leaveField() was already present, the logic has been cleaned up to avoid redundancies (e.g. with removing tags). This is essentially the switch out logic. Note that leaveField() is also called in turn-init-phase.ts to handle the passage from double to single battle.
Where only globalScene.field.remove(pokemon) was being called, it has been replaced by pokemon.leaveField(), again ensuring that there is no redundancy. This is particularly important in the faint phase (because the leaveField condition is replacing the postFaint condition) and in the attempt capture phase (until now, weather would not go away after catching e.g. a boss magcargo).

5) In switch-summon-phase.ts, the .leaveField() call has been postponed, so that all PreSwitchOut ability attributes actually trigger before the pokemon is removed from the field. Although this does not directly affect the weather abilities, it is included in the refactoring to align what happens in the code with expectations (being called PreSwitchOut and not PostSwitchOut).

-----Tests-----

A new file for tests on Desolate Land has been added. The tests use magcargo with its passive unlocked. Four tests check that:
1) If two magcargo are on the field, the EW disappears only after both have left the field.
2) If enemy magcargo faints, the EW disappears.
3) If enemy magcargo is caught, the EW disappears.
4) If magcargo is second in the party, the EW disappears going from double to single battle.

The tests have required some additions, in particular an override to simply unlock passives (rather than setting a passive for the whole party or the whole enemy team---this is necessary to avoid everything having desolate land which would invalidate the tests); and a function in the game manager to throw a ball and attempt a catch. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

**Comment by Wlowscha** [comment]
This PR fixes issue #3385:
https://github.com/user-attachments/assets/326d5d1b-a4b1-4372-a01a-cf2cc3327316

It also partially addresses #5158 e.g. by clearing the weather when transitioning to a trainer battle:
https://github.com/user-attachments/assets/cd6b4ced-8efb-455a-865f-f96d062ccda3

Other parts of this issue (some mystery encounters and the weather not changing right away when activating the orb) are still open.

**Comment by Wlowscha** [comment]
Actually, the mystery encounters in #5158 might be fixed too. The epic weather will end before the start of the encounter. As long as (for example) Primal Kyogre is traded or transmogrified without being summoned to the field again, the weather will remain clear. However I have not tested this.

**Comment by Wlowscha** [comment]
Confirming that the weird ME interactions from #5158 are fixed:
https://github.com/user-attachments/assets/2ff2e9c3-7460-499a-87f8-8e83406f3e03
https://github.com/user-attachments/assets/5dd2eadf-7cb8-4bfd-9c25-e91a7193f616

File: src/overrides.ts [hunk 1]
```diff
@@ -129,6 +129,7 @@ class DefaultOverrides {
   readonly STARTER_FUSION_SPECIES_OVERRIDE: Species | integer = 0;
   readonly ABILITY_OVERRIDE: Abilities = Abilities.NONE;
   readonly PASSIVE_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
+  readonly HAS_PASSIVE_ABILITY_OVERRIDE: boolean = false;
```
[the remark this answers is not in the document]
Comment (Wlowscha) [reply src/overrides.ts]: Done!

File: src/test/abilities/desolate-land.test.ts [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+   */
+  it("should lift only when all pokemon with this ability leave the field", async () => {
+    game.override
+      .battleType("double")
+      .enemyMoveset([ Moves.SPLASH, Moves.ROAR ]);
+    await game.classicMode.startBattle([ Species.MAGCARGO, Species.MAGCARGO, Species.MAGIKARP, Species.MAGIKARP ]);
+
+    expect(game.scene.arena.weather?.weatherType).toBe(WeatherType.HARSH_SUN);
+
+    vi.spyOn(game.scene, "randBattleSeedInt").mockImplementation((range, min: number = 0) => {
```
Comment (DayKev) [inline src/test/abilities/desolate-land.test.ts:46]: What is the RNG mock for?

File: src/test/abilities/desolate-land.test.ts [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+      return min;
+    });
+
+    game.move.select(Moves.SPLASH, 0, 2);
+    game.move.select(Moves.SPLASH, 1, 2);
+
+    await game.forceEnemyMove(Moves.ROAR, 0);
```
Comment (DayKev) [inline src/test/abilities/desolate-land.test.ts:53]: Is it okay to let the second enemy choose its move and target on its own?

File: src/test/utils/gameManager.ts [hunk 4]
```diff
@@ -458,6 +459,24 @@ export default class GameManager {
...
 
+  doThrowPokeball(ballIndex: number) {
+    this.onNextPrompt("CommandPhase", Mode.COMMAND, () => {
+      (this.scene.ui.getHandler() as CommandUiHandler).setCursor(1);
+      (this.scene.ui.getHandler() as CommandUiHandler).processInput(Button.ACTION);
+    });
+
+    this.doSelectPokeball(ballIndex);
+  }
+  // ???
```
Comment (DayKev) [inline src/test/utils/gameManager.ts:470]: I assume you forgot to update this comment?

File: src/test/utils/helpers/overridesHelper.ts [hunk 5]
```diff
@@ -181,6 +181,11 @@ export class OverridesHelper extends GameManagerHelper {
     return this;
   }
 
+  public hasPassiveAbility(hasPassiveAbility: boolean): this {
```
Comment (DayKev) [inline src/test/utils/helpers/overridesHelper.ts:184]:
```suggestion
  public hasPassiveAbility(hasPassiveAbility: boolean | null): this {
```

File: src/test/utils/helpers/overridesHelper.ts [hunk 6]
```diff
@@ -181,6 +181,11 @@ export class OverridesHelper extends GameManagerHelper {
...
+    vi.spyOn(Overrides, "HAS_PASSIVE_ABILITY_OVERRIDE", "get").mockReturnValue(hasPassiveAbility);
+    this.log("Player Pokemon PASSIVE ability is active!");
```
Comment (DayKev) [inline src/test/utils/helpers/overridesHelper.ts:186]:
```suggestion
    if (hasPassiveAbility === null) {
      this.log("Player Pokemon PASSIVE ability no longer force enabled or disabled!");
    }
    else {
      this.log("Player Pokemon PASSIVE ability is force ${hasPassiveAbility ? "enabled" : "disabled"}!");
    }
```

File: src/test/utils/helpers/overridesHelper.ts [hunk 7]
```diff
@@ -325,6 +330,12 @@ export class OverridesHelper extends GameManagerHelper {
     return this;
   }
 
+  public enemyHasPassiveAbility(hasPassiveAbility: boolean): this {
```
Comment (DayKev) [inline src/test/utils/helpers/overridesHelper.ts:333]:
```suggestion
  public enemyHasPassiveAbility(hasPassiveAbility: boolean | null): this {
```

File: src/test/utils/helpers/overridesHelper.ts [hunk 8]
```diff
@@ -325,6 +330,12 @@ export class OverridesHelper extends GameManagerHelper {
...
+    vi.spyOn(Overrides, "OPP_HAS_PASSIVE_ABILITY_OVERRIDE", "get").mockReturnValue(hasPassiveAbility);
+    this.log("Enemy Pokemon PASSIVE ability is active!");
```
Comment (DayKev) [inline src/test/utils/helpers/overridesHelper.ts:335]:
```suggestion
    if (hasPassiveAbility === null) {
      this.log("Enemy Pokemon PASSIVE ability no longer force enabled or disabled!");
    }
    else {
      this.log("Enemy Pokemon PASSIVE ability is force ${hasPassiveAbility ? "enabled" : "disabled"}!");
    }
```

File: src/test/abilities/desolate-land.test.ts (hunk 2 above)
Comment (Wlowscha) [reply src/test/abilities/desolate-land.test.ts:46]: This is necessary to fix what mons are brought out by roar, without the rng mocks, the first magcargo may come out again, which makes the test fail since the harsh sunlight does not go away

Comment (DayKev) [reply src/test/abilities/desolate-land.test.ts:46]: Ah, gotcha.

File: src/test/utils/gameManager.ts [hunk 9]
```diff
@@ -458,6 +459,24 @@ export default class GameManager {
     });
   }
 
+  doThrowPokeball(ballIndex: number) {
```
Comment (DayKev) [inline src/test/utils/gameManager.ts:462]:
```suggestion
  public doThrowPokeball(ballIndex: number): void {
```
Should have some tsdocs.

File: src/test/utils/gameManager.ts [hunk 10]
```diff
@@ -458,6 +459,24 @@ export default class GameManager {
...
+    this.onNextPrompt("CommandPhase", Mode.COMMAND, () => {
+      (this.scene.ui.getHandler() as CommandUiHandler).setCursor(1);
+      (this.scene.ui.getHandler() as CommandUiHandler).processInput(Button.ACTION);
+    });
+
+    this.doSelectPokeball(ballIndex);
+  }
+
+  doSelectPokeball(ballIndex: number) {
```
Comment (DayKev) [inline src/test/utils/gameManager.ts:471]:
```suggestion
  private doSelectPokeball(ballIndex: number): void {
```

File: src/test/utils/helpers/overridesHelper.ts [hunk 11]
```diff
@@ -181,6 +181,15 @@ export class OverridesHelper extends GameManagerHelper {
     return this;
   }
 
+  public hasPassiveAbility(hasPassiveAbility: boolean | null): this {
```
Comment (DayKev) [inline src/test/utils/helpers/overridesHelper.ts:184]: Needs tsdocs.

File: src/test/utils/helpers/overridesHelper.ts [hunk 12]
```diff
@@ -325,6 +334,16 @@ export class OverridesHelper extends GameManagerHelper {
     return this;
   }
 
+  public enemyHasPassiveAbility(hasPassiveAbility: boolean | null): this {
```
Comment (DayKev) [inline src/test/utils/helpers/overridesHelper.ts:337]: Needs tsdocs.

**Review by DayKev — COMMENTED** [review]
Last issues then it's good to go.

File: src/test/utils/gameManager.ts (hunk 9 above)
Comment (Wlowscha) [reply src/test/utils/gameManager.ts]: Actually, writing the tsdocs made me realise there was no point to having two separate functions for the ball throw, so I merged them.

**Review by DayKev — APPROVED** [review]

**Review by xsn34kzx — APPROVED** [review]
