### PR TITLE
[Bug] Fix Recoil Damage and Shell Bell Healing Not Applying When Hitting Substitute

### LINKED ISSUE #5090: [Bug] Recoil Moves don't take Recoil After Hitting a Substitute
### Describe the bug

Moves that have recoil do not damage the User after successfully hitting a Substitute.

Link to Discord's Bug Report (Attacking substitute with a recoil move does not damage the user)
https://discord.com/channels/1125469663833370665/1311707124191199334

### Reproduction

Use Double Edge or any other recoil move against any Pokemon behind a Substitute.
(Moves with RecoilAttr such as Light of Ruin, Chloroblast, Take Down, Submission, Wave Crash, and Wood Hammer.)

### Expected behavior

https://replay.pokemonshowdown.com/gen9customgame-2275748334
Pokemon should take an appropriate amount of recoil damage after damaging a Substitute.

### Screenshots / Videos

https://github.com/user-attachments/assets/8965a448-e727-469e-96fb-a7fe76ad9721

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Desroi**
## What are the changes the user will see?
Users will now see their Pokemon taking damage when hitting an opponent with substitute up with a recoil move. It also now heals your Pokemon when hitting a substitute doll.

## Why am I making these changes?

Fixes #5090 
This enhances the user experience so it feels more inline with how the interaction plays out in mainline games 

## What are the changes from a developer perspective?

One file changed: move-effect-phase
-In the logic, the damage applied to the substitute doll gets applied but then it is not tracked anywhere else. This caused the logic for calculating recoil damage to not work. By simply adding in an if-else statement to handle tracking the proper amount of damage dealt to substitute to the _totalDamageDealt_, recoil damage is able to be properly applied.

## How to test the changes?

I have added a test file called _recoil-moves-test.ts_
_\test\moves\recoil-moves.test.ts_

Running **npx vitest run recoil-moves.test.ts** will test every recoil move against a substitute doll and will either pass if recoil damage is taken or fail if it is not. After those, it will test a double battle, where both player Pokemon will hit a substitute doll; the test will pass if recoil is felt, and fail otherwise. For the double battle, I have the HP's of both the player Pokemon printed, so you can see and calculate the damage yourself to make sure it is right.

### Before (For Shell Bell)

https://github.com/user-attachments/assets/d3d34350-9482-482e-b358-533fe074a5a8

### After (For Shell Bell)

https://github.com/user-attachments/assets/c6cb59c8-515e-4fdf-827e-5037918084a6

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [ ] If so, please leave a link to it here: 
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

**Review by DayKev — COMMENTED** [review]
Left review suggestions here: https://github.com/Desroi/pokerogue/pull/1

**Review by DayKev — DISMISSED** [review]

File: src/phases/move-effect-phase.ts [hunk 1]
```diff
@@ -844,6 +844,11 @@ export class MoveEffectPhase extends PokemonPhase {
     const isBlockedBySubstitute = substitute && this.move.hitsSubstitute(user, target);
     if (isBlockedBySubstitute) {
       substitute.hp -= dmg;
+      if (substitute.hp >= dmg) {
+        user.turnData.totalDamageDealt += dmg;
```
[the remark this answers is not in the document]
Comment (DayKev) [reply src/phases/move-effect-phase.ts:848]: Okay, so it *is* wrong. I thought it was at first, but then somehow convinced myself it worked.

[the remark this answers is not in the document]
Comment (Desroi) [reply src/phases/move-effect-phase.ts:848]: You're so right, that is my error in logic. I will correct it

**Review by Wlowscha — APPROVED** [review]

File: test/moves/recoil-moves.test.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+
+  it("causes recoil damage when hitting a substitute in a double battle", async () => {
+    game.override.battleStyle("double").moveset([Moves.DOUBLE_EDGE]);
+
+    await game.classicMode.startBattle([Species.TOGEPI, Species.TOGEPI]);
+
+    const [playerPokemon1, playerPokemon2] = game.scene.getPlayerField();
+
+    game.move.select(Moves.DOUBLE_EDGE, 0);
+    game.move.select(Moves.DOUBLE_EDGE, 1);
```
Comment (Bertie690) [inline test/moves/recoil-moves.test.ts:68]: Minor nit:
```suggestion
    game.move.select(Moves.DOUBLE_EDGE, BattlerIndex.PLAYER, BattlerIndex.ENEMY);
    game.move.select(Moves.DOUBLE_EDGE, BattlerIndex.PLAYER_2, BattlerIndex.ENEMY_2);
```
(need to add the import as well)

File: test/moves/recoil-moves.test.ts [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+    { moveName: "Volt Tackle", moveId: Moves.VOLT_TACKLE },
+    { moveName: "Wave Crash", moveId: Moves.WAVE_CRASH },
+    { moveName: "Wild Charge", moveId: Moves.WILD_CHARGE },
+    { moveName: "Wood Hammer", moveId: Moves.WOOD_HAMMER },
+  ])("$moveName causes recoil damage when hitting a substitute", async ({ moveId }) => {
+    game.override.moveset([moveId]);
+    await game.classicMode.startBattle([Species.TOGEPI]);
+
+    game.move.select(moveId);
+    await game.toNextTurn();
```
Comment (Bertie690) [inline test/moves/recoil-moves.test.ts:54]: I might be paranoid, but can we get an statement checking that the substitute was actually applied (and took damage)? 
something like 
```suggestion
  await game.phaseInterceptor.to("MoveEndPhase") // Pidove substitute

  const pidove = game.scene.getEnemyPokemon()!;
  const subTag = pidove.getTag(BattlerTagType.SUBSTITUTE)!;
  expect(subTag).toBeDefined();
  const subInitialHp = subTag.hp;

  await game.phaseInterceptor.to("MoveEndPhase"); // player attack
  
  expect(subTag.hp).toBeLessThan(subInitialHp);
```

Comment (Bertie690) [reply test/moves/recoil-moves.test.ts:54]: You'll need to add an import fwiw

**Review by SirzBenjie — COMMENTED** [review]
This looks good, though I agree with Bertie's comments.

**Review by DayKev — DISMISSED** [review]

File: src/phases/move-effect-phase.ts [hunk 4]
```diff
@@ -829,6 +829,11 @@ export class MoveEffectPhase extends PokemonPhase {
     const substitute = target.getTag(SubstituteTag);
     const isBlockedBySubstitute = substitute && this.move.hitsSubstitute(user, target);
     if (isBlockedBySubstitute) {
+      if (substitute.hp >= dmg) {
+        user.turnData.totalDamageDealt += dmg;
+      } else {
+        user.turnData.totalDamageDealt += substitute.hp;
+      }
```
Comment (SirzBenjie) [inline src/phases/move-effect-phase.ts]:
```suggestion
      user.turnData.totalDamageDealt += Math.min(dmg, substitute.hp);
```

Comment (DayKev) [reply src/phases/move-effect-phase.ts]: Hm, I think that's right.

**Review by xsn34kzx — APPROVED** [review]

**Review by SirzBenjie — APPROVED** [review]
