### PR TITLE
[Bug][Move] Struggle no longer gets STAB

### LINKED ISSUE #5490: [Bug] Struggle is Activated by Adaptability
### Describe the bug

Struggle is affected by Adaptability

Link to Discord's Bug Report (Adaptability trigger on normal type struggle)
https://discord.com/channels/1125469663833370665/1347317663650807859

### Reproduction

Use Rapid Spin until the opponent faints, then use Struggle.

```
	STARTER_SPECIES_OVERRIDE: Species.RATTATA,
	MOVESET_OVERRIDE: [Moves.RAPID_SPIN],
	ABILITY_OVERRIDE: Abilities.ADAPTABILITY,

	OPP_LEVEL_OVERRIDE: 3,
	OPP_SPECIES_OVERRIDE: Species.SHROOMISH,
	OPP_MOVESET_OVERRIDE: [Moves.GRUDGE],
```

### Expected behavior

https://replay.pokemonshowdown.com/gen9customgame-2314011640

Struggle should be unaffected by Adaptability.

### Screenshots / Videos

https://github.com/user-attachments/assets/15cbb54c-4efe-4614-91fb-7c00b460c235

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SirzBenjie**
## What are the changes the user will see?
Struggle will no longer be impacted by stab.

## Why am I making these changes?
Fixes #5490

## What are the changes from a developer perspective?
Did some minor cleanup of ``pokemon.getAttackDamage`` while I was editing the file.
Extracted out the calculation of stab effectiveness into its own method that is called by `getAttackDamage`. The first thing the method does is check if the move has the typeless attribute. If it does, the method immediately returns with 1.

## Screenshots/Videos
There's not a good way of providing a screenshot for this.

## How to test the changes?
`npm run test:silent test/moves/struggle.test.ts`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- ~~[ ] Have I tested the changes manually?~~
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- ~~[ ] Have I provided screenshots/videos of the changes (if applicable)?~~
  - ~~[ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -3961,6 +3961,66 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+    const sourceTeraType = source.getTeraType();
+    const moveType = source.getMoveType(move);
+    const matchesSourceType = sourceTypes.includes(source.getMoveType(move));
+    const stabMultiplier = new Utils.NumberHolder(1);
+    if (matchesSourceType && moveType !== PokemonType.STELLAR) {
+      stabMultiplier.value += 0.5;
+    }
+
+    if (!ignoreSourceAbility) {
+      applyAbAttrs(StabBoostAbAttr, source, null, simulated, stabMultiplier);
```
Comment (DayKev) [inline src/field/pokemon.ts:3989]: Can you move this below the `CombinedPledgeStabBoostAttr` application? Xavion accidentally moved it in his Tera rework PR.

File: test/moves/struggle.test.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    const enemy = game.scene.getEnemyPokemon()!;
+    game.move.select(Moves.STRUGGLE);
+
+    const stabSpy = vi.spyOn(enemy, "calculateStabMultiplier");
+
+    await game.phaseInterceptor.to("BerryPhase");
+
+    expect(stabSpy).toHaveReturnedWith(1);
+
+    stabSpy.mockRestore();
```
Comment (DayKev) [inline test/moves/struggle.test.ts:47]: Instead of manually using `.mockRestore()` maybe we should just enable the setting that automatically calls it on all spies? https://vitest.dev/config/#restoremocks

**Review by Madmadness65 — APPROVED** [review]
