### PR TITLE
[Bug][Move] Fix forced switch bugs in enemy partner trainer battles

### LINKED ISSUE #5394: [Bug] Phasing Pokemon In Doubles Trainer Battles Does Not Consider Split Party
### Describe the bug

Using a Phasing move such as Roar, Whirlwind, Dragon Tail or Circle Throw does not consider the difference in party of Trainers in Double battles. Instead, it considers both trainers as a single Party when forcing a Pokemon out.

- If the Phasing Move would bring out a Pokemon from the other Trainer's Party, then no more Pokemon are sent out after the ones on the Field have fainted. This Softlocks the game.

Discord's Bug Report (Using Phasing moves in Doubles Trainer Battle (Dragon Tail, Roar), Softlocks)
https://discord.com/channels/1125469663833370665/1290728464235761706

### Reproduction

Left Grunt has a Scolipede, Garbodor, Galvantula

Right Grunt has a Watchog, Swoobat, Rufflet

If at any point Whirlwind brings out a Pokemon from the other Trainer's party, Trainers will no longer send out new Pokemon after the current ones have fainted, and the battle will never end.

```
	STARTING_WAVE_OVERRIDE: 62,

	STARTING_LEVEL_OVERRIDE: 70,

	MOVESET_OVERRIDE: [Moves.WHIRLWIND, Moves.ERUPTION],

        OPP_MOVESET_OVERRIDE: [Moves.SPLASH],
```

### Expected behavior

Phasing Moves should only bring out the Pokemon from the correct Trainer.

### Screenshots / Videos

<details><summary>2 Left, 1 Right
</summary>
Phase Left (2 Pokemon)

https://github.com/user-attachments/assets/55b3b28b-3606-4095-bf26-98f25169ff19

Phase Right, (1 Pokemon)

https://github.com/user-attachments/assets/4ee1927c-a570-42a8-8816-e284670cb1bd

</details>

3 and 3

https://github.com/user-attachments/assets/15668bc6-d2b5-42e7-85e7-fce54095b10d

### Session export file

[DoublesTrainer.txt](https://github.com/user-attachments/files/18916065/DoublesTrainer.txt)

### User data export file

_No response_

### PR DESCRIPTION
**Pull request by SirzBenjie**
## What are the changes the user will see?
Moves that allow or force the target to switch out will no longer allow an enemy trainer duo to send out their partner's pokemon. This prevents the softlock from occuring.

## Why am I making these changes?
Fixes #5394

## What are the changes from a developer perspective?
The primary source of the bug was that the `getSwitchoutCondition` was prematurely returning with either true or false in some cases, specifically the line:

``return !blockedByAbility.value;``

This would prevent the remainder of the logic in that method, which crucially already included a check against the proper trainer having an adequate pokemon, form running.
I fixed this to no longer unconditionally return.

I also did some other cleanup inside of the method.

I also added an override for forcing a battle type. I renamed the existing `BATTLE_TYPE_OVERRIDE` to `BATTLE_STYLE_OVERRIDE` (because battle type is our name for the enum determining wild, etc...), and then used this `BATTLE_TYPE_OVERRIDE` to allow a battle type to be forced. This only overrides non-scripted battles.

This required pulling out the `BattleType` enum from the `battle-scene` file and into its own file.
I did this and updated all of the imports.

I also added an override, `RANDOM_TRAINER_OVERRIDE` which will override the trainer chosen when a random trainer is needed. This has two fields, one for allowing specifying the trainer type, and another that will force the trainer to be the partner version (that is only applied if the trainer is actually allowed to have a partner).

Lastly, fixed some improper uses of the comma operator that biome was yelling about in test files that were touched by the rename.

## Screenshots/Videos

In the video below, notice how the enemy partner trainer has 2 pokemon each. Notice how first, I faint one of the trainer's pokemon, and then use whirlwind on that same enemy. The enemy is not able to switch to a pokemon from its ally's party
<details><summary>Proper switching interaction </summary>

https://github.com/user-attachments/assets/dc7e6974-49d8-42bc-80a4-526c1d478e04
</details>

## How to test the changes?
`npm run test:silent test/moves/whirlwind.test.ts`

## Additional Notes

There are more latent bugs with the forced switchout moves. However, they cannot be addressed or fixed with the current state of the move effect phase. Of note is #5010.

Note that the fix I applied here also does not address the fact that the failure isn't supposed to occur before the semi-invulnerability check. This can't easily be done until the MEP phase is fixed..

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs? Sort of... too many bugs in this one, didn't want to wait for PRs
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - ~~[ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

### CODE REVIEW

File: src/battle-scene.ts [hunk 1]
```diff
@@ -1407,7 +1416,7 @@ export default class BattleScene extends SceneBase {
       }
       /**
        * Override battles into single only if not fighting with trainers.
-       * @see {@link https://github.com/pagefaultgames/pokerogue/issues/1948 | GitHub Issue #1948}
+       * @see {@link https://github.com/pagefaultgames/pokerogue/issues/1948 GitHub Issue #1948}
```
Comment (DayKev) [inline src/battle-scene.ts:1419]:
```suggestion
       * @see {@link https://github.com/pagefaultgames/pokerogue/issues/1948 | GitHub Issue #1948}
```
You're supposed to have the `|` if you want to "rename" a `@link[code]` according to the spec.
image
https://tsdoc.org/play/

File: test/testUtils/helpers/overridesHelper.ts [hunk 2]
```diff
@@ -101,8 +103,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the player (pokemon) {@linkcode Species | species}
-   * @param species the (pokemon) {@linkcode Species | species} to set
+   * Override the player (pokemon) {@linkcode Species species}
+   * @param species the (pokemon) {@linkcode Species species} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:107]:
```suggestion
   * Override the player pokemon's {@linkcode Species}
   * @param species - The {@linkcode Species} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 3]
```diff
@@ -158,8 +160,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the player (pokemon) {@linkcode Abilities | ability}.
-   * @param ability the (pokemon) {@linkcode Abilities | ability} to set
+   * Override the player (pokemon) {@linkcode Abilities ability}.
+   * @param ability the (pokemon) {@linkcode Abilities ability} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:164]:
```suggestion
   * Override the player pokemon's {@linkcode Abilities | ability}.
   * @param ability - The {@linkcode Abilities | ability} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 4]
```diff
@@ -169,8 +171,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the player (pokemon) **passive** {@linkcode Abilities | ability}
-   * @param passiveAbility the (pokemon) **passive** {@linkcode Abilities | ability} to set
+   * Override the player (pokemon) **passive** {@linkcode Abilities ability}
+   * @param passiveAbility the (pokemon) **passive** {@linkcode Abilities ability} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:175]:
```suggestion
   * Override the player pokemon's **passive** {@linkcode Abilities | ability}
   * @param passiveAbility - The **passive** {@linkcode Abilities | ability} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 5]
```diff
@@ -194,8 +196,8 @@ export class OverridesHelper extends GameManagerHelper {
     return this;
   }
   /**
-   * Override the player (pokemon) {@linkcode Moves | moves}set
-   * @param moveset the {@linkcode Moves | moves}set to set
+   * Override the player (pokemon) {@linkcode Moves moves}set
+   * @param moveset the {@linkcode Moves moves}set to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:200]:
```suggestion
   * Override the player pokemon's {@linkcode Moves | moveset}
   * @param moveset - The {@linkcode Moves moveset} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 6]
```diff
@@ -209,8 +211,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the player (pokemon) {@linkcode StatusEffect | status-effect}
-   * @param statusEffect the {@linkcode StatusEffect | status-effect} to set
+   * Override the player (pokemon) {@linkcode StatusEffect status-effect}
+   * @param statusEffect the {@linkcode StatusEffect status-effect} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:215]:
```suggestion
   * Override the player pokemon's {@linkcode StatusEffect}
   * @param statusEffect - The {@linkcode StatusEffect} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 7]
```diff
@@ -229,6 +231,19 @@ export class OverridesHelper extends GameManagerHelper {
...
+  /**
+   * Override the trainer chosen when a random trainer is selected.
+   *
+   * Does not force the battle to be a trainer battle.
+   * @see {@linkcode setBattleType}
+   * @returns `this`
+   */
+  public randomTrainer(trainer: RandomTrainerOverride | null): this {
+    vi.spyOn(Overrides, "RANDOM_TRAINER_OVERRIDE", "get").mockReturnValue(trainer);
+    this.log("Partner battle is forced!");
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:243]: This log text seems inaccurate?

File: test/testUtils/helpers/overridesHelper.ts [hunk 8]
```diff
@@ -264,20 +279,36 @@ export class OverridesHelper extends GameManagerHelper {
...
+        : `Battle type set to ${battleType[battleType]} (=${battleType})!`,
+    );
     return this;
   }
 
   /**
-   * Override the enemy (pokemon) {@linkcode Species | species}
-   * @param species the (pokemon) {@linkcode Species | species} to set
+   * Override the enemy (pokemon) {@linkcode Species species}
+   * @param species the (pokemon) {@linkcode Species species} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:311]:
```suggestion
   * Override the enemy pokemon {@linkcode Species}
   * @param species - The pokemon {@linkcode Species} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 9]
```diff
@@ -308,8 +339,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the enemy (pokemon) {@linkcode Abilities | ability}
-   * @param ability the (pokemon) {@linkcode Abilities | ability} to set
+   * Override the enemy (pokemon) {@linkcode Abilities ability}
+   * @param ability the (pokemon) {@linkcode Abilities ability} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:343]:
```suggestion
   * Override the enemy pokemon's {@linkcode Abilities ability}
   * @param ability - The {@linkcode Abilities ability} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 10]
```diff
@@ -319,8 +350,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the enemy (pokemon) **passive** {@linkcode Abilities | ability}
-   * @param passiveAbility the (pokemon) **passive** {@linkcode Abilities | ability} to set
+   * Override the enemy (pokemon) **passive** {@linkcode Abilities ability}
+   * @param passiveAbility the (pokemon) **passive** {@linkcode Abilities ability} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:354]:
```suggestion
   * Override the enemy pokemon's **passive** {@linkcode Abilities ability}
   * @param passiveAbility - The **passive** {@linkcode Abilities ability} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 11]
```diff
@@ -330,7 +361,7 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Forces the status of the enemy (pokemon) **passive** {@linkcode Abilities | ability}
+   * Forces the status of the enemy (pokemon) **passive** {@linkcode Abilities ability}
    * @param hasPassiveAbility forces the passive to be active if `true`, inactive if `false`
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:365]:
```suggestion
   * Forces the status of the enemy pokemon's **passive** {@linkcode Abilities | ability}
   * @param hasPassiveAbility - Forces the passive to be active if `true`, inactive if `false`
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 12]
```diff
@@ -345,8 +376,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the enemy (pokemon) {@linkcode Moves | moves}set
-   * @param moveset the {@linkcode Moves | moves}set to set
+   * Override the enemy (pokemon) {@linkcode Moves moves}set
+   * @param moveset the {@linkcode Moves moves}set to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:380]:
```suggestion
   * Override the enemy pokemon's {@linkcode Moves | moveset}
   * @param moveset the {@linkcode Moves | moveset} to set
```

File: test/testUtils/helpers/overridesHelper.ts [hunk 13]
```diff
@@ -371,8 +402,8 @@ export class OverridesHelper extends GameManagerHelper {
   }
 
   /**
-   * Override the enemy (pokemon) {@linkcode StatusEffect | status-effect}
-   * @param statusEffect the {@linkcode StatusEffect | status-effect} to set
+   * Override the enemy (pokemon) {@linkcode StatusEffect status-effect}
+   * @param statusEffect the {@linkcode StatusEffect status-effect} to set
```
Comment (DayKev) [inline test/testUtils/helpers/overridesHelper.ts:406]:
```suggestion
   * Override the enemy pokemon's {@linkcode StatusEffect}
   * @param statusEffect - The {@linkcode StatusEffect} to set
```

**Review by DayKev — COMMENTED** [review]
It seems like the relevant files are: `battle-scene.ts`, `ability.ts`, `move.ts`, `trainer.ts` and `overrides.ts`, plus the Whirlwind test and `overridesHelper.ts`
So those are the ones I reviewed.

**Review by DayKev — DISMISSED** [review]

**Review by DayKev — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]

**Review by DayKev — APPROVED** [review]

File: src/battle-scene.ts [hunk 14]
```diff
@@ -1383,9 +1392,9 @@ export default class BattleScene extends SceneBase {
...
       if (newBattleType === BattleType.WILD && !this.gameMode.isWaveFinal(newWaveIndex)) {
         newDouble = !randSeedInt(this.getDoubleBattleChance(newWaveIndex, playerField));
-      } else if (newBattleType === BattleType.TRAINER) {
-        newDouble = newTrainer?.variant === TrainerVariant.DOUBLE;
       }
+    } else if (double === undefined && newBattleType === BattleType.TRAINER) {
+      newDouble = newTrainer?.variant === TrainerVariant.DOUBLE;
     } else if (!battleConfig) {
       newDouble = !!double;
     }
```
Comment (DayKev) [inline src/battle-scene.ts:1400]: What was this change made for?

Comment (SirzBenjie) [reply src/battle-scene.ts:1400]: The change was made so that overrides don't have to set wave to 2 in order to to force a trainer battle.
