### PR TITLE
[Bug][Ability] Queenly Majesty flyout during move select

### LINKED ISSUE #6567: [Bug] Queenly majesty showing flyout during select and not the move phase
Bug report initiated by Discord user **sirz_benjie**
### Describe the bug

[Related Discord message](https://discord.com/channels/1125469663833370665/1125894949020381285/1418039238951178311)

Queenly majesty flyout is happening on move select.

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by SirzBenjie**
## What are the changes the user will see?
Queenly Majesty will no longer show its flyout when an affected move is selected.

## Why am I making these changes?
Fixes #6567 
## What are the changes from a developer perspective?
- Pass the `simulated` parameter to the `applyAbAttrs` that checks for `fieldPriorityImmunityAbAttr`
- Invert a condition later on to make biome happy

## Screenshots/Videos
<details><summary>Bugfix</summary>

https://github.com/user-attachments/assets/73a652f1-af56-4891-8076-6ca2aaa0ef2c
</details>

## How to test the changes?
I used these overrides

```ts
const overrides = {
  ENEMY_ABILITY_OVERRIDE: AbilityId.QUEENLY_MAJESTY,
  MOVESET_OVERRIDE: [MoveId.BULLET_PUNCH],
} satisfies Partial<InstanceType<OverridesType>>;
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  - [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes? Ehhh
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - ~~[ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

### CODE REVIEW

**Review by Wlowscha — APPROVED** [review]

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -2426,14 +2426,15 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
 
       if (!cancelledHolder.value) {
         const defendingSidePlayField = this.isPlayer() ? globalScene.getPlayerField() : globalScene.getEnemyField();
-        defendingSidePlayField.forEach(p =>
+        defendingSidePlayField.forEach((p: (typeof defendingSidePlayField)[0]) => {
```
Comment (DayKev) [inline src/field/pokemon.ts:2469]: Huh? Why was the `typeof` needed? Also, couldn't it be `: Pokemon` instead?

**Review by DayKev — APPROVED** [review]

File: src/field/pokemon.ts (hunk 1 above)
Comment (SirzBenjie) [reply src/field/pokemon.ts:2469]: It was yelling at me because it's either a player pokemon or enemy pokemon. idk.

**Review by Madmadness65 — APPROVED** [review]
