### PR TITLE
 [Bug]: Fix #5010: roar and whirlwind missing fail message when against a trainer

### LINKED ISSUE #5010: [Bug] Roar does not Display a Fail Message when No Other Pokémon is Available
### Describe the bug

Neither Roar nor Whirlwind display a fail message when used against a Trainer with one Pokémon left.

### Reproduction

Use Roar after fainting a Pokemon against the static Trainer on wave 5.

### Expected behavior

There should be a "But it Failed" Message

https://replay.pokemonshowdown.com/gen9customgame-2265758327

### Screenshots / Videos

Roar does not display "But it Failed"

https://github.com/user-attachments/assets/07e1a056-aaf2-4f34-b8aa-24b1b91183d5

Whirlwind does not display "But it Failed"

https://github.com/user-attachments/assets/a4161dc4-de81-4082-a4d6-704c8dc2875c

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Suction Cups displays its Immunity Message Correctly

https://github.com/user-attachments/assets/17d2f007-4e57-42bd-b390-f9eb6ca8a8ce

### PR DESCRIPTION
**Pull request by sophiaaa05**
## What are the changes the user will see?
Roar and whirlwind should now display a fail message ("but it failed!"), when used against a trainer with only one pokémon left.

## Why am I making these changes?
To display a fail message when the moves fail, so the player knows what happened.
This Fixes #5010 

## What are the changes from a developer perspective?

To implement the fix, 1 source files was changed, accompanied by the addition of a test on another file. The test is detailed in the corresponding section.

A single condition was added in the file move-effect-phase.ts under the useMove() method to detect when Roar or Whirlwind are used against a trainer who only has one usable Pokémon left. If that’s the case, the move now fails gracefully and shows the failure message.

Specifically, the condition checks:

   If the move is ROAR or WHIRLWIND

   If the battle is against a trainer

   if the trainer’s party has only one Pokémon left that is allowed to participate (i.e., not fainted)

If all these are true, success is set to false, which triggers the fail path of the move logic and displays the expected message: “But it failed!”
This change ensures the move behaves consistently with expected in-game mechanics and gives feedback to the player when the move has no effect.

## Screenshots/Videos

https://github.com/user-attachments/assets/b7bd1346-5bb5-4ad5-9bf4-e23869f43ddd

## How to test the changes?

To test manually and observe the behaviour shown in the video, one can set the overrides to include:

     MOVESET_OVERRIDE: [Moves.ROAR, Moves.WHIRLWIND,Moves.EMBER],
     STARTING_WAVE_OVERRIDE: 5,
     STARTING_LEVEL_OVERRIDE: 50

After that, launch a new save with any two starting pokémons. Beat the first pokémon of the trainer using ember, and then try to use whirlwind or roar against the last pokémon.

There is also a new automated test, kept under whirlwind.test.ts, named should fail when player uses Whirlwind against an opponent with only one available Pokémon.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [ ] If so, please leave a link to it here: 
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

**Review by Madmadness65 — APPROVED** [review]

**Review by SirzBenjie — CHANGES_REQUESTED** [review]
Okay so this is a decent solution, but is hardcoded into the move-phase, which is not desirable. The move phase shouldn't be concerned with the success or failure conditions of the moves it invokes.

See #5644, which fixes fixes said bug related to whirlwind/roar, and would very much like to have this bug fixed.

It's better to invoke the `getCondition` method for these moves to check if the conditions are met.

**Comment by sophiaaa05** [comment]
Ok thank you, I'll try to redo it ASAP. I have my last exam on thursday, but after that i'll start working on it

**Comment by sophiaaa05** [comment]
Hi! I've implemented the requested changes, sorry for the delay. When you have the time, please review it. Thank you, Sophia

**Review by SirzBenjie — DISMISSED** [review]

**Comment by SirzBenjie** [comment]
Sorry for the late review on this. The change are small and focused, and it's a good change. Thank you!

File: src/data/moves/move.ts [hunk 1]
```diff
@@ -6390,8 +6390,23 @@ export class ForceSwitchOutAttr extends MoveEffectAttr {
     return (user, target, move) => {
       const switchOutTarget = (this.selfSwitch ? user : target);
       const player = switchOutTarget instanceof PlayerPokemon;
+      const forceSwitchAttr = move.getAttrs(ForceSwitchOutAttr).find(attr => attr.switchType === SwitchType.FORCE_SWITCH);
 
       if (!this.selfSwitch) {
+        if (move.hitsSubstitute(user, target)) {
```
Comment (DayKev) [inline src/data/moves/move.ts:6396]: It shouldn't be necessary to check for this in move attrs anymore after the move effect phase refactor but just in case I'll leave it in.

File: test/moves/whirlwind.test.ts [hunk 2]
```diff
@@ -161,6 +162,38 @@ describe("Moves - Whirlwind", () => {
...
+    const eligibleEnemy = enemyParty.filter(p => p.hp > 0 && p.isAllowedInBattle());
+    expect(eligibleEnemy.length).toBe(1);
+
+    // Spy on the queueMessage function
+    const queueSpy = vi.spyOn(globalScene, "queueMessage");
+
+    // Player uses Whirlwind; opponent uses Splash
+    game.move.select(Moves.WHIRLWIND);
+    await game.forceEnemyMove(Moves.SPLASH);
+    await game.phaseInterceptor.to("MoveEndPhase", false);
```
Comment (DayKev) [inline test/moves/whirlwind.test.ts:188]:
```suggestion
```

**Review by DayKev — DISMISSED** [review]

**Review by SirzBenjie — APPROVED** [review]

File: src/data/moves/move.ts (hunk 1 above)
Comment (SirzBenjie) [reply src/data/moves/move.ts:6396]: Whirlwind is a bit finnicky, and at times its conditions have been checked in the move phase instead of the MEP. I believe in this case, the defensive programming approach of leaving it in is better.

**Review by DayKev — APPROVED** [review]

**Review by Wlowscha — APPROVED** [review]
