### PR TITLE
[Bug][Ability] Fix change move type abilities

### LINKED ISSUE #4978: [Bug] Tera Blast and Tera Starstorm are Unaffected by Aerilate
### Describe the bug

When used by a Pokémon with the ability Aerilate, Tera Blast and Tera Starstorm will not change their Typings from Normal.

-Every move that is unaffected by -ate seems to extend VariableMoveTypeAttr 
https://github.com/pagefaultgames/pokerogue/blob/f2ef3620b56576c35b5cf478cafef572c943b05c/src/data/move.ts#L4890C40-L4890C59

Link to Discord's Bug Report (Base Tera Blast doesn't work with Pixilate)
https://discord.com/channels/1125469663833370665/1280404498157797448

### Reproduction

Have Tera Blast or Tera Starstorm on a Pokémon with an ability that modifies move Typing.
-ie. Aerilate, Galvanize, Refrigerate, Pixilate

### Expected behavior

BlastStartstormAerilate

> If the user is not Terastallized, Tera Blast will be affected by Abilities such as Galvanize, but if the user Terastallized into a Normal type, Tera Blast will remain Normal.
-Bulba

When not Tera'd Tera Blast and Tera Starstorm should be affected by -Ate Abilities.
(Tera Blast and Tera Starstorm seem to be exceptions to the rule)

### Screenshots / Videos

Aerilate does not make Tera Blast or Tera Starstorm Flying-Type

https://github.com/user-attachments/assets/bec36ce0-80fa-4ba0-a801-6d8be27c7ffd

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Revelation Dance and Terrain Pulse is unaffected by Aerilate, which is correct

> Revelation Dance is unaffected by Normalize, Pixilate, Refrigerate, Aerilate, and Galvanize.

>Terrain Pulse is unaffected by Normalize, Pixilate, Refrigerate, and Galvanize.
-Bulba

https://github.com/user-attachments/assets/11e19023-3af0-4069-acf2-d32483e13e4d

Terrain Pulse and Rev Dance unaffected Aerilate

### LINKED ISSUE #4979: [Bug] Tera Blast is Affected by Normalize while Terastallized
### Describe the bug

Tera Blast is affected by Normalize while Terastallized.
-Tera Starstorm should be affected, based on Showdown. (PLEASE CHECK CART)

### Reproduction
Start with Terapagos, get Normalized after Stellar Terastallizing.

Use Tera Blast with a Pokemon with Normalize while Terastallized

```
import { Type } from "#enums/type";
```
const overrides = {
MOVESET_OVERRIDE: [Moves.TERA_STARSTORM, Moves.TERA_BLAST],
OPP_ABILITY_OVERRIDE: Abilities.NORMALIZE,
OPP_MOVESET_OVERRIDE: [{Moves.ENTRAINMENT}],
STARTING_MODIFIER_OVERRIDE: [{name: "TERA_ORB"}],
ITEM_REWARD_OVERRIDE: [{name: "TERA_SHARD", type: Type.ELECTRIC}, {name: "TERA_SHARD", type: Type.STELLAR}]
};

### Expected behavior

Tera Blast should be unaffected by Normalize while a Pokemon is Terastallized

> If the user is not Terastallized, Tera Blast will be affected by Abilities such as Galvanize, but if the user Terastallized into a Normal type, Tera Blast will remain Normal.
-Bulba

TeraStarstorm Blast Normalize is not the same

### Screenshots / Videos

Tera Blast should be Stellar Type, Tera Starstorm is correct based on Showdown

https://github.com/user-attachments/assets/97d184c4-3209-4d9f-98ec-43595566f8f5

### Session export file

_No response_

### User data export file

_No response_

### Additional context

**The -ates Abilities interaction; -ate Type-Changing Abilities not changing Tera'd Tera Blast, works correctly.**

> If the user is not Terastallized, Tera Blast will be affected by Abilities such as Galvanize, **but if the user Terastallized into a Normal type, Tera Blast will remain Normal.**
-Bulba

https://github.com/user-attachments/assets/b148f043-b198-4a35-85da-c9d4c7f7caa8

BlastStartstormAerilate TeraSteel

### PR DESCRIPTION
**Pull request by SirzBenjie**
## What are the changes the user will see?
Type boost items will now apply their power boosts after considering the type changing effects of a move, rather than its innate power.

Tera blast will no longer be boosted by normalize when the user is terastallized and tera-normal.

Tera blast will now be affected by type changing abilities as long as the user is not terastallized; similarly for tera starstorm as long as the user is not a terastallized terapagos with stellar tera type.

Electromorphosis will now boost the power of moves that have been changed to electric type.

## Why am I making these changes?
Fixes #4979
Fixes, partially, #5510 (does not change the spawn from rewards, only the type boost)
Fixes #4978
## What are the changes from a developer perspective?

Moved the checks for blacklisted moves to the `MoveTypeChangeAbAttr#canApplyPreAttack`.
Made `move#calculateBattlePower`'s invocation of `MoveTypeChangeAbAttr` actually use the holder that returns the changed type. Made the fields which should care about this type change actually care about this type change.

Added a new set of moves, `noAbilityTypeOverrideMove` to `src/moves/invalid-moves.ts` with a list of moves that cannot have their type changed by these abilities.

Added tests for each of the type changing abilities, repurposing the test file for galvanize.

Modified the condition function being used for Pixilate, Galvanize, and Refrigerate to not blacklist moves that have the `VariablePower` attribute, as this attribute is in use by tera blast and tera starstorm, both of which are allowed to be boosted as long as the user is not terastallized.

## Screenshots/Videos
I really can't easily screenshot type boosting items not applying their effects very easily. The automated tests should prove that it works as you would expect.

## How to test the changes?
There's a few changes here, but you can look at the procedures for replication in #4979 and #4978.

For the tera blast interaction, I used:
```ts
const overrides = {
  MOVESET_OVERRIDE: [Moves.TERA_STARSTORM, Moves.TERA_BLAST],
  ABILITY_OVERRIDE: Abilities.NORMALIZE,
  OPP_ABILITY_OVERRIDE: Abilities.BALL_FETCH,
  OPP_HAS_PASSIVE_ABILITY_OVERRIDE: false,
  HAS_PASSIVE_ABILITY_OVERRIDE: false,
  STARTING_MODIFIER_OVERRIDE: [{name: "TERA_ORB"}],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- ~~[ ] Have I provided screenshots/videos of the changes (if applicable)?~~
  - ~~[ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

### CODE REVIEW

**Review by Madmadness65 — DISMISSED** [review]

**Review by Madmadness65 — APPROVED** [review]

File: src/data/abilities/ability.ts [hunk 1]
```diff
@@ -1243,12 +1243,40 @@ export class MoveTypeChangeAbAttr extends PreAttackAbAttr {
...
+   * @param _args - args[0] holds the type that the move is changed to, args[1] holds the multiplier
+   * @returns whether the move type change attribute can be applied
+   */
+  override canApplyPreAttack(pokemon: Pokemon, _passive: boolean, _simulated: boolean, _defender: Pokemon | null, move: Move, _args: [NumberHolder?, NumberHolder?, ...any]): boolean {
+    return ((!this.condition || this.condition(pokemon, _defender, move)) &&
+            !noAbilityTypeOverrideMoves.has(move.id) && 
+            (!pokemon.isTerastallized ||
+              (move.id !== Moves.TERA_BLAST &&
+              (move.id !== Moves.TERA_STARSTORM || pokemon.getTeraType() !== PokemonType.STELLAR || !pokemon.hasSpecies(Species.TERAPAGOS)))))
+            ?? false;
```
Comment (DayKev) [inline src/data/abilities/ability.ts:1268]: Why is this `?? false` needed?

File: src/data/moves/move.ts [hunk 2]
```diff
@@ -798,8 +798,10 @@ export default class Move implements Localizable {
 
     const power = new NumberHolder(this.power);
     const typeChangeMovePowerMultiplier = new NumberHolder(1);
+    const typeChangeHolder = new NumberHolder(this.type);
 
-    applyPreAttackAbAttrs(MoveTypeChangeAbAttr, source, target, this, true, null, typeChangeMovePowerMultiplier);
+    // apply move type changing ability attributes
```
Comment (DayKev) [inline src/data/moves/move.ts:803]:
```suggestion
```

File: test/abilities/normal-move-type-change.test.ts [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+import { allAbilities } from "#app/data/data-lists";
+import { MoveTypeChangeAbAttr } from "#app/data/abilities/ability";
+import { toDmgValue } from "#app/utils/common";
+
+/**
+ * Tests for abilities that change the type of normal moves to
+ * a different type and boost their power
+ *
+ * Includes
+ * - Galvanize
```
Comment (DayKev) [inline test/abilities/normal-move-type-change.test.ts:21]:
```suggestion
 * - Aerialate
 * - Galvanize
```

File: src/data/abilities/ability.ts (hunk 1 above)
Comment (SirzBenjie) [reply src/data/abilities/ability.ts:1268]: Doesn't need to be there. Leftover from the original structure.

**Review by Madmadness65 — DISMISSED** [review]

File: src/field/pokemon.ts [hunk 4]
```diff
@@ -9,7 +9,7 @@ import BattleInfo, {
   PlayerBattleInfo,
   EnemyBattleInfo,
 } from "#app/ui/battle-info";
-import type Move from "#app/data/moves/move";
+import Move from "#app/data/moves/move";
```
Comment (DayKev) [inline src/field/pokemon.ts:12]:
```suggestion
import type Move from "#app/data/moves/move";
```
That's weird, you didn't change anything relating to this import but the `type` got removed.

**Review by DayKev — DISMISSED** [review]

**Review by Madmadness65 — APPROVED** [review]
