### PR TITLE
[P1] Fix crash caused by removing arena tags on a new catch

### LINKED ISSUE #4886: [P1] Crash when replacing a field Pokemon with a catch if Imprison is active
### Describe the bug

After catching a Lampent in a double battle at wave 91 the game freezes when my Gyarados levels up. This does not happen when I defeat the lampent or catch the Gholdengo. Reloading does not help.

In the console the following errors appear:
```
index-yN4aaLV8.js:6492 TypeError: Cannot read properties of undefined (reading 'tags')
    at Zm.removeTag (loading-scene-BeiwXceh.js:836:32601)
    at loading-scene-BeiwXceh.js:283:209160
    at Array.forEach (<anonymous>)
    at OL.onRemove (loading-scene-BeiwXceh.js:283:209146)
    at loading-scene-BeiwXceh.js:839:353631
    at Array.forEach (<anonymous>)
    at MV.lapseTags (loading-scene-BeiwXceh.js:839:353617)
    at YF.start (loading-scene-BeiwXceh.js:821:27340)
    at ZF.shiftPhase (loading-scene-BeiwXceh.js:821:71749)
    at yF.end (loading-scene-BeiwXceh.js:283:180242)
```
```
loading-scene-BeiwXceh.js:836 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tags')
    at Zm.removeTag (loading-scene-BeiwXceh.js:836:32601)
    at loading-scene-BeiwXceh.js:283:209160
    at Array.forEach (<anonymous>)
    at OL.onRemove (loading-scene-BeiwXceh.js:283:209146)
    at loading-scene-BeiwXceh.js:839:353631
    at Array.forEach (<anonymous>)
    at MV.lapseTags (loading-scene-BeiwXceh.js:839:353617)
    at YF.start (loading-scene-BeiwXceh.js:821:27340)
    at ZF.shiftPhase (loading-scene-BeiwXceh.js:821:71749)
    at yF.end (loading-scene-BeiwXceh.js:283:180242)
```

### Reproduction

1.  Defeat Gholdengo with Arcanine's Flamethrower
2. Throw 2 ultra balls at the Lampent 
3. Release Arcanine to add Lampent to the party
4. Wait for the exp to be shared between the party members
5. Game freezes and two errors appear in the console

### Expected behavior

After catching and leveling up continue to the shop

### Screenshots / Videos

image

### Session export file

[sessionData_jopenmolles.txt](https://github.com/user-attachments/files/17787933/sessionData_jopenmolles.txt)

### User data export file

[data_jopenmolles.txt](https://github.com/user-attachments/files/17787938/data_jopenmolles.txt)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MokaStitcher**
## What are the changes the user will see?
No crash when an arena tag is up and a Pokemon is caught and replaces a Pokemon that was on the field

## Why am I making these changes?
Closes #4886 
During the fight Imprison is put up, and at the end of the fight the game tries to clear it by calling `removeTag` on Pokemon on the field.
If one of the party members turns out to be a new catch it doesn't have summonData so the game crashes when attempting to access its tags

## What are the changes from a developer perspective?
- Add null check for summonData in `removeTag` and `lapseTags`, which were the last tag-related functions that didn't have it
- Replaced the check in `lapseTag` for style consistency with all other checks

### Screenshots/Videos
Before:
386878938-b30b4b63-9155-49dc-b43c-64948f61e1bf

After: next wave reached properly
image

## How to test the changes?
Save file [sessionData_jopenmolles.txt](https://github.com/user-attachments/files/17788066/sessionData_jopenmolles.txt)

- Defeat Gholdengo with Arcanine's Flamethrower
- Throw 2 ultra balls at the Lampent
- Replace Arcanine or Steraptor with Lampent
- The game should continue properly

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I considered writing automated tests for the issue?
- [X] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by frutescens — APPROVED** [review]

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -3092,10 +3092,10 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
   }
 
   lapseTag(tagType: BattlerTagType): boolean {
-    const tags = this.summonData?.tags;
-    if (isNullOrUndefined(tags)) {
```
Comment (DayKev) [inline src/field/pokemon.ts:3096]: Shouldn't this one have already worked?

Comment (MokaStitcher) [reply src/field/pokemon.ts:3096]: Yes like I said in th PR I changed it for style consistency with the other ~10 tag functions that just do !summonData. If we don't care I can roll it back (or use isNullOrUndefoned everywhere, I just got lazy on that one tbh)

Comment (DayKev) [reply src/field/pokemon.ts:3096]: Ah, alright then.

**Review by DayKev — APPROVED** [review]
