### PR TITLE
[UI] [Bug] Correctly update level after Weird Dream ME

### LINKED ISSUE #5287: [Bug] "Weird Dream" Reduced Levels do not Change on the Battle Screen when a Pokemon Levels Up
### Describe the bug

After selecting "Leave" and having your Pokemon's levels reduced, the level on the Battle Plates does not update to reflect levels gained after the fact.
-This is fixed by reloading, or by encountering Weird Dream again.
-Stats seem to be changed as normal.

Link to Discord's Bug Report (Level being unsynced after event (Weird Dream))
https://discord.com/channels/1125469663833370665/1316681183446433823

### Reproduction

Leave, then progress and choose a Rare Candy.
```
    STARTING_WAVE_OVERRIDE: 11,
    STARTING_LEVEL_OVERRIDE: 40,
    MYSTERY_ENCOUNTER_RATE_OVERRIDE: 50,
    MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.WEIRD_DREAM,
    ITEM_REWARD_OVERRIDE: [{name: "RARE_CANDY"}],


```

### Expected behavior

Displayed levels should reflect a Pokemon's real level.

### Screenshots / Videos

Using a Rare Candy and levels do not visually update.

https://github.com/user-attachments/assets/6807e448-32ee-40c2-bcc8-bf3410acafc6

Does not get Fixed on recall.

https://github.com/user-attachments/assets/e95df844-ff4b-4831-b700-ef44abdcb922

Not fixed after switching mons

https://github.com/user-attachments/assets/5a68a4d0-efbd-4a5c-a7c6-29fd46fe2b5b

### Session export file

_No response_

### User data export file

_No response_

### Additional context

https://discord.com/channels/1125469663833370665/1289842295751053354
There used to be a bug where levels would not visually **decrease** after selecting "Leave"

### PR DESCRIPTION
**Pull request by fabske0**
## What are the changes the user will see?

After selecting the `leave` option for the Weird Dream ME, the level will be correctly updated on level up.

## Why am I making these changes?

Fixes #5287

## What are the changes from a developer perspective?

Added a check to see if the current level is lower then the saved last level and if so update the last level

## Screenshots/Videos

<details><summary>Video</summary>

https://github.com/user-attachments/assets/4e2b4043-6cde-43ac-bd48-b7339cc2eb00

</details> 

## How to test the changes?

Level up a Pokémon after selecting the `leave` option.

```ts
const overrides = {
  STARTING_WAVE_OVERRIDE: 11,
  STARTING_LEVEL_OVERRIDE: 40,
  MYSTERY_ENCOUNTER_RATE_OVERRIDE: 100,
  MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.WEIRD_DREAM,
  ITEM_REWARD_OVERRIDE: [{ name: "RARE_CANDY" }],
} satisfies Partial<InstanceType<OverridesType>>;
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  - [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

### CODE REVIEW

File: src/ui/battle-info/player-battle-info.ts [hunk 1]
```diff
@@ -207,6 +207,9 @@ export class PlayerBattleInfo extends BattleInfo {
     this.lastLevelCapped = isLevelCapped;
 
     if (this.lastExp !== pokemon.exp || this.lastLevel !== pokemon.level) {
+      if (this.lastLevel > pokemon.level) {
```
Comment (Bertie690) [inline src/ui/battle-info/player-battle-info.ts]: Can we swap this to a `Math.min`?

File: src/ui/battle-info/player-battle-info.ts [hunk 2]
```diff
@@ -207,6 +207,9 @@ export class PlayerBattleInfo extends BattleInfo {
...
+        this.lastLevel = pokemon.level;
+      }
```
Comment (DayKev) [inline src/ui/battle-info/player-battle-info.ts]:
```suggestion
      this.lastLevel = Math.min(this.lastLevel, pokemon.level);
```
I assume he means this?
