### PR TITLE
[BUG] Fix quick claw being blocked by Psychic terrain

### LINKED ISSUE #6675: [Bug] Quick Claw being blocked by Psychic Terrain
Bug report initiated by Discord user **kazapple_**
### Describe the bug

[Related Discord message](https://discord.com/channels/1125469663833370665/1430220810676867102/1430220810676867102)

As title states, all moves affected by quick claw are being blocked by psychic terrain, as if they’ve been given actual priority.

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by fabske0**
## What are the changes the user will see?

Non priority moves that are boosted by quick claw will no longer be blocked by psychic terrain

## Why am I making these changes?

Fixes #6675

## What are the changes from a developer perspective?

The check for increased priority in `Terrain#isMoveTerrainCancelled` is now `> 0.2` instead of `> 0` to account for the fractional priority used by Quick Claw and similar effects.

## Screenshots/Videos

https://github.com/user-attachments/assets/910729d5-d4e1-47cc-92e7-2dcb8c1b5b41

## How to test the changes?

I used these overrides:

```ts
const overrides = {
  STARTING_HELD_ITEMS_OVERRIDE: [{
    name: "QUICK_CLAW",
    count: 10
  }],
  ENEMY_LEVEL_OVERRIDE: 1000,
  ENEMY_MOVESET_OVERRIDE: MoveId.PSYCHIC_TERRAIN,
  STARTING_LEVEL_OVERRIDE: 500,
  MOVESET_OVERRIDE: [MoveId.QUICK_ATTACK, MoveId.POUND]
} satisfies Partial<InstanceType<OverridesType>>;
```

Just use moves and make sure they behave correct under psychic terrain/ with quick claw

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  - [x] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?

### CODE REVIEW

File: src/data/terrain.ts [hunk 1]
```diff
@@ -68,8 +69,9 @@ export class Terrain {
         return (
           // ... is neither spread nor field-targeted,
           !isFieldTargeted(move)
-          && !isSpreadMove(move) // .. has positive final priority,
-          && move.getPriority(user) > 0 // ...and is targeting at least 1 grounded opponent
+          && !isSpreadMove(move) // .. has positive final priority, but not just has the boost from Quick Claw,
+          && move.getPriority(user) > 0
+          && !(user.getTag(BattlerTagType.BYPASS_SPEED) && move.getPriority(user) === 0.2) // ...and is targeting at least 1 grounded opponent
           && user.getOpponents(true).some(o => targets.includes(o.getBattlerIndex()) && o.isGrounded())
```
Comment (Bertie690) [inline src/data/terrain.ts]:
```suggestion
          && !isSpreadMove(move) 
          // .. has positive final priority, excluding Quick Claw boost
          && move.getPriority(user) >= 0.2
          // ...and is targeting at least 1 grounded opponent
          && user.getOpponents(true).some(o => targets.includes(o.getBattlerIndex()) && o.isGrounded())
```

this calls get priority twice

File: test/arena/psychic-terrain.test.ts [hunk 2]
```diff
@@ -56,4 +56,30 @@ describe("Arena - Psychic Terrain", () => {
 
     expect(game.scene.arena.weather?.weatherType).toBe(WeatherType.RAIN);
   });
+
+  it("Quick claw boosted move is not blocked", async () => {
```
Comment (Bertie690) [inline test/arena/psychic-terrain.test.ts]:
```suggestion
  it("should not block non-priority moves boosted by Quick Claw", async () => {
```

File: test/arena/psychic-terrain.test.ts [hunk 3]
```diff
@@ -56,4 +56,30 @@ describe("Arena - Psychic Terrain", () => {
...
+    await game.classicMode.startBattle([SpeciesId.MAGIKARP]);
+
+    game.move.select(MoveId.PSYCHIC_TERRAIN);
+    await game.toNextTurn();
+
+    game.move.use(MoveId.POUND);
+    await game.toEndOfTurn();
+
+    expect(game.field.getEnemyPokemon().hp).toBeLessThan(game.field.getEnemyPokemon().getMaxHp());
+  });
```
Comment (Bertie690) [inline test/arena/psychic-terrain.test.ts]:
```suggestion
    await game.classicMode.startBattle([SpeciesId.FEEBAS]);
    
    game.move.use(MoveId.PSYCHIC_TERRAIN);
    await game.toNextTurn();

    expect(game).toHaveTerrain(TerrainType.PSYCHIC);
    const feebas = game.field.getPlayerPokemon();
    expect(allMoves[MoveId.POUND].getPriority(feebas)).toBe(0.2);

    game.move.use(MoveId.POUND);
    await game.toEndOfTurn();

    const shuckle = game.field.getEnemyPokemon();
    expect(shuckle).not.toHaveFullHp();
  });
```

don't forget to add some imports

File: test/arena/psychic-terrain.test.ts [hunk 4]
```diff
@@ -56,4 +56,30 @@ describe("Arena - Psychic Terrain", () => {
...
+    await game.classicMode.startBattle([SpeciesId.MAGIKARP]);
+
+    game.move.select(MoveId.PSYCHIC_TERRAIN);
+    await game.toNextTurn();
+
+    game.move.use(MoveId.QUICK_ATTACK);
+    await game.toEndOfTurn();
+
+    expect(game.field.getEnemyPokemon().hp).toHaveFullHp;
+  });
```
Comment (Bertie690) [inline test/arena/psychic-terrain.test.ts]:
```suggestion
  it("should block priority moves boosted by Quick Claw", async () => {
    await game.classicMode.startBattle([SpeciesId.FEEBAS]);
    
    game.move.use(MoveId.PSYCHIC_TERRAIN);
    await game.toNextTurn();

    expect(game).toHaveTerrain(TerrainType.PSYCHIC);
    const feebas = game.field.getPlayerPokemon();
    expect(allMoves[MoveId.QUICK_ATTACK].getPriority(feebas)).toBe(1.2);

    game.move.use(MoveId.QUICK_ATTACK);
    await game.toEndOfTurn();

    const shuckle = game.field.getEnemyPokemon();
    expect(shuckle).toHaveFullHp();
  });
```

**Review by Bertie690 — CHANGES_REQUESTED** [review]

File: test/arena/psychic-terrain.test.ts (hunk 3 above)
Comment (fabske0) [reply test/arena/psychic-terrain.test.ts]: This check doesn't work, since when calling `getPriority()` directly on the move, the mon doesn't have the battlertag.
The items aren't applied, so the prio doesn't get the +0.2

Comment (fabske0) [reply test/arena/psychic-terrain.test.ts]: I could manually add the tag before the check and remove it after.

Comment (DayKev) [reply test/arena/psychic-terrain.test.ts]: Fixed the suggestions and applied them.

**Review by DayKev — DISMISSED** [review]

**Review by Bertie690 — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
