### PR TITLE
[Bug] Fix reloads erasing weather on first wave of biome

### LINKED ISSUE #3877: [Bug] Biome Weather Disappears When Reloading on the First Wave of a Biome
### Describe the bug

Link to Discord with Videos
https://discord.com/channels/1125469663833370665/1278472685541916734

On waves that end in 1, and 6 in endless, and waves that end in 1 on classic, biome weather can be stopped by save and exiting or reloading a session

-Rain, Hail, Snow, Sandstorm, 

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

Biome Weather should not be lost when reloading a session on the first wave of a new biome

### Screenshots / Videos

_No response_

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

Might be similar to https://github.com/pagefaultgames/pokerogue/issues/1005 (Bug: Summoning abilities don't activate when reloading a session)

### PR DESCRIPTION
**Pull request by PigeonBar**
## What are the changes the user will see?

Reloading on the first wave of a new biome should no longer cause weather to disappear.

## Why am I making these changes?

Fixes #3877. This is also relevant to Daily Run Guides, which currently reload on the first wave of every new biome. 

## What are the changes from a developer perspective?

When entering a new biome, the game now generates the biome's weather before saving the session, which ensures that the weather gets saved correctly.
Also, `reloadHelper.ts` was updated to correctly use session data from the exact time session data gets saved, instead of the time when `reloadHelper` gets called.

### Before the changes

https://github.com/user-attachments/assets/376bedb0-9011-4f2c-99cd-376aae02c8c7

After reloading, the weather is no longer Sunny, and Paras does not take damage from Dry Skin.

### After the changes

https://github.com/user-attachments/assets/b4a2b45d-ac3c-4868-89b7-4f4a73520109

After reloading, the weather remains Sunny, and Paras takes damage from Dry Skin.

## How to test the changes?

1. Enter a new biome that has weather. Take note of the type of weather.
2. Reload the session on the first wave of that biome.
3. Check that the weather is the same as before the reload.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- ~~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

File: src/phases/encounter-phase.ts [hunk 1]
```diff
@@ -154,6 +154,7 @@ export class EncounterPhase extends BattlePhase {
 
       this.scene.ui.setMode(Mode.MESSAGE).then(() => {
         if (!this.loaded) {
+          this.trySetWeatherIfNewBiome(); // Set weather before session gets saved
           //@ts-ignore
           this.scene.gameData.saveAll(this.scene, true, battle.waveIndex % 10 === 1 || this.scene.lastSavePlayTime >= 300).then(success => { // TODO: get rid of ts-ignore
```
Comment (DayKev) [inline src/phases/encounter-phase.ts:159]:
```suggestion
          this.scene.gameData.saveAll(this.scene, true, battle.waveIndex % 10 === 1 || (this.scene.lastSavePlayTime ?? 0) >= 300).then(success => {
```
Can you fix this while you're here?

File: src/test/battle/battle.test.ts [hunk 2]
```diff
@@ -291,7 +292,8 @@ describe("Test Battle Phase", () => {
     expect(game.scene.currentBattle.turn).toBeGreaterThan(turn);
   }, 20000);
 
-  it("to next wave with pokemon killed, single", async () => {
+  // Made redundant by the "same biome" test, which is copied from this test, should this be removed?
```
Comment (DayKev) [inline src/test/battle/battle.test.ts:295]: Yeah since the new test is the exact same as the old test, just with an extra `expect()`, you can remove the old test.

File: src/test/reload.test.ts [hunk 3]
```diff
@@ -36,32 +36,35 @@ describe("Reload", () => {
...
       .battleType("single")
-      .startingLevel(100)
-      .enemyLevel(1000)
+      .startingLevel(100) // Avoid levelling up
+      .enemyLevel(1000) // Avoid opponent dying before game.doKillOpponents()
       .disableTrainerWaves()
       .moveset([Moves.KOWTOW_CLEAVE])
       .enemyMoveset(SPLASH_ONLY);
-    await game.dailyMode.startBattle();
+    await game.classicMode.startBattle(); // Apparently daily mode would override the biome
```
Comment (DayKev) [inline src/test/reload.test.ts:49]: I think this test was specifically testing for daily mode, so I don't think you should swap it to classic mode. For now you'll have to write a new test (or find another test that's closer to what you're testing to add on to).

**Review by DayKev — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
