### PR TITLE
[Bug] Fix Aura Break applying without Dark/Fairy Aura present

### LINKED ISSUE #4050: [Bug] Aura Break Applies the Damage Multiplier to the User's Dark and Fairy Moves, even without Fairy or Dark Aura Present.
### Describe the bug

Aura Break weakens Dark and Fairy type moves on the Ability's side, even without Fairy Aura or Dark Aura present.
-The opposing pokemon do not have their fairy or dark moves' power reduced.

Link to Discord's Bug report (Zygarde huge power not working)
https://discord.com/channels/1125469663833370665/1281151076262875136

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

Aura break should not lower the Ability bearer's side's dark and fairy type moves. 

### Screenshots / Videos

Aura Break lowers the power of the Aura Breaker's Fairy moves

https://github.com/user-attachments/assets/e37cfbbb-e059-4f38-8363-f80e6ffe2973

Aura Break weakens the power of the Aura Breaker's Fairy type moves

Uploading PokéRogue 2024-09-05 08-38-21.mp4…

Aura Break weakens the power of an ally's Dark type moves

https://github.com/user-attachments/assets/671503c0-6802-44e3-9ad4-786917523838

 Aura Break does not lower the power of the opposing side's moves.

https://github.com/user-attachments/assets/ad8f74dc-840d-4fc4-b1fe-be929b6a21e9

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

Aura Break reduces the power of the Aura Breaker's fairy moves when Fairy Aura is on the field (correct)

https://github.com/user-attachments/assets/1f39cf33-3bd4-4c08-8eb3-c395aeac277d

https://replay.pokemonshowdown.com/gen9customgame-2195170181-rjooupp7phd8j3ymleznzchcxyagktepw

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?
This fixes a bug where Aura Break would apply its power debuff despite Dark and/or Fairy Aura not being present on the field

## Why am I making these changes?
closes #4050 

## What are the changes from a developer perspective?

- `data/ability`: Changed Aura Break's condition (in its `conditionalAttr`s) to check all active Pokemon on the field for Dark/Fairy Aura instead of a single "target" Pokemon (or, really, just Aura Break's source under a misnamed arg).
- `data/move`: Changed `Move#calculateBattlePower` so that field aura attributes that don't satisfy their conditions from `getCondition()` are filtered out before applying.
- `test/abilities/aura_break.test`: New test covering the case where neither Dark Aura nor Fairy Aura are present.

## How to test the changes?
`npm run test aura_break`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [?] Are the changes visual?
  - [?] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by torranx — APPROVED** [review]
coolio

File: src/data/ability.ts [hunk 1]
```diff
@@ -5333,8 +5333,8 @@ export function initAbilities() {
       .attr(FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 4 / 3),
     new Ability(Abilities.AURA_BREAK, 6)
       .ignorable()
-      .conditionalAttr(target => target.hasAbility(Abilities.DARK_AURA), FieldMoveTypePowerBoostAbAttr, Type.DARK, 9 / 16)
-      .conditionalAttr(target => target.hasAbility(Abilities.FAIRY_AURA), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 9 / 16),
+      .conditionalAttr(pokemon => pokemon.scene.getField(true).some(p => p.hasAbility(Abilities.DARK_AURA)), FieldMoveTypePowerBoostAbAttr, Type.DARK, 9 / 16)
+      .conditionalAttr(pokemon => pokemon.scene.getField(true).some(p => p.hasAbility(Abilities.FAIRY_AURA)), FieldMoveTypePowerBoostAbAttr, Type.FAIRY, 9 / 16),
```
Comment (flx-sta) [inline src/data/ability.ts:5337]: Does this resolve in a `AND` or in a `OR` connection of conditions?

File: src/data/move.ts [hunk 2]
```diff
@@ -757,7 +757,10 @@ export default class Move implements Localizable {
 
     const fieldAuras = new Set(
       source.scene.getField(true)
-        .map((p) => p.getAbilityAttrs(FieldMoveTypePowerBoostAbAttr) as FieldMoveTypePowerBoostAbAttr[])
+        .map((p) => p.getAbilityAttrs(FieldMoveTypePowerBoostAbAttr).filter(attr => {
+          const condition = attr.getCondition();
+          return (!condition || condition(p));
```
Comment (flx-sta) [inline src/data/move.ts:762]: what!? I'm a bit confused what this does

File: src/data/ability.ts (hunk 1 above)
Comment (innerthunder) [reply src/data/ability.ts:5337]: `some` is an `OR` connection/reduction

**Comment by flx-sta** [comment]
# Fairy Aura (Player)

## No Break (Enemy)

https://github.com/user-attachments/assets/164ca89e-5ea6-47d8-ae25-fae64a9c2112

## Aura Break (Enemy)

https://github.com/user-attachments/assets/afecb35c-41cf-4b85-a86d-c6b6be1e856f

---

# Dark Aura

## No Break (Enemy)

https://github.com/user-attachments/assets/e981982b-db61-4518-985f-f7081b63565e

## Aura Break (Enemy)

https://github.com/user-attachments/assets/b836d5af-6dc3-4d86-a6b6-29e2d2d41147

File: src/data/move.ts (hunk 2 above)
Comment (innerthunder) [reply src/data/move.ts:762]: This gets all "aura" ability attributes from the Pokemon on the field and checks their condition from `getCondition`. Then it filters out any ability that has a condition that isn't met.

Maybe a clearer way to put this would be:
```suggestion
          return (condition === null || condition(p));
```

**Review by flx-sta — CHANGES_REQUESTED** [review]
There should be a message if the aura is broken
image
https://youtu.be/aT3eNBkSElY?t=10

**Comment by innerthunder** [comment]
Just added a post-summon message. It should only trigger if there is a Pokemon with Dark/Fairy Aura on the field

**Review by flx-sta — APPROVED** [review]
lgtm

https://github.com/user-attachments/assets/0ac61f6f-4d12-4feb-9f34-245b16d05622

**Review by Tempo-anon — APPROVED** [review]

**Review by frutescens — APPROVED** [review]

**Review by f-fsantos — APPROVED** [review]
