### PR TITLE
[Bug] Fix battle-anims crashing in certain cases

### LINKED ISSUE #5122: [Bug] Certain Partial Trapping Moves (Whirlpool, Sand Tomb) Crash when the User and Opponent Faints at the Same Time
### Describe the bug

When Animations are set to ON, and a damaging trapping move faints a Pokemon at the same time as the trappee to end-of-turn damage the game crashes.

- Whirlpool, Fire Spin, and Sand Tomb, crash the game while Infestation and Snap Trap does not.
- Replacing the animation for Sand Tomb for Infestation's in `battler-tags.ts` does not result in a Crash when Sand Tomb is used.
- Turning Move Animations OFF prevents a crash from occurring.
-Does not require Salt Cure, Leech Seed/Sappy Seed and cannot crash from taking Future Sight damage.

Link to Discord's Bug Report (Game crash on end-of-turn damage?)
https://discord.com/channels/1125469663833370665/1328079300112678954

### Reproduction

**Move Animations ON**

Choose a Starter weak to the Opposing Trapping move. Use Salt Cure.
-Using Infestation or Snap Trap does not Crash.

Modify OPP_HELD_ITEMS_OVERRIDE: type: Type.    to the type of the move used in OPP_MOVESET_OVERRIDE
```
	MOVESET_OVERRIDE: [Moves.SALT_CURE],
	ABILITY_OVERRIDE: Abilities.STURDY,

	OPP_LEVEL_OVERRIDE: 5,
	OPP_SPECIES_OVERRIDE: Species.FLETCHINDER,
	OPP_MOVESET_OVERRIDE: [Moves.FIRE_SPIN],
	OPP_IVS_OVERRIDE: [0, 31, 0, 31, 0, 0],
	OPP_ABILITY_OVERRIDE: Abilities.STURDY,

	STARTING_HELD_ITEMS_OVERRIDE: [{name: "ATTACK_TYPE_BOOSTER", type: Type.ROCK, count: 50}],
	OPP_HELD_ITEMS_OVERRIDE: [{name: "ATTACK_TYPE_BOOSTER", type: Type.FIRE, count: 50}],
```

Try replacing
```
super(BattlerTagType.FIRE_SPIN, CommonAnim.FIRE_SPIN, turnCount, Moves.FIRE_SPIN, sourceId);
```
With
```
super(BattlerTagType.FIRE_SPIN, CommonAnim.INFESTATION, turnCount, Moves.FIRE_SPIN, sourceId);
```

### Expected behavior

The game shouldn't crash when Pokemon faint to secondary damage while the Opponent faints to Partial Trapping. or vise-versa. Specifically Fire Spin, Sand Tomb, and Whirlpool. (There are probably others, and other exceptions.)

In addition, Pokemon should not take turn-end damage related to partial-trapping if the Trappee faints before them from turn-end damage due to having a higher Speed stat.

-Pokemon should also take turn-end damage in order of their Speed, with Leech Seed and Salt Cure going before Trapping Damage. Rather than it always starting with the Player's.
https://replay.pokemonshowdown.com/gen9customgame-2281249171

### Screenshots / Videos

Screenshot (543)

<details><summary>
Player and Opponent's side
</summary>
(Enemy Trapping Move, Player Chip Damage)

https://github.com/user-attachments/assets/d197d6ca-d979-48ee-8d16-d45b57c3edf5

Player Trapping Move (Whirlpool), Enemy Chip Damage. (Leech only works if the Enemy used it)

https://github.com/user-attachments/assets/f6a4a173-5868-4e01-92a2-c6db024cca53

</details>

<details><summary>
Player Salt Cure and Enemy Salt Cure does not Crash
</summary>

https://github.com/user-attachments/assets/2582f41f-e1d4-4016-96d1-709cefc05542

</details>

<details><summary>
Certain Moves Crash
</summary>
Player's Salt Cure and Enemy's Sand Tomb Crashes

https://github.com/user-attachments/assets/259a68e5-6768-4fea-8d09-67314709f86c

Player's Salt Cure and Enemy's Fire Spin Crashes

https://github.com/user-attachments/assets/f27250ef-3590-4c91-90a5-6e20850c6ef2

Player's Salt Cure and Enemy's Infestation does not Crash

https://github.com/user-attachments/assets/ec2032b7-bf76-4a31-9c55-82a87f40ab4b

Player's Salt Cure and Enemy's Snap Trap does not Crash

https://github.com/user-attachments/assets/3fb6aeda-e28c-4a83-a7e5-780be5170e09

</details>
<details><summary>
Move Animation OFF Fire Spin does not Crash
</summary>

Player Salt Cure Enemy Fire Spin Anims OFF

https://github.com/user-attachments/assets/f8c77c91-b4a7-40d8-91c1-8671ff6232cd

</details>

### Session export file

_No response_

### User data export file

_No response_

### Additional context

When a Faster Pokemon faints from Salt Cure, and the other Pokemon is bound by a Partial Trapping Move, the Partial Trapping effect should wear off the MOMENT the Pokemon (Trappee) faints, even if by passive damage (Salt Cure)

https://replay.pokemonshowdown.com/gen9customgame-2280390566

https://github.com/user-attachments/assets/b91506d3-f00d-406d-b8a7-2770230c2fed

Caterpie is 9 speed, Fletchling is 12

https://github.com/user-attachments/assets/694f8454-37c4-4589-bf34-53ec4708e16f

### PR DESCRIPTION
**Pull request by SirzBenjie**
## What are the changes the user will see?
The game will not crash when an animation is trying to be placed above or below a pokemon that is considered to not be "active".
In other words, the game will not crash when 

## Why am I making these changes?
Fixes #5122 and also a hell of a lot of other latent bugs where animations can trigger on pokemon that the `isActive` method returns `false` for.
Also, fixing a P1 bug is high priority.

## What are the changes from a developer perspective?
The `setSpritePriority` submethod within `src/data/battle-anims.ts`'s `BattleAnim.play` has been refactored and fixed.
The cause of the bug was due to `gameScene.field.moveBelow()` possibly being called with an undefined value. It may have also possible for it to be called with a value that did not exist in the `gameScene.field` container.
In either case, that method has now been rewritten to be substantially shorter (~20 lines WITH comments compared to ~40 beforehand, which didn't even have comments).

Unfortunately, I am not able to get a regression test for this bugfix. While I did write one, triggering the bug *requires* playing the animations, which aren't able to be done with the current testing infrastructure. Alas, this bugfix PR will have to go in without a regression test.

I also made some minor changes to the `battle-scene.ts` file while I was editing it. Formatted long import lines, and also moved two calculations that were being done inside loops that could be done outside of them.
## Screenshots/Videos

<details><summary>Before Fix</summary>

https://private-user-images.githubusercontent.com/176693244/402643852-f27250ef-3590-4c91-90a5-6e20850c6ef2.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk2MzI0NDgsIm5iZiI6MTczOTYzMjE0OCwicGF0aCI6Ii8xNzY2OTMyNDQvNDAyNjQzODUyLWYyNzI1MGVmLTM1OTAtNGM5MS05MGE1LTZlMjA4NTBjNmVmMi5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxNVQxNTA5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTI1NzQ0NTY2NzY1YzY0OWQ1ZDEyOWMzODBmYzVjYjY1ZGY5ZWE3Y2JjYjk0ODc0YzFkZjYzMjRjYjBhZjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U4lWu_mJlYvTAUWCBwN2DE00Cq0O8AF3th3ds79zOTE
</details>

<details><summary>Post Fix</summary>

https://github.com/user-attachments/assets/0e4600b4-5e4d-4381-a1d1-59630dff5991
</details>

## How to test the changes?

#5122 goes into much better detail about this, but for convenience, here's the overrides you can use:

```ts
const overrides = {
  MOVESET_OVERRIDE: [ Moves.SALT_CURE ],
  ABILITY_OVERRIDE: Abilities.STURDY,

  OPP_LEVEL_OVERRIDE: 5,
  OPP_SPECIES_OVERRIDE: Species.FLETCHINDER,
  OPP_MOVESET_OVERRIDE: [ Moves.FIRE_SPIN ],
  OPP_IVS_OVERRIDE: [ 0, 31, 0, 31, 0, 0 ],
  OPP_ABILITY_OVERRIDE: Abilities.STURDY,

  STARTING_HELD_ITEMS_OVERRIDE: [{ name: "ATTACK_TYPE_BOOSTER", type: Type.ROCK, count: 50 }],
  OPP_HELD_ITEMS_OVERRIDE: [{ name: "ATTACK_TYPE_BOOSTER", type: Type.FIRE, count: 50 }],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes? _Not doable w/ current testing infra_
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - ~~[ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

~~Are there any localization additions or changes? If so:~~
- ~~[ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?~~
  - ~~[ ] If so, please leave a link to it here:~~
- ~~[ ] Has the translation team been contacted for proofreading/translation?~~

## Additional Notes

Watching the fix video reveals another visual bug. Animations triggered during the MoveEndPhase are not played in the proper order. That is, the salt cure animation should not be played while bulbasaur is still on the field. That issue, however, is not related to this fix, and is outside the scope of this PR.

### CODE REVIEW

**Review by Madmadness65 — APPROVED** [review]

File: src/data/battle-anims.ts [hunk 1]
```diff
@@ -993,47 +1006,39 @@ export abstract class BattleAnim {
...
+                    moveFunc = priority === 2 ? globalScene.field.moveBelow : globalScene.field.moveAbove;
+                    if (frame.focus === AnimFocus.USER) {
+                      targetSprite = this.user;
+                    } else if (frame.focus === AnimFocus.TARGET) {
+                      targetSprite = this.target;
+                    }
                   }
+                  // If target sprite is not undefined and exists in the field container, then move the sprite using the moveFunc.
+                  // Otherwise, default to just bringing it to the top.
+                  targetSprite && globalScene.field.exists(targetSprite) ? moveFunc.bind(globalScene.field)(moveSprite as Phaser.GameObjects.GameObject, targetSprite) : globalScene.field.bringToTop(moveSprite as Phaser.GameObjects.GameObject);
```
Comment (DayKev) [inline src/data/battle-anims.ts:1041]: I'd prefer this to be an `if`/`else`, it's a bit too long of a line to be a ternary.

File: src/data/battle-anims.ts [hunk 2]
```diff
@@ -993,47 +1006,39 @@ export abstract class BattleAnim {
               const moveSprite = sprites[graphicIndex];
               if (spritePriorities[graphicIndex] !== frame.priority) {
                 spritePriorities[graphicIndex] = frame.priority;
+                /** Move the position that the moveSprite is rendered in based on the priority.
+                 * @param priority The priority level to draw the sprite.
+                 * - 0: Draw the sprite in front of the pokemon on the field.
+                 * - 1: Draw the sprite in front of the user pokemon.
```
Comment (DayKev) [inline src/data/battle-anims.ts:1012]: Is `priority === 1` made into the "default" case?

File: src/data/battle-anims.ts [hunk 3]
```diff
@@ -993,47 +1006,39 @@ export abstract class BattleAnim {
...
-                      setSpritePriority(1);
+                  /** The sprite we are moving the moveSprite in relation to */
+                  let targetSprite: Phaser.GameObjects.GameObject | nil;
+                  /** The method that is being used to move the sprite.*/
+                  let moveFunc: ((sprite: Phaser.GameObjects.GameObject, target: Phaser.GameObjects.GameObject) => void) |
+                              ((sprite: Phaser.GameObjects.GameObject) => void) = globalScene.field.bringToTop;
+
+                  if (priority === 0) { // Place the sprite in front of the pokemon on the field.
+                    targetSprite = globalScene.getEnemyField().find(p => p) ?? globalScene.getPlayerField().find(p => p);
+                    console.log(typeof targetSprite);
```
[the remark this answers is not in the document]
Comment (SirzBenjie) [reply src/data/battle-anims.ts:1026]: Nope that's remnant, thanks for pointing it out.

File: src/data/battle-anims.ts (hunk 2 above)
Comment (SirzBenjie) [reply src/data/battle-anims.ts:1012]: Yeah, that's what it was before.

File: src/data/battle-anims.ts (hunk 1 above)
Comment (SirzBenjie) [reply src/data/battle-anims.ts:1041]: Sorry, I am a [never nester](https://medium.com/@MBCube/i-am-a-never-nester-8c88baf7a218) and old habits die hard.
Will fix.

**Review by Unicornpowerstar — APPROVED** [review]

**Review by Unicornpowerstar — APPROVED** [review]
