### PR TITLE
[Bug] Fix for Roost Grounds the User Rather than Removing Flying Typing#3984 

### LINKED ISSUE #3984: [Bug] Roost Grounds the User Rather than Removing Flying Typing
### Describe the bug

Roost grounds the user, allowing it to be hit by ground type moves. However, it also retains the flying type, making it take Super effective damage from moves Flying type would be weak to.

Link to Discord Bug Report (Roost is not removing flying type)
https://discord.com/channels/1125469663833370665/1280071569204318261
-Videos

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

> If a Flying-type Pokémon successfully uses Roost, it will now [lose](https://bulbapedia.bulbagarden.net/wiki/Type_change) its Flying type until the end of the turn
-Bulba

### Screenshots / Videos

Rotom-Fan has Levitate and Roost, is hit by Earth Power

https://github.com/user-attachments/assets/286215e3-9d89-40ea-a8cb-a1b9e0636646

-Using Roost, Levitate is lost, and Rotom-Fan is hit by Earth Power

Aerodactyl uses Roost and is hit Supereffectively by Shock Wave

https://github.com/user-attachments/assets/712f207d-e8b1-499e-8a26-0c32cc748c57

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

This seems to have started happening after the update, possibly caused by #3670 , where a bug regarding gravity was fixed.

### PR DESCRIPTION
**Pull request by PrabbyDD**
## What are the changes the user will see?
Roost will now work as listed on bulbapedia for the cases listed in the bug report and more. This includes:
Roost correctly removing flying for a turn instead of immediately grounding a pokemon. 
Roost will only ground a pokemon if it was ungrounded solely due to being flying type
Roost on a pure flying type will change it to normal until end of turn.
Roost on a dual type will change it to the non flying type until end of turn
Roost on a pokemon that has used burn up will make it typeless until end of turn, then revert to flying
Roost on a pokemon afflicted with trick or treat/forests curse will change types faithfully to the base game
Roost on a non flying type pokemon will not change its type. 

## Why am I making these changes?
Closes #3984 
bugfix

## What are the changes from a developer perspective?
Added new tag for roost called RoostedTag, added BurnUpTag, added test cases in roost.test.ts, filled out 
BattleTag class for RoostedTag. 

### Screenshots/Videos

https://github.com/user-attachments/assets/94da4050-2d92-4c1e-9bb9-999757114d16

https://github.com/user-attachments/assets/3ad8eb42-cc9b-4cba-99fd-66c255c06090

https://github.com/user-attachments/assets/732ce9fa-4a83-476d-a118-45efd05c0576

https://github.com/user-attachments/assets/b57546fa-0a66-4d58-a815-5f25f4a7aa0c

https://github.com/user-attachments/assets/9d8a96b1-a896-4c78-9d8a-12e4d1395969

## How to test the changes?
You can run the roost.test.ts file using npm test roost
You can also change the override file to any roost related test cases you wish. 

## Checklist
- [X ] **I'm using `beta` as my base branch**
- [X ] There is no overlap with another PR?
- [X ] The PR is self-contained and cannot be split into smaller PRs?
- [X ] Have I provided a clear explanation of the changes?
- [X ] Have I considered writing automated tests for the issue?
- [ X] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [X ] Have I tested the changes (manually)?
    - [X ] Are all unit tests still passing? (`npm run test`)
- [X ] Are the changes visual?
  - [X ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by PrabbyDD** [comment]
Am fixing merge conflicts and checking if tests still pass (including the one i added)...

**Comment by PrabbyDD** [comment]
Some issues i suppose. Will try and fix tomorrow

File: src/data/battler-tags.ts [hunk 1]
```diff
@@ -2244,7 +2318,9 @@ export function getBattlerTag(tagType: BattlerTagType, turnCount: number, source
   case BattlerTagType.IGNORE_FLYING:
     return new GroundedTag(tagType, BattlerTagLapseType.CUSTOM, sourceMove);
   case BattlerTagType.ROOSTED:
-    return new GroundedTag(tagType, BattlerTagLapseType.TURN_END, sourceMove);
+    return new RoostedTag(tagType, BattlerTagLapseType.TURN_END, sourceMove);
+  case BattlerTagType.BURNED_UP:
+    return new BurnedUpTag(tagType, BattlerTagLapseType.CUSTOM, sourceMove);
```
Comment (innerthunder) [inline src/data/battler-tags.ts:2323]:
```suggestion
    return new RoostedTag();
  case BattlerTagType.BURNED_UP:
    return new BurnedUpTag();
```
To go along with other suggestions...

Also, doesn't Double Shock also need a tag in this vein?

File: src/test/moves/roost.test.ts [hunk 2]
```diff
@@ -27,33 +27,205 @@ describe("Moves - Roost", () => {
...
     game.override.battleType("single");
-    game.override.enemySpecies(Species.STARAPTOR);
-    game.override.enemyAbility(Abilities.INSOMNIA);
+    game.override.enemySpecies(Species.RELICANTH);
     game.override.startingLevel(100);
-    game.override.enemyLevel(100);
-    game.override.moveset([Moves.STOMPING_TANTRUM]);
-    game.override.enemyMoveset([Moves.ROOST, Moves.ROOST, Moves.ROOST, Moves.ROOST]);
+    game.override.enemyLevel(60);
+    game.override.enemyMoveset([Moves.EARTHQUAKE, Moves.EARTHQUAKE, Moves.EARTHQUAKE, Moves.EARTHQUAKE]);
```
Comment (innerthunder) [inline src/test/moves/roost.test.ts:33]:
```suggestion
    game.override.enemyMoveset(Moves.EARTHQUAKE);
```
A recent change to moveset overrides makes this so that the enemy's only move is Earthquake

File: src/test/moves/roost.test.ts [hunk 3]
```diff
@@ -27,33 +27,205 @@ describe("Moves - Roost", () => {
...
+   */
+
+  test(
+    "Non flying type uses roost -> no type change, took damage",
+    async () => {
+      await game.classicMode.startBattle([Species.DUNSPARCE]);
+      game.move.select(Moves.ROOST);
+      const playerPokemon = game.scene.getPlayerPokemon()!;
+      const playerPokemonStartingHP = playerPokemon.hp;
+      let playerPokemonTypes = playerPokemon.getTypes();
```
Comment (innerthunder) [inline src/test/moves/roost.test.ts:61]:
```suggestion
      const playerPokemon = game.scene.getPlayerPokemon()!;
      const playerPokemonStartingHP = playerPokemon.hp;
      let playerPokemonTypes = playerPokemon.getTypes();
      
      game.move.select(Moves.ROOST);
```
This avoids potential desync issues. You're currently collecting the player's types and starting HP as the turn is progressing (this also applies to the other tests)

**Review by innerthunder — CHANGES_REQUESTED** [review]

File: src/data/battler-tags.ts (hunk 1 above)
Comment (PrabbyDD) [reply src/data/battler-tags.ts:2320]: Ill take a peek at this, hopefully its the same as what i did for burn up, will need another test case tho

File: src/test/moves/roost.test.ts (hunk 3 above)
Comment (PrabbyDD) [reply src/test/moves/roost.test.ts]: Thanks for all the help!

**Comment by PrabbyDD** [comment]
Also I tried linking the issue by putting the number in my description, how did you do it in the comments? @innerthunder

**Comment by innerthunder** [comment]
> Also I tried linking the issue by putting the number in my description, how did you do it in the comments? @innerthunder

Not related to the comments, I can just link them manually as a junior dev :)

**Comment by PrabbyDD** [comment]
I see

> > Also I tried linking the issue by putting the number in my description, how did you do it in the comments? @innerthunder
> 
> Not related to the comments, I can just link them manually as a junior dev :)

I see lol. Also when it says my branch is out of date with the branch, does that mean i need to update it before the PR?

File: src/data/battler-tags.ts [hunk 4]
```diff
@@ -1886,17 +1886,94 @@ export class CursedTag extends BattlerTag {
...
+    super(BattlerTagType.DOUBLE_SHOCKED, BattlerTagLapseType.CUSTOM, 1, Moves.DOUBLE_SHOCK);
+  }
+}
+
+export class BurnedUpTag extends BattlerTag {
+  constructor() {
+    super(BattlerTagType.BURNED_UP, BattlerTagLapseType.CUSTOM, 1, Moves.BURN_UP);
+  }
+}
+
```
[the remark this answers is not in the document]
Comment (PrabbyDD) [reply src/data/battler-tags.ts:1900]: I suppose I can merge them into a single class.

**Review by innerthunder — APPROVED** [review]
