### PR TITLE
fix(move): Gravity displays a message when grounding Pokémon

### LINKED ISSUE #6865: [Bug] Gravity should show a message upon grounding an airborne Pokemon
### Describe the bug

We currently don't even ground airborne Pokemon at the moment lol, so that will need to be fixed first and foremost.

### Reproduction

1. Use gravity on a rookidee
2. No message appears for removing the effects.

### Expected behavior

shows message (checked on showdown)
https://abcboy101.github.io/poke-corpus/#q=fell+from+the+sky&s=kcNsKvfM

> [!IMPORTANT]
> I checked this with Magnet Rise, and the Gravity-specific message appears to override _all messages for the effects it removes_. 
> This means we will need to have some mechanism to suppress Magnet Rise (& Telekinesis') removal messages when cleared via Gravity.

### Screenshots / Videos

_No response_

### Session export file

N/a

### User data export file

N/A

### Additional context

Probably unactionable until #5950 is merged

### PR DESCRIPTION
**Pull request by afonsob05**
## What are the changes the user will see?

The move "Gravity" will now show a message regarding Pokémon affected by the move.

## Why am I making these changes?

The fix addresses a lack of visual input regarding the move "Gravity", as reported in issue #6865
Before, new players that used the move would only see a message about the move being active, being left clueless on what the move actually does (without consulting the Wiki), which can be a bit troublesome. Not only that, the original games have had a message regarding pokemon affected by "Gravity", for as long as the move itself exists. This fix aims to be an addition to the visual input of the move, thus improving playability! 

Fixes #6865

## What are the changes from a developer perspective?

The only change made is in the [arena-tag.ts](src/data/arena-tag.ts) file, inside `GravityTag.onAdd`.
It now queues a message when Gravity grounds a Pokemon, making the effect visible to players, without changing gameplay logic (since other maintainers are assigned to implement and hone the mechanics behind this move).

Edit: the variable "wasGrounded", stating the grounded condition of a pokemon, was added at the beginning of the loop. In addition to that, the message display is now nested inside an if clause regarding the "wasGrounded" variable. This ensures that the message (previously shown for all pokemon in the battlefield), now shows only for non-grounded pokemon (flying, floating, etc.)

## Screenshots/Videos

<details><summary>Before</summary>

[before screenshot here](https://github.com/user-attachments/assets/3be53753-07a0-4358-860e-587eafec860f)

</details>
<details><summary>After</summary>

[after screenshot here](https://github.com/user-attachments/assets/d9b24070-7b53-4ac7-ae64-b887f8ef5ede)

</details>

## How to test the changes?

(OUTDATED) Since the fix implements only the message queue (without any logic), any pokemon can be used! However, when fixes regarding mechanics are implemented (currently assigned to other maintainers), this shall be tested with floating/flying Pokémon! 

Edit: As for now, the message display is now conditional! For the best test outcome, this should be tested with a non-grounded pokemon and a flying/floating one!

+ Select a Rookidee as the foe pokemon
+ Select a non-flying pokemon for your own
+ Make sure the moveset of your pokemon has gravity
+ Use the move!
+ The message "*the foe Pokemon* fell from the sky due to gravity!" should be displayed (edit: the message should be displayed only for the rookidee)!!

## Checklist

- The PR content is correctly formatted:
  - [X] **I'm using `beta` as my base branch**
  - [X] **The current branch is not named `beta`, `main` or the name of another long-lived feature branch**
  - [X] I have provided a clear explanation of the changes within the PR description
  - [X] The PR title matches the Conventional Commits format (as described in [CONTRIBUTING.md](https://github.com/pagefaultgames/pokerogue/blob/beta/CONTRIBUTING.md#pr-title-format))
- [X] The PR is self-contained and cannot be split into smaller PRs
- [X] There is no overlap with another open PR
- The PR has been confirmed to work correctly:
  - [X] I have tested the changes manually
  - [X] The full automated test suite still passes (use `pnpm test:silent` to test locally)
  - [~] I have created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes if necessary
- [X] I have provided screenshots/videos of the changes (if applicable)
- [~] I have made sure that any UI changes work for both the default and legacy UI themes (if applicable)

Are there any localization additions or changes? If so:
- [X] I have created an associated PR on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repository
  - If so, include a link to the PR here: [link](https://github.com/pagefaultgames/pokerogue-locales/pull/297)
- [X] I have contacted the Translation Team on Discord for proofreading/translation

Does this require any additions or changes to in-game assets? If so:
- [~] I have created an associated PR on the [assets](https://github.com/pagefaultgames/pokerogue-assets) repository
  - If so, include a link to the PR here: _____

### CODE REVIEW

File: src/data/arena-tag.ts [hunk 1]
```diff
@@ -1228,6 +1228,11 @@ export class GravityTag extends SerializableArenaTag {
         if (pokemon.getTag(BattlerTagType.FLYING)) {
           pokemon.addTag(BattlerTagType.INTERRUPTED);
         }
+        globalScene.phaseManager.queueMessage(
+          i18next.t("arenaTag:gravityGroundsPokemon", {
+            pokemonNameWithAffix: getPokemonNameWithAffix(pokemon),
+          }),
+        );
```
Comment (Bertie690) [inline src/data/arena-tag.ts]: The message should only play for Pokemon that were successfully grounded by Gravity's effect (i.e. Gravity made them go from airborne to not airborne).

As it stands, we are showing the message for every single pokemon on field.

**Review by Bertie690 — CHANGES_REQUESTED** [review]
Please remove the locales submodule change - that should not be committed to beta.

Other than that, it looks OK.

File: src/data/arena-tag.ts (hunk 1 above)
Comment (fabske0) [reply src/data/arena-tag.ts]: @Bertie690 Is this something to be addressed by this PR or just a note for later?

Comment (Bertie690) [reply src/data/arena-tag.ts]: A request to fix some incorrect functionality.

Comment (afonsob05) [reply src/data/arena-tag.ts]: @Bertie690 the issue should be fixed now! Also updated the PR description and info!

**Review by fabske0 — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]

**Review by Bertie690 — APPROVED** [review]
LGTM!
