### PR TITLE
[Bug] [Ability] Prevent message flyout spam for sturdy, damp, and a few other abilities

### LINKED ISSUE #1476: bug, Damp activation feedback messages
So while damp did in fact cancel them, this minior tried using 5 suicide moves on its turn, not even just the same move but both Selfdestruct and Explosion

https://github.com/pagefaultgames/pokerogue/assets/46976469/2eb78c82-302b-42b1-9587-cd871b08e294

### LINKED ISSUE #5632: [Bug] Sturdy card slides in and out multiple times
### Describe the bug

Sturdy card slides in and out a bunch of times at the start of a double battle turn when the opponent is preparing a OHKO move like fissure. I have not confirmed where else this may occur, but it seems to slide in and out at the start of the turn any time an OHKO move is prepared against a sturdy ability

### Reproduction

My scenario:
1. Sawsbuck and Excadrill (passive sturdy), facing boss Whiscash with fissure and arbok
2. horn leech on whiscash, earthquake on all,
3. Whiscash prepares fissure on excadrill
4. sturdy slides in and out at start of turn before turn plays out as normal
5. Sawsbuck revives with reviver seed

2nd turn:
1. horn leech on whiscash, earthquake on all
2. whiscash prepares fissure
3. sturdy card slides in and out 3 times before turn plays out as normal

Extra: 
1. Sawsbuck has 3 quick claws, could be some kind of code clash there

### Expected behavior

Sturdy should only appear in response to an OHKO move being used right when the move is used rather than the start of the turn order

### Screenshots / Videos

Didnt think to record it, but it happened on floor 90 boss

### Session export file

[sessionData_GigachadGamerman.txt](https://github.com/user-attachments/files/19618680/sessionData_GigachadGamerman.txt)

### User data export file

[data_GigachadGamerman.txt](https://github.com/user-attachments/files/19618688/data_GigachadGamerman.txt)

### Additional context

Sawsbuck should be named "Flingo" and Excadrill "Clonkinator"...
This is not important to addressing the bug, but it is important to Flingo and Clonkinator

### PR DESCRIPTION
**Pull request by SirzBenjie**
## What are the changes the user will see?
Sturdy, damp, and other abilities with flyouts should now only trigger once instead of a bunch of times, and will no longer send the flyout prematurely.

## Why am I making these changes?
This is one of the most annoying and frustrating bugs that slows down the game.
Fixes #5632
Fixes #1476 

## What are the changes from a developer perspective?
Added a new abstract class to abilities, `CancelInteractionAbAttr` with this body:
```ts
abstract class CancelInteractionAbAttr extends AbAttr {
  override canApply({ cancelled }: AbAttrParamsWithCancel): boolean {
    return !cancelled.value;
  }

  override apply({ cancelled }: AbAttrParamsWithCancel): void {
    cancelled.value = true;
  }
}
```
For basic abilities that just need to cancel an interaction, they can all inherit this (for DRYness). If they need to adjust either the `canApply` or the `apply` method, then they can do so.

I then searched through all of the abilities that were setting `cancelled.value = true` in the ability attributes. If this was all they were doing, and they were inheriting from the basic `AbAttr`, then I changed them to instead inherit from `CancelInteractionAbAttr`.

Added a temporary adjustment to damp's moveConditionFunc (yes, this is implemented on the move instead of the ability, tho it should probably be moved to the ability) that checks a "simulated" -- basically, if the current phase is `enemyCommandPhase`. This stops damp from displaying its message during the enemy command phase.

## Screenshots/Videos
<details><summary>Explosion/Damp post fix</summary>
Note: the excess messages where the custom failure message plays in addition to the "but it failed!" message and out of order are already a thing and can/should be addressed by #6276

https://github.com/user-attachments/assets/d894e266-765a-445d-89fd-06f4a862b498
</details> 

<details><summary>Sturdy message post fix</summary>

https://github.com/user-attachments/assets/4ea06d08-1e3c-414d-9f28-036651931625
</details> 

## How to test the changes?
explosion/damp:
```ts
const overrides = {
  ENEMY_MOVESET_OVERRIDE: [MoveId.EXPLOSION],
  BATTLE_STYLE_OVERRIDE: "double",
  ABILITY_OVERRIDE: AbilityId.DAMP,
  MOVESET_OVERRIDE: [MoveId.SPLASH],
} satisfies Partial<InstanceType<OverridesType>>;
```

sturdy:
```ts
const overrides = {
  ENEMY_MOVESET_OVERRIDE: [MoveId.CRUNCH],
  BATTLE_STYLE_OVERRIDE: "double",
  ABILITY_OVERRIDE: AbilityId.STURDY,
  ENEMY_LEVEL_OVERRIDE: 1000,
  MOVESET_OVERRIDE: [MoveId.SPLASH],
} satisfies Partial<InstanceType<OverridesType>>;
```

## Checklist
- [x] **I'm using `hotfix-1.10.7` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  - [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes? Kinda hard since this relies on getting the AI to do command selection logic and check messages. I don't want to, we can add later.
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - ~~[ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

### CODE REVIEW

File: src/data/abilities/ability.ts [hunk 1]
```diff
@@ -396,7 +396,24 @@ export abstract class AbAttr {
   }
 }
 
-export class BlockRecoilDamageAttr extends AbAttr {
+/**
+ * Abstract class for ability attributes that simply cancel an interaction
+ *
+ * @remarks
+ * Abilities that have simple cancel interactions (e.g. {@linkcode BlockRecoilDamageAttr}) can extend this class to reuse the `canApply` and `apply` logic
+ * Classes can
```
Comment (DayKev) [inline src/data/abilities/ability.ts]:
```suggestion
```
