### PR TITLE
[Bug] Fix stat-protection-attribute not taking inverts (e.g. Contrary) into account

### LINKED ISSUE #776: Contrary Not Being Taken Into Account
When abilities like Clear Body and Flower Veil trigger to prevent stats lowering, they should take into account Contrary to see if the stats are actually going to be raised.

### PR DESCRIPTION
**Pull request by flx-sta**
## What are the changes the user will see?
When e.g your Pokemon has a stat-protection ability (e.g. [Clear Body](https://bulbapedia.bulbagarden.net/wiki/Clear_Body_(Ability))) and an an inverter ability/attribute like [Contrary](https://bulbapedia.bulbagarden.net/wiki/Contrary_(Ability)) the stat-protection attribute will take that invert into account.
So if the enemy has [Intimidate](https://bulbapedia.bulbagarden.net/wiki/Intimidate_(Ability)) your Pokemon will have it's ATK raised (see videos)

## Why am I making these changes?
To fix #776 
Protections shouldn't protect against positive effects. 
To quote Bulbapedia:

> Clear Body prevents stat reduction
 
So only **reductions** are prevented!

## What are the changes from a developer perspective?
The effect of `StatStageChangeMultiplierAbAttr` is now applied before resolving any `ProtectStatAbAttr`. Thus the `stage` (level) of the `BattleStat` change was properly altered at the time of resolving the protection 

## Screenshots/Videos

- Player Abilities: `Clear Body` & `Contrary`
- Enemy Abilities: `Intimidate`

1. Enemy `Intimidate` is inverted and Player `ATK +1` = `+1`
2. Player `Howl` is inverted by `Contrary` but then blocked by `Clear Body`
3. Enemy `Growl` is inverted and Player `ATK +1` = `+

https://github.com/user-attachments/assets/9dea3507-8320-485e-8d50-eb90afb40e75

### Overrides

```ts
const overrides = {
  ABILITY_OVERRIDE: Abilities.CLEAR_BODY,
  PASSIVE_ABILITY_OVERRIDE: Abilities.CONTRARY,
  OPP_ABILITY_OVERRIDE: Abilities.INTIMIDATE,
  OPP_MOVESET_OVERRIDE: [Moves.GROWL, Moves.GROWL, Moves.GROWL, Moves.GROWL],
  MOVESET_OVERRIDE: [Moves.HOWL, Moves.HOWL, Moves.HOWL, Moves.HOWL],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```
<sup>This is only one of many scenarios. There is also Abilities e.g. like [Flower Veil](https://bulbapedia.bulbagarden.net/wiki/Flower_Veil_(Ability))</sup>

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- ~~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~~[ ] Are the changes visual?~~
  - ~~[ ] Have I provided screenshots/videos of the changes?~~

### CODE REVIEW

**Review by DayKev — APPROVED** [review]

File: src/phases/stat-stage-change-phase.ts [hunk 1]
```diff
@@ -42,17 +42,23 @@ export class StatStageChangePhase extends PokemonPhase {
       return this.end();
     }
 
+    const stages = new Utils.IntegerHolder(this.stages);
```
Comment (torranx) [inline src/phases/stat-stage-change-phase.ts:45]:
```suggestion
    const stages = new Utils.NumberHolder(this.stages);
```

Comment (flx-sta) [reply src/phases/stat-stage-change-phase.ts:45]: But But But.. I want to feel like I'm actually using an integer, that can magically become a float or double 🫠

File: src/test/abilities/contrary.test.ts [hunk 2]
```diff
@@ -5,6 +5,7 @@ import { Species } from "#enums/species";
 import Phaser from "phaser";
 import { afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
 import { SPLASH_ONLY } from "../utils/testUtils";
+import { Moves } from "#app/enums/moves.js";
```
Comment (flx-sta) [inline src/test/abilities/contrary.test.ts:8]:
```suggestion
import { Moves } from "#app/enums/moves";
```

**Review by frutescens — APPROVED** [review]

**Review by DayKev — APPROVED** [review]

**Review by xsn34kzx — APPROVED** [review]

**Review by CodeTappert — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
