### PR TITLE
[Bug] Prevent self speed ties

### LINKED ISSUE #6701: [Bug] [Beta] Stat Buffs are no longer in order
### Describe the bug

Turn 1 used Contrary Superpower, defense was raised first then attack. Turn 2 using Contrary Superpower, it corrected to raising attack first then defense.

### Reproduction

Use moves that give you multiple stat changes in one turn. 

### Expected behavior

Stat changes should go in order (ATK -> DEF -> SPATK) etc

### Screenshots / Videos

_No response_

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Dean mentioned on discord it would be related to the stat buffs speed tieing with each other

### PR DESCRIPTION
**Pull request by emdeann**
## What are the changes the user will see?
Pokemon won't speed tie with themselves. For example, the stat changes from superpower will always be atk -> def in that order.

This needs to get pointed to the hotfix branch once it's up. No promises I'll be around

## Why am I making these changes?
Fixes #6701 

## What are the changes from a developer perspective?
When sorting by speed, the Pokemon are first grouped in the following manner: all consecutive entries of the same Pokemon are grouped together, and these groups are shuffled and sorted.

## How to test the changes?
Easiest thing to do is use moves like superpower, QD, etc.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  - [x] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

### CODE REVIEW

File: src/utils/speed-order.ts [hunk 1]
```diff
@@ -15,40 +15,42 @@ interface hasPokemon {
  * @param shuffleFirst - Whether to shuffle the list before sorting (to handle speed ties). Default `true`.
```
Comment (Bertie690) [inline src/utils/speed-order.ts]: Needs to be remofed i think

**Review by damocleas — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]
