### PR TITLE
[Bug][Refactor] Custom types from MEs are correctly applied on form changes

### LINKED ISSUE #5227: [Bug] Typings Granted by Weird Dream and Clowning Around Interact Poorly With Forms with a Different Number of Typings
### Describe the bug

If the Pokemon that can change forms gains or loses a secondary typing upon changing forms, and has had its typing modified by either Clowning Around or Weird Dream, The artificial typing is lost.

- Modifying Single Typing to Double Typing
Typing becomes that of the Pokemon's new Form, completely replacing the artificial typing.
Upon reverting back to Single Typing, the Pokemon's other Form's Secondary Typing is smuggled.
If the Pokemon can have different Secondary Typings, the Secondary Typing changes to be correct for that form. (Ogerpon)

- Modifying Double Typing to Single Typing
After changing Forms from Double Typing to Single Typing, artificial Typing is retained.
Upon reverting back to the Double Typing Form, artificial Typing is lost, and it becomes the correct Typing for that Form.

- Modifying Double Typing to Double Typing
Artificial Typing is completely retained.

- Modifying Single Typing to Single Typing
Artificial Typing is completely retained.
Arceus can be made to be monotype, if the activated plate matches the artificial Typing.

Link to Discord's Bug Report (Clown mystery encounter with some pokemon)
https://discord.com/channels/1125469663833370665/1305698600608600085

### Reproduction

Weird Dream
1. Leave
2. Lock and Roll until you get a FormChangeItem and Pokemon that would gain a new typing upon form change.
```
	STARTING_WAVE_OVERRIDE: 11,

	MYSTERY_ENCOUNTER_RATE_OVERRIDE: 255,

	MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.WEIRD_DREAM,

	STARTING_MODIFIER_OVERRIDE: [{name: "MEGA_BRACELET"}, {name: "GOLDEN_POKEBALL", count:3}, {name: "LOCK_CAPSULE"}],

        WAIVE_ROLL_FEE_OVERRIDE:  true,
```

Clowning Around
1. Insult the Clown or Remain Unprovoked in order to get the Form change item first.
2. Change forms in the rewards menu
```
	STARTING_WAVE_OVERRIDE: 11,

	MYSTERY_ENCOUNTER_RATE_OVERRIDE: 255,

	MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.CLOWNING_AROUND,

	STARTING_MODIFIER_OVERRIDE: [{name: "MEGA_BRACELET"}, {name: "GOLDEN_POKEBALL", count:3}, {name: "LOCK_CAPSULE"}],

        WAIVE_ROLL_FEE_OVERRIDE:  true,
```

### Expected behavior

The Secondary Artificial Typing should not be lost upon Form change from Single to Double Typing.

Secondary Typing from Forms should not be smuggled.

### Screenshots / Videos

Copperajah (Steel Rock) to G-Max Copperajah (Steel Ground) to Copperajah (Steel Ground)

https://github.com/user-attachments/assets/50727173-59c7-47fe-8d18-348037c8fc45

Zacian-Crowned (Fairy Dark) to Zacian (Fairy Dark) to Zacian-Crowned (Fairy Steel)

https://github.com/user-attachments/assets/2f431e5e-1c4b-48ab-8e72-916eca4d74da

Weird Dream Groudon (Ground Normal) to Primal Groudon (Ground Fire)

https://github.com/user-attachments/assets/a5c939d9-3f6c-4c65-8a53-4599b09fbfaf

Diancie (Rock Psychic) to Mega Diancie (Rock Psychic) to Diancie (Rock Psychic)

https://github.com/user-attachments/assets/e5f1f8fd-9f9c-420f-b954-f2b526b10658

Arceus

https://github.com/user-attachments/assets/9a2827a8-dcef-46e7-aa70-eb40f82bcd4c

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Wlowscha**
## What are the changes the user will see?
Fixes #5227 : type changes obtained from a ME persist through form changes, no smuggling of types to base forms.

## What are the changes from a developer perspective?
In the Pokemon.getType() function, types from customPokemonData were checked separately from the Species.types. For this reason, it was necessary to include in customPokemonData even the types that were not being changed. This introduced some weirdness on form changes, which required to also change the customPokemonData when a form change occurs.

After the refactoring, the Species.types are applied first, then they are overridden by the customPokemonData.types. If a type in customPokemonData is Type.UNKNOWN, it is skipped. The types in customPokemonData are no longer updated on a form change.

The test for the Clowning Around encounter has been changed; instead of directly accessing customPokemonData, it instead checks that getTypes() returns the correct values.

Examples:
Copperajah is steel type, and its G-Max form is steel/ground. Consider a ME that adds the type normal as a secondary type. Before, this would happen:
After ME, customPokemonData is STEEL / NORMAL
After form changing to G-Max, customPokemonData sees that the secondary type is different and changes  customPokemonData to STEEL / GROUND
After form changing back, customPokemonData sees that the form only has a primary type, therefore doesn't check the primary type and customPokemonData is still STEEL / GROUND

After the changes:
After ME, customPokemonData is UNKNOWN / NORMAL
The types in customPokemonData are not affected by form changes, so the secondary type persists.

Another example, with Castform; this worked properly but for the wrong reasons. Previously it worked like this:
After ME, customPokemonData is NORMAL / GROUND
After using Rain Dance, Castform changes to a new form; the customPokemonData must be changed accordingly and becomes 
WATER / GROUND

After the changes:
After ME, customPokemonData is UNKNOWN/ GROUND
After using Rain Dance, the UNKNOWN in the primary type in customPokemonData is ignored and the primary type of the base form is correctly displayed.

## Screenshots/Videos
Copperajah working as intended:
https://github.com/user-attachments/assets/f9250a78-3233-4826-b59c-e13995592e66

Castform continues to work as intended after the changes:
https://github.com/user-attachments/assets/a9cd426f-c7f9-4947-8115-c2118bde3982

## How to test the changes?
Overrides for the examples above: 

const overrides = {
  STARTER_SPECIES_OVERRIDE: Species.COPPERAJAH,
  STARTING_WAVE_OVERRIDE: 11,
  STARTING_LEVEL_OVERRIDE: 100,
  MOVESET_OVERRIDE: [Moves.TACKLE],
  MYSTERY_ENCOUNTER_RATE_OVERRIDE: 128,
  MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.CLOWNING_AROUND,
  STARTING_MODIFIER_OVERRIDE: [{name: "DYNAMAX_BAND"}, {name: "GOLDEN_POKEBALL", count:3}, {name: "LOCK_CAPSULE"}],
  ITEM_REWARD_OVERRIDE: [{name: "FORM_CHANGE_ITEM", type: FormChangeItem.MAX_MUSHROOMS}],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;

const overrides = {
  STARTER_SPECIES_OVERRIDE: Species.CASTFORM,
  STARTING_WAVE_OVERRIDE: 11,
  STARTING_LEVEL_OVERRIDE: 100,
  MOVESET_OVERRIDE: [Moves.TACKLE, Moves.RAIN_DANCE, Moves.HAIL, Moves.SUNNY_DAY],
  MYSTERY_ENCOUNTER_RATE_OVERRIDE: 128,
  MYSTERY_ENCOUNTER_OVERRIDE: MysteryEncounterType.CLOWNING_AROUND,
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
- [x] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -1306,6 +1283,38 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
         if (types.length === 1 && speciesForm.type2 !== null) {
           types.push(speciesForm.type2);
         }
+
+        // "Permanent" override for a Pokemon's normal types, currently only used by Mystery Encounters
+        if (this.customPokemonData.types && this.customPokemonData.types.length > 0) {
```
Comment (DayKev) [inline src/field/pokemon.ts:1288]:
```suggestion
        if (this.customPokemonData.types?.length > 0) {
```
Pretty sure you can simplify it to this.

**Review by DayKev — COMMENTED** [review]
You should also add some tests for `Pokemon.getTypes()` to check various scenarios involving form changes/fusion.

**Review by damocleas — APPROVED** [review]

**Review by DayKev — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]
