### PR TITLE
[Move] Trick Room now reverses itself when added twice in a row

### LINKED ISSUE #4604: [Bug] Trick Room Does Not End when Used Again While Active
### Describe the bug

Trick Room continues to be present if the move is used while the Trick Room Field Effect is Active.

Magic Room and Wonder Room should have this interaction as well, however, they are not yet implemented.

Link to Discord (Trick Room not reverting when used twice)
https://discord.com/channels/1125469663833370665/1292692532542701659

### Reproduction

Use Trick Room with Trick Room active

### Expected behavior

https://replay.pokemonshowdown.com/gen9customgame-2217571587-wnyqjg92072t6yfc94dbav1z7ayhu2rpw
Trick Room should get rid of Trick Room

> Similar to Magic Room and Wonder Room, using Trick Room while it is already in effect will end it immediately.
-Bulba

### Screenshots / Videos

Trick Room does not remove Trick Room

https://github.com/user-attachments/assets/e303b81e-0536-40a6-b150-bbd9e8cb1fbd

Beta

https://github.com/user-attachments/assets/3db2100a-0051-4113-ad79-ec032da0c8e1

### Session export file

@
[TrickRoomTrickRoom.txt](https://github.com/user-attachments/files/17273546/TrickRoomTrickRoom.txt)

### User data export file

_No response_

### Additional context

https://github.com/pagefaultgames/pokerogue/pull/3394
Wonder Room PR does not seem to mention that this should occur

https://github.com/pagefaultgames/pokerogue/pull/4343
Trick Room Challenges

### PR DESCRIPTION
**Pull request by Bertie690**
## What are the changes the user will see?
Trick room now reverses itself when used while TR is up.

## Why am I making these changes?
Mainline parity

Fixes #4604 
## What are the changes from a developer perspective?
Added a new abstract class, `RoomArenaTag`, which implements shared logic for the Room moves to remove themselves upon overlapping. This is currently only used by TR, but will be extended for the other moves as well.

## Screenshots/Videos
N/A
## How to test the changes?
`pnpm test trick-room.test.ts`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  - [x] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?

### CODE REVIEW

File: src/@types/arena-tags.ts [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import type { ArenaTagTypeMap } from "#data/arena-tag";
 import type { ArenaTagType } from "#enums/arena-tag-type";
+// biome-ignore lint/correctness/noUnusedImports: TSDocs
+import type { SessionSaveData } from "#system/game-data";
```
Comment (DayKev) [inline src/@types/arena-tags.ts:4]:
```suggestion
// biome-ignore-start lint/correctness/noUnusedImports: TSDoc imports
import type { SessionSaveData } from "#system/game-data";
// biome-ignore-end lint/correctness/noUnusedImports: TSDoc imports

import type { ArenaTagTypeMap } from "#data/arena-tag";
import type { ArenaTagType } from "#enums/arena-tag-type";
```

File: test/test-utils/helpers/field-helper.ts [hunk 2]
```diff
@@ -45,20 +46,38 @@ export class FieldHelper extends GameManagerHelper {
...
+   * (such as for comparison with other speed order-related mechanisms); default `false`
+   * @returns An array containing the {@linkcode BattlerIndex}es of all on-field {@linkcode Pokemon} on the field in order of descending Speed. \
+   * Speed ties are returned in increasing order of index.
+   *
+   * @remarks
+   * This does not account for Trick Room as it does not modify the _speed_ of Pokemon on the field,
+   * only their turn order.
+   */
+  public getSpeedOrder(indices: true): BattlerIndex[];
+  public getSpeedOrder(indices = false): BattlerIndex[] | Pokemon[] {
```
Comment (DayKev) [inline test/test-utils/helpers/field-helper.ts:72]: These overloads are really not necessary lol.

File: src/@types/arena-tags.ts (hunk 1 above)
Comment (SirzBenjie) [reply src/@types/arena-tags.ts:4]: Why? In case we need to add more later?

Comment (Bertie690) [reply src/@types/arena-tags.ts:4]: presumably

**Review by Wlowscha — APPROVED** [review]

File: src/@types/arena-tags.ts (hunk 1 above)
Comment (DayKev) [reply src/@types/arena-tags.ts:4]: Unfortunately TSDoc imports have to be managed manually, so they should be separated from the rest of the imports so they're easier to manage.
