### PR TITLE
Fix #5082: Nicknames not properly sanitized

### LINKED ISSUE #5082: [Bug] Nicknames not Properly Sanitized
### Describe the bug

Using @c{}, @s{}, @d{}, @f{}, and $ in Pokemon Nicknames allows undesirable customization.

Relevant Code in message-ui-handler.ts
https://github.com/pagefaultgames/pokerogue/blob/355e70328c7e079e7deaf598059108885b91c8e5/src/ui/message-ui-handler.ts#L51

Link to Discord's Bug Report (Extra Text after Learn Move)
https://discord.com/channels/1125469663833370665/1289679259501203638

### Reproduction

Put @c{}, @s{SoundName}, @d{Value}, @f{Value}, or $ in a Pokemon Nickname.

### Expected behavior

Things should not occur when these characters are present in nicknames.

### Screenshots / Videos

Using $

https://github.com/user-attachments/assets/6a4c7ef5-d08a-435c-9e2d-7c9037dfab8a

using @d{}

https://github.com/user-attachments/assets/4f521fd0-63dd-49d4-9c8a-f2fcde74316a

using @s{}

https://github.com/user-attachments/assets/06524e1d-8aff-472b-89c9-29ed160ad1ef

Using @f{}

https://github.com/user-attachments/assets/e082e017-ff7b-408e-9f72-8753c597fd6e

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mati-soda**
## What are the changes the user will see?
When the player renames the pokemon to a nickname that contains the following symbols: "@c{}", "@s{}", "@d{}", "@f{}" and "$" the text will appear properly without causing abnormalities such as the name being cut or the game fading into black.

## Why am I making these changes?
To ensure all nicknames can be used without any abnormalities happening.
Fixes #5082

## What are the changes from a developer perspective?
- on message-ui-handler.ts file I updated the "showTextInternal" function to get the original name of the pokemon or pokemons (in case it's a double battle) saving it in a list named "pokename" and change it in the text for their  correspondent placeholder which is saved in the list "repname" (e.g "#POKEMON1" for the first pokemon and "#POKEMON2" for the second pokemon). After the text is properly modified because of the special characters ("@c{}", "@s{}", "@d{}", "@f{}")  the name of the pokemons is replaced to it's original value. 
- on message-phase.ts file I updated the "start" function to use a similar approach but only change the pokemon name to it's original form after the "pageIndex" (which checks the index of the "$") is updated, so the text is cut properly.
- on ui.ts file I updated the "showtext" function to use same approach of the previous files, ensuring that the pokemon names were only replaced back to their original values after all text processing on "$" was completed.

## Screenshots/Videos

https://github.com/user-attachments/assets/7a0b4618-5b14-4127-8a9c-27fc5aa13e64

## How to test the changes?
Add to the nickname of the pokemon any the following set of characters "@c{}", "@s{}", "@d{}", "@f{}" and "$".

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes manually?
- [X] Are all unit tests still passing? (`npm run test`)
  - [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [X] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [ ] If so, please leave a link to it here: 
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

File: src/phases/message-phase.ts [hunk 1]
```diff
@@ -28,17 +28,28 @@ export class MessagePhase extends Phase {
     super.start();
 
     if (this.text.indexOf("$") > -1) {
+      let pokename: string[] = [];
+      let repname = [ "#POKEMON1", "#POKEMON2" ];
```
Comment (DayKev) [inline src/phases/message-phase.ts:32]:
```suggestion
      const pokename: string[] = [];
      const repname = [ "#POKEMON1", "#POKEMON2" ];
```

File: src/ui/message-ui-handler.ts [hunk 2]
```diff
@@ -76,6 +76,12 @@ export default abstract class MessageUiHandler extends AwaitableUiHandler {
     const fadeMap = new Map<number, number>();
     const actionPattern = /@(c|d|s|f)\{(.*?)\}/;
     let actionMatch: RegExpExecArray | null;
+    let pokename: string[] = [];
+    let repname = [ "#POKEMON1", "#POKEMON2" ];
```
Comment (DayKev) [inline src/ui/message-ui-handler.ts:80]:
```suggestion
    const pokename: string[] = [];
    const repname = [ "#POKEMON1", "#POKEMON2" ];
```

File: src/ui/ui.ts [hunk 3]
```diff
@@ -328,17 +328,28 @@ export default class UI extends Phaser.GameObjects.Container {
     prompt?: boolean | null,
     promptDelay?: number | null,
   ): void {
+    let pokename: string[] = [];
+    let repname = [ "#POKEMON1", "#POKEMON2" ];
```
Comment (DayKev) [inline src/ui/ui.ts:332]:
```suggestion
    const pokename: string[] = [];
    const repname = [ "#POKEMON1", "#POKEMON2" ];
```

**Review by DayKev — COMMENTED** [review]
Seems to work, just need to fix the lack of `const`.

**Review by DayKev — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]

**Review by damocleas — APPROVED** [review]
