### PR TITLE
[UI/UX] Show correct max duration in flyout

### LINKED ISSUE #6521: [Bug] [UI/UX] Weather's total turn count resets to numerator on reload
Bug report initiated by Discord user **sirz_benjie**
### Describe the bug

[Related Discord message](https://discord.com/channels/1125469663833370665/1414595208204783717/1414644985445482518)

When you have a weather or terrain active and you reload, the maximum becomes what is left (could be 1/1 if one turn left when you reload) and so on

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by fabske0**
## What are the changes the user will see?

After reloading the game the arena flyout will now correctly show the max duration of the effect, instead of just the remaining one.

> [!NOTE]
> For effects from already existing saves, the remaining duration will be shown. 
> The max duration is only saved for NEW effects

## Why am I making these changes?

fixes #6521

## What are the changes from a developer perspective?

- Weather, terrain and tags got an `maxDuration` property.
- The arena events also got this added and used when loading a session

## Screenshots/Videos

<details open><summary>Video</summary>

https://github.com/user-attachments/assets/8acc4426-2330-467b-a11f-92d13d061355

</details> 

## How to test the changes?

Use an ability/move that adds a weather/terrain/tag with a duration. then play the wave so the duration decreases and then reload and make sure the flyout still shows the max duration.
I mainly used these overrides to test:
```ts
const overrides = {
  ABILITY_OVERRIDE: AbilityId.DRIZZLE,
  MOVESET_OVERRIDE: MoveId.TAILWIND,
  PASSIVE_ABILITY_OVERRIDE: AbilityId.NEUTRALIZING_GAS,
  STARTING_HELD_ITEMS_OVERRIDE: [{name: "MYSTICAL_ROCK", count: 2}]
} satisfies Partial<InstanceType<OverridesType>>;
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  ~~- [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?~~
- [x] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

File: src/events/arena.ts [hunk 1]
```diff
@@ -20,10 +20,13 @@ export enum ArenaEventType {
 export class ArenaEvent extends Event {
   /** The total duration of the {@linkcode ArenaEventType} */
   public duration: number;
-  constructor(eventType: ArenaEventType, duration: number) {
+  /** The maximum duration of the {@linkcode ArenaEventType} */
+  public maxDuration: number;
+  constructor(eventType: ArenaEventType, duration: number, maxDuration: number) {
```
Comment (Wlowscha) [inline src/events/arena.ts]: Could we make `maxDuration` optional here?

File: src/system/game-data.ts [hunk 2]
```diff
@@ -1021,6 +1021,7 @@ export class GameData {
             WeatherType.NONE,
             globalScene.arena.weather?.weatherType!,
             globalScene.arena.weather?.turnsLeft!,
+            globalScene.arena.weather?.maxDuration!,
           ),
```
Comment (Wlowscha) [inline src/system/game-data.ts:1025]: How come we have all these bangs here? If `arena.weather` cannot be null, they should not be necessary... but if it can, wouldn't the call be wrong?

Comment (fabske0) [reply src/system/game-data.ts:1025]: Idk. But vscode yells at me when i remove them. Atleast for the `turnsLeft` and type. `maxDuration` is fine.
And looking into why the weather/terrain is `weather: Weather | null` probably exceeds the scope of this PR

File: src/data/terrain.ts [hunk 3]
```diff
@@ -22,10 +22,12 @@ export interface SerializedTerrain {
 export class Terrain {
   public terrainType: TerrainType;
   public turnsLeft: number;
+  public maxDuration: number;
 
-  constructor(terrainType: TerrainType, turnsLeft?: number) {
+  constructor(terrainType: TerrainType, turnsLeft?: number, maxDuration?: number) {
     this.terrainType = terrainType;
     this.turnsLeft = turnsLeft || 0;
+    this.maxDuration = maxDuration || turnsLeft || 0;
```
Comment (DayKev) [inline src/data/terrain.ts]:
```suggestion
  constructor(terrainType: TerrainType, turnsLeft = 0, maxDuration: number = turnsLeft) {
    this.terrainType = terrainType;
    this.turnsLeft = turnsLeft;
    this.maxDuration = maxDuration;
```

File: src/data/weather.ts [hunk 4]
```diff
@@ -19,10 +19,12 @@ export interface SerializedWeather {
 export class Weather {
   public weatherType: WeatherType;
   public turnsLeft: number;
+  public maxDuration: number;
 
-  constructor(weatherType: WeatherType, turnsLeft?: number) {
+  constructor(weatherType: WeatherType, turnsLeft?: number, maxDuration?: number) {
     this.weatherType = weatherType;
     this.turnsLeft = !this.isImmutable() ? turnsLeft || 0 : 0;
+    this.maxDuration = !this.isImmutable() ? maxDuration || turnsLeft || 0 : 0;
```
Comment (DayKev) [inline src/data/weather.ts]:
```suggestion
  constructor(weatherType: WeatherType, turnsLeft = 0, maxDuration: number = turnsLeft) {
    this.weatherType = weatherType;
    this.turnsLeft = this.isImmutable() ? 0 : turnsLeft;
    this.maxDuration = this.isImmutable() ? 0 : maxDuration;
```

File: src/events/arena.ts [hunk 5]
```diff
@@ -20,10 +20,13 @@ export enum ArenaEventType {
 export class ArenaEvent extends Event {
   /** The total duration of the {@linkcode ArenaEventType} */
   public duration: number;
-  constructor(eventType: ArenaEventType, duration: number) {
+  /** The maximum duration of the {@linkcode ArenaEventType} */
+  public maxDuration: number;
+  constructor(eventType: ArenaEventType, duration: number, maxDuration?: number) {
```
Comment (DayKev) [inline src/events/arena.ts]:
```suggestion
  constructor(eventType: ArenaEventType, duration: number, maxDuration: number = duration) {
```

File: src/events/arena.ts [hunk 6]
```diff
@@ -20,10 +20,13 @@ export enum ArenaEventType {
...
     super(eventType);
 
     this.duration = duration;
+    this.maxDuration = maxDuration || duration;
```
Comment (DayKev) [inline src/events/arena.ts]:
```suggestion
    this.maxDuration = maxDuration;
```

File: src/system/game-data.ts (hunk 2 above)
Comment (Bertie690) [reply src/system/game-data.ts:1025]: Basically if the weather type is `undefined` or 'WeatherType.NONE`, it tries to clear the weather data in the flyout.
Technically we don't need to do this if no weather/terrain is active, but yeah.

I know this due to actively removing the weird nullishness in #6142

**Review by Bertie690 — APPROVED** [review]
Lgtm, though it may be worth waiting for #6142 to be merged beforehand given it cleans up many of the related areas.

**Review by Bertie690 — APPROVED** [review]
You know what - changed my mind.
We should merge this before #6142 so I can resolve conflicts.

**Review by Wlowscha — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
