### PR TITLE
[Bug][Item] Fix Reviver Seed and endure triggering off of indirect damage

### LINKED ISSUE #5114: [Bug] Reviver Seed activates on Secondary Move and Ability Damage
### Describe the bug

Reviver Seed Activates on Secondary Damage from certain Moves and Abilities. Includes Vortex Damage, Salt Cure, Curse(target damage), and Leech Seed Damage, Iron Barbs, Liquid Ooze, and Aftermath Damage. it also correctly activates for Future Sight.
-It will not activate from Destiny Bond, Recoil damage, Self-Curse Damage Explosion, End-of-Turn Weather damage or Toxic, Burn, and Poison
-It currently does not activate from OHKO moves, incorrectly.

Link to Discord's Bug Report (Aftermath Triggers Reviver Seed)
https://discord.com/channels/1125469663833370665/1290582934214152232

and

Link to Discord's Bug Report (Reviver seed did not activate against fissure)
https://discord.com/channels/1125469663833370665/1308883042281979986

### Reproduction

Choose one of the above and faint to it.
```
STARTING_HELD_ITEMS_OVERRIDE: [{name: "REVIVER_SEED"}],
```

### Expected behavior

Continues to work for Future Sight and Direct Damage, but not Secondary Damage.

### Screenshots / Videos

<details><summary>
Salt Cure and Leech Seed
</summary>
Salt Cure

https://github.com/user-attachments/assets/8cc17a81-f5e4-435c-b888-a41b93dab3ac

Leech Seed

https://github.com/user-attachments/assets/3638cdfb-34b3-4708-b6b1-d3bfcb216793

</details>

<details><summary>
Abilities: (Liquid Ooze, Aftermath, Iron Barbs)
<summary>

Aftermath

https://github.com/user-attachments/assets/d770dab2-de13-4a9a-9da8-43ccc1e92c1f

Liquid Ooze

https://github.com/user-attachments/assets/c1513c17-7d15-440e-912c-ff12e5928b40

Iron Barbs

https://github.com/user-attachments/assets/c06be371-9f7b-4fbf-a166-b8f68ce4f732

</details>

<details><summary>
DamagingTrapTag (Vortex and binding damage moves; Fire-Spin)
</summary>

Fire Spin

https://github.com/user-attachments/assets/7b787693-1b50-46a6-b96c-90e4a316a95d

</details>

<details><summary>
Curse
</summary>

Curse Target

https://github.com/user-attachments/assets/44841a8e-53cf-4cb6-b320-f3118fcad906

Curse Recoil - Correct

https://github.com/user-attachments/assets/44cb7b7c-ace9-47a0-8d0e-bd9cde5e6f46
 
</details>

<details><summary>
Future Sight activates Reviver Seed - Correct
</summary>

https://github.com/user-attachments/assets/63a963cb-568b-486d-ac74-42ada53d007e

</details>

<details><summary>
Destiny Bond, Explosion, Recoil do not activate Reviver Seed - Correct
</summary>

Destiny Bond

https://github.com/user-attachments/assets/23d1e0c4-3dad-4af8-8295-d6a0ba318ad1

Explosion

https://github.com/user-attachments/assets/13014136-de1e-45e1-b213-f0f14460eff8

Steel Beam 

https://github.com/user-attachments/assets/e38b452f-28ab-4c6b-b32e-1388f4dbc031

 Double-Edge

https://github.com/user-attachments/assets/44e9db69-395d-40fa-bb9f-cb587868d83b

</details>

<details><summary>
Sandstorm (Weather Damage) does not activate Reviver Seed - Correct
</summary>

https://github.com/user-attachments/assets/bcc3a67b-bc48-4813-86fd-3977bdd23dd4

</details>

<details><summary>
Seismic Toss activates Reviver Seed - Correct
</summary>

https://github.com/user-attachments/assets/23f3867b-7b53-47f7-88c3-cae3fad476e8

</details>

<details><summary>
OHKO does not Activate Reviver Seed
</summary>

https://github.com/user-attachments/assets/04ab3605-46ae-4328-b544-5bba44c2cf90

</details>

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Screenshot (541)

This could be considered a list of Secondary effects that Endure incorrectly blocks.
> For the rest of the turn, Endure allows the user to survive any attack that would cause it to faint,
(Bulba)

### LINKED ISSUE #5115: [Bug] Endure and Endure Tokens Block most Secondary move and Ability Damage
### Describe the bug

Endure and Endure Tokens currently block most Secondary move and Ability damage
> Secondary Damage from certain Moves and Abilities. Includes Vortex Damage, Salt Cure, Curse(target damage), and Leech Seed > Damage, Iron Barbs, Liquid Ooze, and Aftermath Damage. it also correctly activates for Future Sight.
> -It will not activate from Destiny Bond, Recoil damage, Self-Curse Damage Explosion, End-of-Turn Weather damage or Toxic, > Burn, and Poison
> -It currently does not activate from OHKO moves, incorrectly.

Link to Discord's Bug Report (endure end of turn survival)
https://discord.com/channels/1125469663833370665/1302811441375739975

### Reproduction

Use Endure or trigger Endure Tokens, and be knocked past 1 HP by any of the above Secondary damage types.

### Expected behavior

Endure should block OHKO moves
https://replay.pokemonshowdown.com/gen9customgame-2279508797

Most Secondary damage should not trigger Endure (Salt Cure)
https://replay.pokemonshowdown.com/gen9customgame-2279499924

> For the rest of the turn, Endure allows the user to survive any attack that would cause it to faint, leaving the user with 1 HP instead.
-Bulba

### Screenshots / Videos
[[Bug] Reviver Seed activates on Secondary Move and Ability Damage #5114
](https://github.com/pagefaultgames/pokerogue/issues/5114)

Screenshot (541)

Salt Cure

https://github.com/user-attachments/assets/762722e2-bd70-4f01-a6e6-28fd155808bb

OHKO moves

https://github.com/user-attachments/assets/30b22061-9303-410b-9fdd-4122128c4fe8

### Session export file

_No response_

### User data export file

_No response_

### Additional context

Both Endure the move and Endure Tokens use the `ENDURING` battlertag
https://github.com/pagefaultgames/pokerogue/blob/d3fafa27702f2121e89852cc45481dd935a6a7fd/src/data/battler-tags.ts#L1559

Possibly Confusion with Endure Tokens
https://github.com/pagefaultgames/pokerogue/issues/1170

### PR DESCRIPTION
**Pull request by schmidtc1**
TODO:

- [x] Revise code to proc Reviver Seed on confusion, ignore all other indirect damage
- [x] Make OHKO moves not bypass Endure or Reviver Seed
- [x] Test manually
  - [x] Should activate RSeed
    - [x] "Normal" damaging moves
    - [x] OHKO moves
    - [x] Fixed damage
      - [x] Seismic toss
      - [x] Super fang
    - [x] Final Gambit
      - [x] Damage portion (self-faint portion should not activate RSeed)
    - [x] Confusion self-hit
    - [x] Delayed attacks (Future Sight)
    - [x] Counter moves
  - [x] Should not active RSeed
    - [x] Status damage (burn and poison)
    - [x] Hail/Sand chip
    - [x] Salt Cure, Curse, Leech Seed chip
      - [x] Salt Cure
      - [x] Curse
      - [x] Leech Seed
    - [x] Partial trapping chip (Magma Storm, Infestation, Whirlpool chip)
    - [x] Recoil damage
    - [x] Weather damage
    - [x] Deduction damage (Ghost Curse)
    - [x] Self-KOing (Explosion, Memento, Final Gambit)
    - [x] Damage from Liquid Ooze/Innards Out
      - [x] Fix Liquid Ooze 
      - [x] Innards Out
    - [x] Misc cases
      - [x] Fire Pledge
      - [x] Bad Dreams
- [x] Fix Endure from blocking indirect damage
- [x] Write/adjust unit tests
  - [x] Reviver Seed tests
  - [x] Endure tests

## What are the changes the user will see?

Reviver Seed's description states it triggers off of direct damage, but it triggers from some forms of indirect damage.
Reviver Seed should no longer trigger off of indirect damage (weather, Iron Barbs ability, status effect, etc.)
This PR will attempt to cover these cases mentioned on Discord:
https://discord.com/channels/1125469663833370665/1176874654015684739/1332821527787208777

## Why am I making these changes?

Bug fix/matching implementation to description

Fixes #5114
Fixes #5115

## What are the changes from a developer perspective?

Created a `damageSources` array under `turnData` which tracks `DamageResult`. This will store the latest `DamageResult` sent to the `damageAndUpdate` function in `turnData.damageSources[0]`. If no `DamageResult` is supplied, `HitResult.OTHER` is used which will mark it as an indirect damage.
`PokemonInstantReviveModifier` now checks for `HitResult.OTHER` in its apply function. If the most recent damage taken is `HitResult.OTHER`, the apply function returns early and has no effect.
Liquid Ooze now uses `HitResult.OTHER`, instead of `HitResult.HEAL`. 

## Screenshots/Videos

<details><summary>Status damage</summary>

https://github.com/user-attachments/assets/a9f792d0-d063-4d7e-bd62-e4d897c83b7b
</details>

<details><summary>Weather</summary>

https://github.com/user-attachments/assets/40f9be67-43a3-4205-a1e6-015b21b0eac5
</details>

<details><summary>OHKO</summary>

https://github.com/user-attachments/assets/7bc40b3d-f9fc-46bd-9eef-b839c366efdc
</details>

<details><summary>Endure</summary>

https://github.com/user-attachments/assets/b12d6af1-31a2-4c64-8060-2275a0cc4e56
</details>

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [n/a] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [n/a] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [n/a] If so, please leave a link to it here: 
- [n/a] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -5356,10 +5366,11 @@ export enum HitResult {
   FAIL,
   MISS,
   OTHER,
-  IMMUNE
+  IMMUNE,
+  SELF
```
Comment (Wlowscha) [inline src/field/pokemon.ts:5370]: From what I see the SELF HitResult is only used for confusion; maybe it would be appropriate to rename it to CONFUSION to avoid mixing it up with other types of self-damage, e.g. from Explosion or Metal Burst

**Comment by Wlowscha** [comment]
I have gone through the PR and looked at the relevant code, and I don't quite understand why it is necessary to introduce `this.turnData.damageSources`.
This is checked twice:
1) In `Pokemon.damage()`, where `!preventEndure` is also checked in the same condition,
2) In `PokemonInstantReviveModifier.apply()`, which is only called once in the code from `FaintPhase` and is locked behind an `if (!this.preventEndure)` condition.

There are only two `new FaintPhase`, one in `Pokemon.damage()` (which already looks at a `preventEndure` variable) and one in `Pokemon.apply()` (which is being changed in this PR to always set `preventEndure` to `false`. Therefore, it would seem that passing the correct `preventEndure` to `Pokemon.damage()` should be enough.

`Pokemon.damage()` itself is only called in three places:
1) `Pokemon.damageAndUpdate()`
2) In the code for Pain Split
3) In the status damage at the end of turn (poison, toxic, burn)

For (2) and (3) it could be argued that the `Pokemon.damage()` calls should be replaced by `Pokemon.damageAndUpdate()` anyway, but in any case they are easy to manage. Pain Split doesn't really matter since it never kills, and the status damage is already passing `true` as `preventEndure`. 
`Pokemon.damageAndUpdate()` is taking both a `HitResult` parameter and a `preventEndure`, so it should be possible to check here if the result is `HitResult.OTHER`, and, in that case, pass on `preventEndure = true` if it wasn't already.
(In fact, it might be preferable to remove `preventEndure` altogether and only look at the `HitResult`, since this PR is going in the direction to ensure that all sources which would `preventEndure` are marked as `HitResult.OTHER`).


I'm saying all this mainly to see if a simpler solution can be found, as it seems that introducing the `turnData.damageSources` was the very first action taken. Are there any strange edge cases that necessarily require the `turnData.damageSources` in order to be handled? For example, is it possible that `Pokemon.apply()` is called but somehow the mon dies from indirect damage before going to the `FaintPhase`?

File: src/field/pokemon.ts (hunk 1 above)
Comment (schmidtc1) [reply src/field/pokemon.ts:5370]: Updated to CONFUSION.

**Comment by schmidtc1** [comment]
> I'm saying all this mainly to see if a simpler solution can be found, as it seems that introducing the `turnData.damageSources` was the very first action taken. Are there any strange edge cases that necessarily require the `turnData.damageSources` in order to be handled? For example, is it possible that `Pokemon.apply()` is called but somehow the mon dies from indirect damage before going to the `FaintPhase`?

It was the first thing that came to mind for me. I figured it'd be easier to add the `HitResult` in the `damageAndUpdate` function rather than going to each individual call of `damageAndUpdate`. 

I don't think there are any edge cases requiring `turnData.damageSources`.

I think to prevent any significant overhaul to this PR, I would prefer to remove the `preventEndure` boolean from `damageAndUpdate` and `FaintPhase`. I don't like that we tie Reviver Seed's logic with `preventEndure`. Intuitively, I see a variable named `preventEndure` only applying to Endure. 

If you prefer to keep `preventEndure`, I'll work on that instead.

**Comment by Wlowscha** [comment]
> > I'm saying all this mainly to see if a simpler solution can be found, as it seems that introducing the `turnData.damageSources` was the very first action taken. Are there any strange edge cases that necessarily require the `turnData.damageSources` in order to be handled? For example, is it possible that `Pokemon.apply()` is called but somehow the mon dies from indirect damage before going to the `FaintPhase`?
> 
> It was the first thing that came to mind for me. I figured it'd be easier to add the `HitResult` in the `damageAndUpdate` function rather than going to each individual call of `damageAndUpdate`.
> 
> I don't think there are any edge cases requiring `turnData.damageSources`.
> 
> I think to prevent any significant overhaul to this PR, I would prefer to remove the `preventEndure` boolean from `damageAndUpdate` and `FaintPhase`. I don't like that we tie Reviver Seed's logic with `preventEndure`. Intuitively, I see a variable named `preventEndure` only applying to Endure.
> 
> If you prefer to keep `preventEndure`, I'll work on that instead.

Note that if you actually wanted to remove `preventEndure`, you would then have to go through all the `damageAndUpdate` calls to make sure that argument is not passed anymore :)
But this was actually part of my suggestion: with your changes to various things like weather and liquid ooze, you are ensuring that all calls which would need to pass `preventEndure = true` to `damageAndUpdate` are also passing `HitType.OTHER`. Since "other === indirect damage === prevents endure", the `preventEndure` argument can be discarded from `damageAndUpdate`.

However, you still need to pass `preventEndure` to `damage`, which then passes it on to `FaintPhase`. If the issue is with the naming, you can rename it to `activatesReviverSeed` when passing it to `FaintPhase`, or even rename those instances to `isIndirectDamage` for example.

It seems to me that we should avoid adding a new attribute to the Pokemon class to track information which is anyway passed directly from `damageAndUpdate` to `damage` to `FaintPhase`, if that attribute serves no other purpose. It's another story if tracking that information can become somehow useful elsewhere, but at the moment that doesn't seem the case. I understand not wanting to make big changes to the PR though, I'll leave it to the others to weigh in :)

**Comment by schmidtc1** [comment]
Refactored code based on suggestions by @Wlowscha 
Removed damageSources array in favor of sending an isIndirectDamage boolean to faintPhase and damage whenever HitResult.OTHER is encountered or no HitResult is supplied. Removed the preventEndure variable as a parameter in damageAndUpdate, it now only appears in FaintPhase.

**Review by SirzBenjie — DISMISSED** [review]
With @Wlowscha's suggestions integrated, this PR is very clean and lean. I like it.
Also you added good tests for it.

**Review by Wlowscha — DISMISSED** [review]

File: src/field/pokemon.ts [hunk 2]
```diff
@@ -3163,13 +3161,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
    * @param ignoreFaintPhase boolean to ignore adding a FaintPhase, passsed to damage()
    * @returns integer of damage done
    */
-  damageAndUpdate(damage: number, result?: DamageResult, critical: boolean = false, ignoreSegments: boolean = false, preventEndure: boolean = false, ignoreFaintPhase: boolean = false, source?: Pokemon): number {
+  damageAndUpdate(damage: number, result?: DamageResult, critical: boolean = false, ignoreSegments: boolean = false, ignoreFaintPhase: boolean = false, source?: Pokemon): number {
```
Comment (DayKev) [inline src/field/pokemon.ts:3164]: It's probably a good idea to change the optional parameters to be an object, ie:
```suggestion
  damageAndUpdate(damage: number,
    {
      result = HitResult.EFFECTIVE,
      critical = false,
      ignoreSegments = false,
      ignoreFaintPhase = false,
    }:
    {
      result?: DamageResult,
      critical?: boolean,
      ignoreSegments?: boolean,
      ignoreFaintPhase?: boolean,
      source?: Pokemon,
     }
  ): number {
```

**Review by DayKev — COMMENTED** [review]
Is `HitResult.INDIRECT_KO` only used for the damage number display and sfx?

**Comment by schmidtc1** [comment]
> Is `HitResult.INDIRECT_KO` only used for the damage number display and sfx?

Yes, this was discussed on discord. Perish song and destiny bond are unique KO moves that will not trigger reviver seed, but still have the KO sfx, so they were given the `INDIRECT_KO` hit result

File: src/field/pokemon.ts [hunk 3]
```diff
@@ -3163,13 +3161,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+    let isIndirectDamage: boolean = true;
+    if (result !== undefined) {
```
[the remark this answers is not in the document]
Comment (schmidtc1) [reply src/field/pokemon.ts]: Fixed in [b5bf976](https://github.com/pagefaultgames/pokerogue/pull/5182/commits/b5bf9766aab5bbebaaffe6461911cc8e538b568b)

File: src/field/pokemon.ts (hunk 2 above)
Comment (schmidtc1) [reply src/field/pokemon.ts]: Refactored in [855d795](https://github.com/pagefaultgames/pokerogue/pull/5182/commits/855d795f2d4774423ff6e19808c7d4ead0e11a97)

**Review by Wlowscha — APPROVED** [review]

File: src/field/pokemon.ts [hunk 4]
```diff
@@ -3175,13 +3173,21 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
    * @param ignoreFaintPhase boolean to ignore adding a FaintPhase, passsed to damage()
    * @returns integer of damage done
    */
-  damageAndUpdate(damage: number, result?: DamageResult, critical: boolean = false, ignoreSegments: boolean = false, preventEndure: boolean = false, ignoreFaintPhase: boolean = false, source?: Pokemon): number {
+  damageAndUpdate(damage: number,
```
Comment (DayKev) [inline src/field/pokemon.ts:3176]: You should rename `critical` to `isCritical`.

Also, don't forget to update the tsdocs for this function with the changes you've made.

File: src/data/battler-tags.ts [hunk 5]
```diff
@@ -723,7 +723,7 @@ export class DestinyBondTag extends BattlerTag {
         pokemonNameWithAffix2: getPokemonNameWithAffix(pokemon)
       })
     );
-    pokemon.damageAndUpdate(pokemon.hp, HitResult.ONE_HIT_KO, false, false, true);
+    pokemon.damageAndUpdate(pokemon.hp, { result: HitResult.INDIRECT_KO, ignoreSegments: true });
```
[the remark this answers is not in the document]
Comment (schmidtc1) [reply src/data/battler-tags.ts:726]: - You told me on [discord](https://discord.com/channels/1125469663833370665/1176874654015684739/1342284309117145170) that Reviver Seed will trigger in any case that endure will trigger. Endure would not trigger off of Destiny Bond or Perish Song, since Endure can only trigger off of [attacks](https://bulbapedia.bulbagarden.net/wiki/Endure_(move)#:~:text=Endure%20allows%20the%20user%20to%20survive%20any%20attack%20that%20would%20cause%20it%20to%20faint). Thus, Reviver Seed would not trigger off of Destiny Bond or Perish Song.
- I have been told to make [OHKO moves trigger Reviver Seed](https://discord.com/channels/1125469663833370665/1176874654015684739/1332821527787208777). 

Based on these two requirements, I created `HitResult.INDIRECT_KO`, since actual OHKO moves would function differently than Destiny Bond and Perish Song.

If you still want Destiny Bond and Perish Song to trigger Reviver Seed, then I will change it.

[the remark this answers is not in the document]
Comment (DayKev) [reply src/data/battler-tags.ts:726]: Oh I missed one use in `Pokemon.getAttackDamage()`, I thought you replaced them all. I guess it's fine then, not sure there's a clean way to do it... sigh, thanks gamefreak.

**Comment by schmidtc1** [comment]
@DayKev's suggestions resolved in [3dfeabe](https://github.com/pagefaultgames/pokerogue/pull/5182/commits/3dfeabe46a9aba1914fece40fa3d1e1284624955) and [de8efba](https://github.com/pagefaultgames/pokerogue/pull/5182/commits/de8efba9fef430506ba4178d70663f8112ba9520)

**Review by DayKev — APPROVED** [review]

**Comment by damocleas** [comment]
now has a conflict, assuming related to #5495

**Review by Wlowscha — APPROVED** [review]

**Review by DayKev — APPROVED** [review]
