### PR TITLE
[Bug] Fix level up evolution delay

### LINKED ISSUE #4039: [Bug] Pokémon level-up evolution is improperly delayed
## Describe the bug

Say you have Charmeleon being level 35 after the battle and you switch into the Rewards screen which offers a candy.
You choose it and give it to said Pokemon which puts it to level 36 which is the evolution to charizard level.
The Pokemon won’t evolve till the next battle though

## Expected behavior

The Pokemon should evolve after being given the candy.

## Screenshots / Videos

TBA

## Additional Context

image

image

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
Pokémon will now immediately evolve after leveling up, which will also prevent the bug causing evolutions to be rolled back when the player quits immediately after evolving their Pokémon.

## Why am I making these changes?
Fixes #4039 

## What are the changes from a developer perspective?
The code handling learning new moves and level up evolution is moved to a new `this.end()` function, which calls `super.end()` (which ultimately calls `scene.shiftPhase()`) at the appropriate time instead of in the middle of the phase before it's finished running.

### Screenshots/Videos

<details>
  <summary>Evolution Phase delayed until next wave (current behavior)</summary>

https://github.com/user-attachments/assets/49bf72c6-400e-49b1-acfb-3516ce807998

</details>
<details>
  <summary>Evolution Phase immediately after Level Up Phase (PR fix)</summary>

https://github.com/user-attachments/assets/0c90d3df-9efd-4632-8f5b-fce20e0e82bf

</details>

## How to test the changes?
Bring in a pokemon that evolves by level up (such as Squirtle) and use the following overrides:
```ts
const overrides = {
  STARTING_LEVEL_OVERRIDE: 50,
  ITEM_REWARD_OVERRIDE: [{ name: "RARER_CANDY" }]
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```
Beat the first wave and used the candy to force a level up, and check that the Pokémon evolves immediately instead of waiting until after the next encounter starts. Save and quit (or reload the page) after the start of the next encounter and reload the session, the Pokémon should still be evolved.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- ~[ ] Have I considered writing automated tests for the issue?~
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by innerthunder — APPROVED** [review]

File: src/phases/level-up-phase.ts [hunk 1]
```diff
@@ -1,59 +1,66 @@
...
+import { LearnMovePhase } from "#app/phases/learn-move-phase";
+import { PlayerPartyMemberPokemonPhase } from "#app/phases/player-party-member-pokemon-phase";
 import { LevelAchv } from "#app/system/achv";
+import { NumberHolder } from "#app/utils";
 import i18next from "i18next";
-import * as Utils from "#app/utils";
-import { PlayerPartyMemberPokemonPhase } from "./player-party-member-pokemon-phase";
-import { LearnMovePhase } from "./learn-move-phase";
 
 export class LevelUpPhase extends PlayerPartyMemberPokemonPhase {
```
Comment (Tempo-anon) [inline src/phases/level-up-phase.ts:12]: One day all the Phases will be properly documented 😔
