### PR TITLE
  [Bug]Chilly Reception Replaces Legendary Weather (Primordial Sea, Desolate Land, Delta Stream)

### LINKED ISSUE #5378: [Bug] Chilly Reception Replaces Legendary Weather (Primordial Sea, Desolate Land, Delta Stream)
### Describe the bug

On Usage, Chilly Reception replaces the weather (Harsh Sun, Heavy Rain, Heavy Winds) set by the Primal Weather Abilities.

### Reproduction

Use Chilly Reception while a Legendary weather is active.

### Expected behavior

Sandstorm and other weather-setting fails while Legendary Weather is active.

https://github.com/user-attachments/assets/da130bd1-6ab5-4bb3-be3c-67422135379d

> heavy rain causes the weather-modifying moves Sunny Day, Rain Dance, Sandstorm, and Hail to fail if used, and causes the Abilities Drought, Drizzle, Sand Stream, and Snow Warning to fail to activate.
-Bulba

Chilly Reception should still switch the Pokemon despite the weather not being able to be changed, unlike Parting Shot.

https://replay.pokemonshowdown.com/gen9customgame-2303972860

### Screenshots / Videos

Chilly and Delta Stream

https://github.com/user-attachments/assets/1f9b72da-4e64-424f-a94e-335593875389

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Mikhail-Shueb**
## What are the changes the user will see?
The move chilly reception will no longer replace legendary weather

## Why am I making these changes?
The move previously replaced legendary weather with snow, this in turn could end up worsening the user's experiece, as mensioned in issue #5378, linked bellow
https://github.com/pagefaultgames/pokerogue/issues/5378

"Fixes #5378"

## What are the changes from a developer perspective?
- Added a clause to the function trySetWeather that checks if the current weather is a legendary weather type and if so blocks any change that isn't a different legendary weather type or the NONE weather type;

- Added the function "getLegendaryWeatherContinuesMessage"
to get the correct message for the event(failed attempt to change legendary weather);

## Screenshots/Videos
Before the Fix:

https://github.com/user-attachments/assets/1f68bf21-a8ca-4dea-ab67-1b869712845f

After Fix:

https://github.com/user-attachments/assets/b877e23b-cf74-4ba6-ad31-0e081b5d66ac

## How to test the changes?
MOVESET_OVERRIDE: Moves.CHILLY_RECEPTION;
OPP_ABILITY_OVERRIDE: Abilities.DESOLATE_LAND;
IMPORTANT: have 2 pokemon in party;
## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [x] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [x] If so, please leave a link to it here: https://github.com/pagefaultgames/pokerogue-locales/pull/144
- [x] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

**Comment by Mikhail-Shueb** [comment]
> Please Provide evidence that you've tested your fix in-game.

will video evidence be enough?

**Comment by Mikhail-Shueb** [comment]
https://youtu.be/BkrZiUdAKvA @Snailman11 could not upload a video so I made a private youtube clip to show the fix working

**Comment by Mikhail-Shueb** [comment]
evidence of Fix in game has been added to the PR

**Comment by Mikhail-Shueb** [comment]
converted to draft to see if bugs are created as a result of the changes

**Comment by Mikhail-Shueb** [comment]
updated to have an exception for the NONE WeatherType o it always works

File: src/field/arena.ts [hunk 1]
```diff
@@ -274,6 +274,12 @@ export class Arena {
 
     const oldWeatherType = this.weather?.weatherType || WeatherType.NONE;
 
+    if (this.weather?.isImmutable() && (weather !== WeatherType.HARSH_SUN && weather !== WeatherType.HEAVY_RAIN && weather !== WeatherType.STRONG_WINDS && weather !== WeatherType.NONE)) {
```
Comment (DayKev) [inline src/field/arena.ts:277]:
```suggestion
    if (this.weather?.isImmutable() && (![ WeatherType.HARSH_SUN, WeatherType.HEAVY_RAIN, WeatherType.STRONG_WINDS, WeatherType.NONE ].contains(weather))) {
```

File: src/field/arena.ts [hunk 2]
```diff
@@ -274,6 +274,12 @@ export class Arena {
 
     const oldWeatherType = this.weather?.weatherType || WeatherType.NONE;
 
+    if (this.weather?.isImmutable() && (![ WeatherType.HARSH_SUN, WeatherType.HEAVY_RAIN, WeatherType.STRONG_WINDS, WeatherType.NONE ].includes(weather))) {
```
Comment (DayKev) [inline src/field/arena.ts:277]:
```suggestion
    if (this.weather?.isImmutable() && ![ WeatherType.HARSH_SUN, WeatherType.HEAVY_RAIN, WeatherType.STRONG_WINDS, WeatherType.NONE ].includes(weather)) {
```
Oops, forgot to remove the `()` in the last suggestion.

**Review by DayKev — DISMISSED** [review]

**Review by DayKev — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]

**Review by damocleas — APPROVED** [review]
