### PR TITLE
[Move] Fix multi-hit moves activating type-immunity abilities multiple times

### LINKED ISSUE #2123: [BUG] Water absorb activating on every multi-hit strike
**Describe the bug**
 Water absorb activating on every multi-hit strike

**Expected behavior**
Water absorb activating once

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/46976469/01407d25-c4a1-4745-b99a-8ffc07397f29

**Additional context**
https://bulbapedia.bulbagarden.net/wiki/Water_Absorb_(Ability)
"Multi-strike moves such as Water Shuriken, will only activate the Ability once."

### PR DESCRIPTION
**Pull request by zacharied**
## What are the changes?
Fix multi-hit moves (i.e. Bullet Seed, Water Shuriken) triggering type-immunity abilities more than once.

## Why am I doing these changes?
Fix #2123.

## What did change?
Refactor `MultiHitAttr` to check the type effectiveness of the attack before assigning the hit count. If the defender is immune to the attack, the attack only gets 1 hit. This check includes type immunity abilities, so the defender's type immunity ability only triggers once.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/6374275/b2ec02f9-42e9-4bc5-90ac-60279d95cf73

## How to test the changes?
The unit tests should handle it. For manual testing, consider the following overrides:

```ts
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.WATER_SHURIKEN];
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.WATER_ABSORB;
```

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

File: src/data/move.ts [hunk 1]
```diff
@@ -4661,8 +4697,8 @@ export class RandomMoveAttr extends OverrideMoveEffectAttr {
         : moveTargets.targets.indexOf(target.getBattlerIndex()) > -1
           ? [ target.getBattlerIndex() ]
           : [ moveTargets.targets[user.randSeedInt(moveTargets.targets.length)] ];
-      user.getMoveQueue().push({ move: moveId, targets: targets, ignorePP: true });
-      user.scene.unshiftPhase(new MovePhase(user.scene, user, targets, new PokemonMove(moveId, 0, 0, true), true));
+      user.getMoveQueue().push({ move: Moves.BULLET_SEED, targets: targets, ignorePP: true });
+      user.scene.unshiftPhase(new MovePhase(user.scene, user, targets, new PokemonMove(Moves.BULLET_SEED, 0, 0, true), true));
```
Comment (Tempo-anon) [inline src/data/move.ts:4701]: Hardcoded bullet seed here

**Review by Tempo-anon — CHANGES_REQUESTED** [review]
Looks mostly good but there's merge conflicts and also you left in some stuff from testing

File: src/data/move.ts (hunk 1 above)
Comment (zacharied) [reply src/data/move.ts]: crap, fixed.

**Comment by zacharied** [comment]
@Tempo-anon requested fixes have been made.

File: src/data/move.ts [hunk 2]
```diff
@@ -1549,49 +1557,77 @@ export class MultiHitAttr extends MoveAttr {
...
+      const hitType = new Utils.IntegerHolder(this.multiHitType);
+      applyMoveAttrs(ChangeMultiHitTypeAttr, user, target, move, hitType);
+      hitTimes = this.getHitCount(user, target);
+    }
+
+    (args[0] as Utils.IntegerHolder).value = hitTimes;
+    return true;
+  }
+
+  getTargetBenefitScore(user: Pokemon, target: Pokemon, move: Move): number {
```
[the remark this answers is not in the document]
Comment (Tempo-anon) [reply src/data/move.ts:1586]: I think it should be handled earlier since all multi hit moves are always attacks. That and you're keeping this the same -5 as before

**Review by Tempo-anon — APPROVED** [review]
