### PR TITLE
fix(encounter): HA chance for MEs will be calculated correctly

### LINKED ISSUE #7219: [Bug] BASE_HIDDEN_ABILITY_CHANCE is not correctly described
### Describe the bug

In rates.ts, chance is defined as x/65536 while rate is defined as 1/x. BASE_HIDDEN_ABILITY_CHANCE behaves as a rate and not a chance, since the hidden ability chance increases with lower values. The default value is 256 which is the same value using both formulas.

### Reproduction

Setting BASE_HIDDEN_ABILITY_CHANCE to 1 results in 100% Hidden ability chance.

### Expected behavior

Per the description, BASE_HIDDEN_ABILITY_CHANCE should be 100% when the value is 65536 and not 1.

### Screenshots / Videos

_No response_

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
Ability Charms will now increase the chance of ME Pokémon having their HA instead of decreasing it, as intended.

## Why am I making these changes?
Fixes #7219 

## What are the changes from a developer perspective?
Reworked `Pokemon#tryRerollHiddenAbilitySeed` to work the same as `Pokemon#generateAbilityIndex` wrt calculating HA chance.

## Checklist
- The PR content is correctly formatted:
  - [x] **I'm using `beta` as my base branch**
  - [x] **The current branch is not named `beta`, `main` or the name of another long-lived feature branch**
  - [x] I have provided a clear explanation of the changes within the PR description
  - [x] The PR title matches the Conventional Commits format (as described in [CONTRIBUTING.md](https://github.com/pagefaultgames/pokerogue/blob/beta/CONTRIBUTING.md#pr-title-format))
- [x] The PR is self-contained and cannot be split into smaller PRs
- [x] There is no overlap with another open PR

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -635,7 +636,7 @@ export abstract class Pokemon extends Phaser.GameObjects.Container {
 
   /** Generate `abilityIndex` based on species and hidden ability if not pre-defined. */
   private generateAbilityIndex(): number {
-    const hiddenAbilityChance = new NumberHolder(BASE_HIDDEN_ABILITY_CHANCE);
+    const hiddenAbilityChance = new NumberHolder(BASE_HIDDEN_ABILITY_RATE);
```
Comment (fabske0) [inline src/field/pokemon.ts]: Could you make this a ValueHolder

**Review by fabske0 — DISMISSED** [review]

File: src/field/pokemon.ts (hunk 1 above)
Comment (DayKev) [reply src/field/pokemon.ts]: Ah good point, might as well since the line is already being changed.

**Review by fabske0 — APPROVED** [review]

**Review by damocleas — APPROVED** [review]

**Review by SirzBenjie — APPROVED** [review]
