### PR TITLE
[Bug] Giratina no longer loses its' Hidden Ability going from Origin back to Altered Form

### LINKED ISSUE #5041: [Bug] Giratina Altered Forme has a HA, Origin Forme does not. This resets the HA if reverting forms.
### Describe the bug

When form changing to Giratina's Altered Forme from its Origin Forme, it will default your ability back to Pressure even if you started a run with HA Telepathy.

### Reproduction

Start a run with Giratina Altered Forme with the HA Telepathy selected.
Then form change into Giratina Origin Forme and back.

### Expected behavior

Giratina Altered Forme with HA Telepathy -> Giratina Origin Forme with Levitate -> Giratina Altered Forme with HA Telepathy

An easy fix would be if Giratina's Origin Forme would have Levitate listed as both the first ability and HA.

### Screenshots / Videos

Giratina_HA_Bug

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by damocleas**
## What are the changes the user will see?
Giratina swapping between Altered and Origin form with its' Hidden Ability Telepathy, will now properly gain it back when reverting from Origin form.

## Why am I making these changes?
Closes #5041 
## What are the changes from a developer perspective?
Hidden Ability for Origin Form Giratina

## How to test the changes?
Swap from Altered Giratina with Telepathy -> Origin then back.
## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes manually?
- [X] Are all unit tests still passing? (`npm run test`)
- [ ] Have I provided screenshots/videos of the changes (if applicable)?

### CODE REVIEW

**Review by Madmadness65 — APPROVED** [review]

File: src/data/pokemon-species.ts [hunk 1]
```diff
@@ -1844,7 +1844,7 @@ export function initSpecies() {
     new PokemonSpecies(Species.REGIGIGAS, 4, true, false, false, "Colossal Pokémon", Type.NORMAL, null, 3.7, 420, Abilities.SLOW_START, Abilities.NONE, Abilities.NORMALIZE, 670, 110, 160, 110, 80, 110, 100, 3, 0, 335, GrowthRate.SLOW, null, false),
     new PokemonSpecies(Species.GIRATINA, 4, false, true, false, "Renegade Pokémon", Type.GHOST, Type.DRAGON, 4.5, 750, Abilities.PRESSURE, Abilities.NONE, Abilities.TELEPATHY, 680, 150, 100, 120, 100, 120, 90, 3, 0, 340, GrowthRate.SLOW, null, false, true,
       new PokemonForm("Altered Forme", "altered", Type.GHOST, Type.DRAGON, 4.5, 750, Abilities.PRESSURE, Abilities.NONE, Abilities.TELEPATHY, 680, 150, 100, 120, 100, 120, 90, 3, 0, 340, false, null, true),
-      new PokemonForm("Origin Forme", "origin", Type.GHOST, Type.DRAGON, 6.9, 650, Abilities.LEVITATE, Abilities.NONE, Abilities.NONE, 680, 150, 120, 100, 120, 100, 90, 3, 0, 340),
+      new PokemonForm("Origin Forme", "origin", Type.GHOST, Type.DRAGON, 6.9, 650, Abilities.LEVITATE, Abilities.NONE, Abilities.LEVITATE, 680, 150, 120, 100, 120, 100, 90, 3, 0, 340),
```
Comment (SirzBenjie) [inline src/data/pokemon-species.ts:1847]: This seems like a hacky way to do it. In S/V, does the hidden levitate ability show as hidden while in origin form? I suppose it doesn't matter if we just set Giratnia's hidden ability to be Levitate, as it doesn't have a hidden otherwise anyway.

Regardless, I can't approve this without at least video evidence or, more preferable, an automated test for it.

**Review by SirzBenjie — CHANGES_REQUESTED** [review]

**Review by Wlowscha — APPROVED** [review]
