### PR TITLE
[Bug] Sand Spit should only activate when hit with a damaging move

### LINKED ISSUE #3336: [Bug] Sand Spit Activates on Status Moves and Self Status Moves
### Describe the bug

Taken From Discord (Game Crash on using Roar vs Sand Spit) https://discord.com/channels/1125469663833370665/1267274089027076097

Title, this also causes a crash when roar is used. (Probably related to (Dragon tail crashes game) https://discord.com/channels/1125469663833370665/1267083547882164326)

Sand Spit is inappropriately activated when:

-Selecting a self stat-boosting move (minimize, coil, etc.)
-Hit by a status move

### User data export file

_No response_

### Session export file

_No response_

### Expected behavior

(Bulbapedia.net) Sand Spit summons a sandstorm in battle for five turns when a Pokémon with Sand Spit is hit by a damaging move

### Screenshots / Videos

_No response_

### What OS did you observe the bug on?

PC/Windows

### If other please specify

_No response_

### Which browser do you use?

Edge

### If other please specify

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes?
Sand Spit will only activate when hit with a damaging move.

## Why am I doing these changes?
Fixes #3336
cf https://bulbapedia.bulbagarden.net/wiki/Sand_Spit_(Ability)

## What did change?
An optional condition parameter was added to `PostDefendWeatherChangeAbAttr` which is used by Sand Spit to ignore status moves (though currently Sand Spit is the only ability to use that abattr anyway).

## How to test the changes?
Start a run with Silicobra with Sand Spit, and get hit by various moves.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

### CODE REVIEW

File: src/data/ability.ts [hunk 1]
```diff
@@ -941,14 +941,19 @@ export class PostDefendPerishSongAbAttr extends PostDefendAbAttr {
...
-  constructor(weatherType: WeatherType) {
+  constructor(weatherType: WeatherType, condition?: PokemonDefendCondition) {
     super();
 
     this.weatherType = weatherType;
+    this.condition = condition ?? null;
   }
 
   applyPostDefend(pokemon: Pokemon, passive: boolean, attacker: Pokemon, move: Move, hitResult: HitResult, args: any[]): boolean {
+    if (this.condition !== null && !this.condition(pokemon, attacker, move)) {
```
Comment (torranx) [inline src/data/ability.ts:954]: correct me if I'm wrong but if `this.condition` is `null`, it should proceed?

Comment (DayKev) [reply src/data/ability.ts:954]: Yeah, if it's null that means there's no condition to stop the ability from continuing.

**Comment by Tempo-anon** [comment]
Unit test? 👉 👈

**Comment by DustinLin** [comment]
looks good!
