### PR TITLE
[i18n] [Beta] Fix arena tag message typos

### LINKED ISSUE #6642: [Bug] Beta Locales Broken for Light Screen / Reflect removal
### Describe the bug

Title

### Reproduction

Use Light Screen / Reflect and wait for it to expire

### Expected behavior

Show the correct message

### Screenshots / Videos

Image

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fabske0**
## What are the changes the user will see?

Arena tag messages will not show the locales key anymore

## Why am I making these changes?

partialy Fixes #6642

## What are the changes from a developer perspective?

- Fixed 2 typos where the `add` key was used for the `remove` message.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`pnpm test:silent`)
  ~~- [ ] Have I created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes?~~
- [ ] Have I provided screenshots/videos of the changes (if applicable)?
  ~~- [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?~~

### CODE REVIEW

File: src/data/arena-tag.ts [hunk 1]
```diff
@@ -194,12 +194,19 @@ export abstract class ArenaTag implements BaseArenaTag {
...
         pokemonNameWithAffix: getPokemonNameWithAffix(this.getSourcePokemon()),
         moveName: this.getMoveName(),
-      }),
-    );
+      });
+    } else {
+      message = i18next.t("arenaTag:arenaOnRemove" + this.i18nSideKey, {
+        moveName: this.getMoveName(),
+      });
+    }
```
Comment (Bertie690) [inline src/data/arena-tag.ts]:
```suggestion

    const message = i18next.t(key, {
      pokemonNameWithAffix: getPokemonNameWithAffix(this.getSourcePokemon()),
      moveName: this.getMoveName(),
    });
```

File: src/data/arena-tag.ts [hunk 2]
```diff
@@ -194,12 +194,19 @@ export abstract class ArenaTag implements BaseArenaTag {
...
     }
 
-    globalScene.phaseManager.queueMessage(
-      i18next.t(this.onRemoveMessageKey, {
+    // TODO: potentially remove fallback when all messages are implemented
+    let message = "";
+    if (i18next.exists(this.onRemoveMessageKey)) {
+      message = i18next.t(this.onRemoveMessageKey, {
         pokemonNameWithAffix: getPokemonNameWithAffix(this.getSourcePokemon()),
         moveName: this.getMoveName(),
```
Comment (Bertie690) [inline src/data/arena-tag.ts]:
```suggestion
    // TODO: potentially remove fallback when all messages are implemented
    const key: string = i18n.exists(this.onRemoveMessageKey)
      ? this.onRemoveMessageKey
      : "arenaTag:arenaOnRemove" + this.i18nSideKey;
```

File: test/arena/arena-tags.test.ts [hunk 3]
```diff
@@ -89,12 +89,15 @@ describe("Arena Tags", () => {
...
-        );
+        const expectedMessage = i18next.exists(tag["onRemoveMessageKey"])
+          ? i18next.t(tag["onRemoveMessageKey"], {
+              pokemonNameWithAffix: getPokemonNameWithAffix(tag["getSourcePokemon"]()),
+              moveName: tag["getMoveName"](),
+            })
+          : i18next.t("arenaTag:arenaOnRemove" + tag["i18nSideKey"], {
+              moveName: tag["getMoveName"](),
+            });
+        expect(game.textInterceptor.logs).toContain(expectedMessage);
```
Comment (Bertie690) [inline test/arena/arena-tags.test.ts]:
```suggestion

        expect(game).toHaveShownMessage(expectedMessage);
```

File: test/arena/arena-tags.test.ts [hunk 4]
```diff
@@ -89,12 +89,15 @@ describe("Arena Tags", () => {
...
-            moveName: tag["getMoveName"](),
-          }),
-        );
+        const expectedMessage = i18next.exists(tag["onRemoveMessageKey"])
+          ? i18next.t(tag["onRemoveMessageKey"], {
+              pokemonNameWithAffix: getPokemonNameWithAffix(tag["getSourcePokemon"]()),
+              moveName: tag["getMoveName"](),
+            })
+          : i18next.t("arenaTag:arenaOnRemove" + tag["i18nSideKey"], {
+              moveName: tag["getMoveName"](),
```
Comment (Bertie690) [inline test/arena/arena-tags.test.ts]:
```suggestion
              pokemonNameWithAffix: getPokemonNameWithAffix(tag["getSourcePokemon"]()),
              moveName: tag["getMoveName"](),
```

File: test/moves/mat-block.test.ts [hunk 5]
```diff
@@ -50,7 +50,7 @@ describe("Moves - Mat Block", () => {
 
     leadPokemon.forEach(p => expect(p.hp).toBe(p.getMaxHp()));
     expect(game.textInterceptor.logs).toContain(
```
Comment (Bertie690) [inline test/moves/mat-block.test.ts:52]:
```suggestion
    expect(game).toHaveShownMessage(
```

**Review by Bertie690 — APPROVED** [review]

File: test/arena/arena-tags.test.ts [hunk 6]
```diff
@@ -89,12 +89,15 @@ describe("Arena Tags", () => {
       game.scene.arena.removeTagOnSide(tagType, side, false);
       if (tag["onRemoveMessageKey"]) {
         // TODO: Convert to `game.toHaveShownMessage`
```
Comment (DayKev) [inline test/arena/arena-tags.test.ts:91]:
```suggestion
```
Goes with matt's suggestions.
