### PR TITLE
[BUG] fixes #5472 - transform on reload

### LINKED ISSUE #5472: [Bug] Transform and Imposter Lose Transformed Pokemon on Reload
### Describe the bug

Upon Reloading into a run where a Pokemon has used Transform or Imposter to transform into a Pokemon, the User's Species will be its original Species and not the previously-transformed-into Species.
- Typing of the Transformed Species is preserved.

Link to Discord's Bug Report (Form not saved when restarting session)
https://discord.com/channels/1125469663833370665/1267976989957029900

### Reproduction

Use Transform or activate Imposter. Progress the wave, then reload the run.

```
	ABILITY_OVERRIDE: Abilities.IMPOSTER,
```

### Expected behavior

The Pokemon that the User of Imposter or Transform transformed into should persist upon reloading or saving and quitting.

### Screenshots / Videos

https://github.com/user-attachments/assets/5c45522d-d9d2-443b-9411-306c982dbb5e

<details><summary>Images</summary>

Image

Image

Image

</details>

### Session export file

_No response_

### User data export file

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zeserrado-marques**
## What are the changes the user will see?

Transformed pokémon, either via transform move or imposter ability now persists after reloading
## Why am I making these changes?

To make sure any status changes on player pokémon during wild waves are consistent with the game roguelite behavior during wild battle waves. This Fixes #5472

## What are the changes from a developer perspective?

I changed 3 src files, `pokemon-data.ts`, `pokemon.ts` and `summon-phase.ts`. 
##### pokemon-data.ts
- when create a `pokemonData` object, it also copies the `speciesFrom` from the source pokemon object
- when creating a pokemon with `toPokemon()`, if there was a `speciesFrom`, runs `getPokemonSpecies(this.summonData.speciesForm.speciesId)`. This ensures that, once the JSON from the server was parsed, we create the `species` object again.

##### pokemon.ts
- on `resetSummonData()` now uses `Object.keys(this.summonDataPrimer)` to copy all attributes from the primer into `summonData` attribute. This way, `Object.keys()` is able to fetch all attributes that the primer has. For example, in the previous version, since we create a new `summonData` object in this method, and the `moveset` attribute can be null, I think `Object.Keys()` was missing it, hence the moveset of the transformed pokemon was not copied back.

##### summon-phase.ts
- if there was a `speciesForm` in the `summonData` after `resetSummonData()`, then we need to reload the assets of pokemon, to load the previously copied sprite. 

## Screenshots/Videos

https://github.com/user-attachments/assets/d529ae34-eac3-481e-8947-92a68ab92a63

## How to test the changes?

On the overrides.ts file, insert these lines

```
  ABILITY_OVERRIDE: Abilities.IMPOSTER,

  STARTING_LEVEL_OVERRIDE: 20,
```
level 20 is to ensure you survive until the next wave. 

- New game
- select any pokemon as starter
- select a save slot
- win wave 1
- on wave 2, Save and Quit
- reload session on chosen save slot
- voilá, pokemon stayed transformed

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [ ] If so, please leave a link to it here: 
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

**Comment by zeserrado-marques** [comment]
I fixed it. I also added a test to check for form index 

https://github.com/user-attachments/assets/c81321b9-ff37-40d8-9b59-98142435d707

File: src/system/pokemon-data.ts [hunk 1]
```diff
@@ -63,6 +64,7 @@ export default class PokemonData {
   public bossSegments?: number;
 
   public summonData: PokemonSummonData;
+  public summonDataSpeciesFormIndex: number;
```
Comment (DayKev) [inline src/system/pokemon-data.ts:67]: Does this need to be a separate field? Why can't you just grab `summonData.speciesForm.formIndex` directly?

Comment (zeserrado-marques) [reply src/system/pokemon-data.ts:67]: From what I gathered, when the JSON is parsed, `summonData.speciesForm` is not an object, but only a "dictionary". So when the `source` argument in `pokemonData` constructor was not a pokemon object, there was no method `formIndex` to get the form index back. Since i did not want to change the attribute `_formIndex` visibility, I saved the `formIndex` inside `pokemonData`

Comment (zeserrado-marques) [reply src/system/pokemon-data.ts:67]: This was the warning i did got, and didn't want to break it
<details>
<summary>Warning when accessing protected attribute</summary>
img
</details>

Comment (DayKev) [reply src/system/pokemon-data.ts:67]: Sorry I forgot to take a look earlier; anyway, there's a public getter/setter for `formIndex`:
https://github.com/pagefaultgames/pokerogue/blob/4b8f1df8cd4bc98b985f05931befa11183e0443d/src/data/pokemon-species.ts#L249-L255
Which means you can use `summonData.formIndex` without issues.

Comment (zeserrado-marques) [reply src/system/pokemon-data.ts:67]: That was the first thing I tried. If I try to use that, this happens

<details><summary>Sprite not loaded</summary>
<p>

image


</p>
</details> 

This is because, I assume, the `summonData.speciesForm` object is not fully reconstructed as `SpeciesForm` when it's loaded from the server. So, there is no `formIndex` method on `summonData.speciesForm` 

<details><summary>no form index method</summary>
<p>

image


</p>
</details> 

hence, inside `getPokemonSpeciesFrom` , the `formIndex` is undefined

<details><summary>no form index</summary>
<p>

image


</p>
</details> 

And, after the `getPokemonSpeciesFrom` runs, it has `formIndex  = 0`

<details><summary>Wrong form index invoked </summary>
<p>


image


</p>
</details> 

That is why I needed the extra attribute, to ensure i keep the form index after loading from the server.

Comment (DayKev) [reply src/system/pokemon-data.ts:67]: Ah, alright, that probably means the savedata should be re-examined later (separate from this PR).

**Review by DayKev — DISMISSED** [review]

File: src/phases/summon-phase.ts [hunk 2]
```diff
@@ -195,6 +195,10 @@ export class SummonPhase extends PartyMemberPokemonPhase {
                 pokemon.cry(pokemon.getHpRatio() > 0.25 ? undefined : { rate: 0.85 });
                 pokemon.getSprite().clearTint();
                 pokemon.resetSummonData();
+                // necessary to stay transformed during wild waves
+                if (pokemon.summonData?.speciesForm) {
+                  pokemon.loadAssets();
```
Comment (DayKev) [inline src/phases/summon-phase.ts:200]:
```suggestion
                  pokemon.loadAssets(false);
```
This should fix the sprite loading issues I believe.

Comment (zeserrado-marques) [reply src/phases/summon-phase.ts]: Yes, I'll make those changes

**Review by DayKev — APPROVED** [review]

**Review by emdeann — APPROVED** [review]
