### PR TITLE
[Bug] Stat Stages are now changed individually instead of all at once

### LINKED ISSUE #4281: [Bug] When Multiple Stats are Lowered by a Single Move, Defiant and Competitive raise ATK/SPATK Once
### Describe the bug

 When hit by a move that lowers multiple stats; instead of raising Attack or Special Attack for every stat lowered, Competitive and Defiant only raise stats once

Moves that lower multiple stats at once include:
 Tickle, Noble Roar. Parting Shot, Memento

Discord Bug Report ([Bug] Minor Interaction between Competitive and Parting Shot)
https://discord.com/channels/1125469663833370665/1285127111362871296

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

https://replay.pokemonshowdown.com/gen9customgame-2202651716-acnkm7dp2bzc30c1wyqh2zljvd0vcpjpw

> If multiple stats are lowered (such as by Memento or Venom Drench), Defiant activates for each stat lowered.
-Bulba

### Screenshots / Videos

Tickle against Competitive Bulba

https://github.com/user-attachments/assets/4de41351-ad2e-4a0c-8307-6f0225cb3556

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

No

### PR DESCRIPTION
**Pull request by PrabbyDD**
## What are the changes the user will see?
Defiant and Competitive will now properly interact with moves that modify multiple stats stages.

## Why am I making these changes?
Fixes #4281 

## What are the changes from a developer perspective?
If multiple stats are being changed in `StatStageChangePhase`, a new SSCPhase is created for each individual stat and then the current SSCPhase is ended.

### Screenshots/Videos

https://github.com/user-attachments/assets/c0723f2a-8cbc-49a8-9fec-c6559f84aeae

## How to test the changes?
Override file, or the test file made

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

File: src/phases/move-effect-phase.ts [hunk 1]
```diff
@@ -272,7 +272,6 @@ export class MoveEffectPhase extends PokemonPhase {
                           if (move.hitsSubstitute(user, target)) {
                             return resolve();
                           }
-
```
Comment (DayKev) [inline src/phases/move-effect-phase.ts:275]: You accidentally left in a spacing change.

**Review by DayKev — COMMENTED** [review]
It seems like the reason this bug exists is because we combine stat changes into a single SSCPhase which is different from mainline where each stat change is handled individually. It speeds things up but apparently also causes bugs. It might be better to instead have the SSCPhase check if it's changing multiple stats at once, and to unshift a new SSCPhase for each stat and end the current SSCPhase after doing so.

File: src/phases/stat-stage-change-phase.ts [hunk 2]
```diff
@@ -106,7 +106,15 @@ export class StatStageChangePhase extends PokemonPhase {
         }
       }
 
-      applyPostStatStageChangeAbAttrs(PostStatStageChangeAbAttr, pokemon, filteredStats, this.stages, this.selfTarget);
+      // If a pokemon has defiant or competitive which activates for each stat lowered, loop over each stat lowered
+      const defiantOrCompetitive = pokemon.getAbilityAttrs(PostStatStageChangeStatStageChangeAbAttr);
+      if (defiantOrCompetitive?.length > 0) {
+        for (let _ = 0; _ < filteredStats.length; _++) {
```
Comment (torranx) [inline src/phases/stat-stage-change-phase.ts:112]: not a fan of the variable name `_`

**Comment by PrabbyDD** [comment]
> It seems like the reason this bug exists is because we combine stat changes into a single SSCPhase which is different from mainline where each stat change is handled individually. It speeds things up but apparently also causes bugs. It might be better to instead have the SSCPhase check if it's changing multiple stats at once, and to unshift a new SSCPhase for each stat and end the current SSCPhase after doing so.

This is what I was thinking originally but I wasnt sure where to start when trying to implement this - I figured the solution I committed would be simpler and easier to understand. Where do I start when trying to add multiple SSCPhases? Also should I be hard coding it in for specifically defiant and competitive?

File: src/test/abilities/competitive.test.ts [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+    game.override.battleType("single")
+      .enemySpecies(Species.RATTATA)
+      .enemyMoveset(Moves.TICKLE)
+      .startingLevel(100)
+      .moveset(Moves.SPLASH)
+      .ability(Abilities.COMPETITIVE);
+  });
+
+  it("lower atk and def by 1 via tickle, then increase spatk by 4 via competitive", async () => {
```
Comment (torranx) [inline src/test/abilities/competitive.test.ts:35]: when writing tests, it's ideal to include the cases from the [ability's description](https://bulbapedia.bulbagarden.net/wiki/Competitive_(Ability)), tests for cases like this is just a bonus

**Review by torranx — COMMENTED** [review]
I'd like to see Defiant test cases as well

**Comment by DayKev** [comment]
> > It seems like the reason this bug exists is because we combine stat changes into a single SSCPhase which is different from mainline where each stat change is handled individually. It speeds things up but apparently also causes bugs. It might be better to instead have the SSCPhase check if it's changing multiple stats at once, and to unshift a new SSCPhase for each stat and end the current SSCPhase after doing so.
> 
> This is what I was thinking originally but I wasnt sure where to start when trying to implement this - I figured the solution I committed would be simpler and easier to understand. Where do I start when trying to add multiple SSCPhases? Also should I be hard coding it in for specifically defiant and competitive?

At the beginning of the SSCPhase's `start()` function, check if more than one different stat is being changed, and if so make a loop that passes each stat (plus the other constructor fields) to a new SSCPhase via `unshiftPhase(new SSCPhase(...))`. Then after the loop completes (if it was run) the current SSCPhase is ended via `this.end(); return;`. Something like this (more might be necessary, haven't tested this):

```ts
  start() {
    if (this.stats.length > 1) {
      for (let i = 0; i < this.stats.length; i++) {
        const stat = [this.stats[i]];
        this.scene.unshiftPhase(new StatStageChangePhase(this.scene, this.battlerIndex, this.selfTarget, stat, this.stages, this.showMessage, this.ignoreAbilities, this.canBeCopied, this.onChange));
      }
      return this.end();
    }
```

File: src/phases/stat-stage-change-phase.ts (hunk 2 above)
Comment (PrabbyDD) [reply src/phases/stat-stage-change-phase.ts:112]: it was unused so I just decided to make it _. Should I name unused variables something else?

Comment (torranx) [reply src/phases/stat-stage-change-phase.ts:112]: ahh didn't notice it being unused, would `forEach` or `map` then be better to use?

Comment (PrabbyDD) [reply src/phases/stat-stage-change-phase.ts]: there will still be an unused variable in there, and using _ didnt trigger the linter, so I figured it would be cleaner, but I guess it doesnt matter now because I removed this loop.

**Review by DayKev — DISMISSED** [review]

**Comment by DayKev** [comment]
Updated the OP with the changes.

File: src/test/abilities/competitive.test.ts [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+
+    const playerPokemon = game.scene.getPlayerPokemon()!;
+    game.move.select(Moves.CLOSE_COMBAT);
+    await game.phaseInterceptor.to(TurnInitPhase);
+
+    expect(playerPokemon.getStatStage(Stat.SPDEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.DEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.SPATK)).toBe(0);
+  });
+  it("white herb should remove only the negative effects", async () => {
```
Comment (torranx) [inline src/test/abilities/competitive.test.ts:59]: very very small nit
```suggestion
  });
  
  it("white herb should remove only the negative effects", async () => {
```

File: src/test/abilities/defiant.test.ts [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+
+    const playerPokemon = game.scene.getPlayerPokemon()!;
+    game.move.select(Moves.CLOSE_COMBAT);
+    await game.phaseInterceptor.to(TurnInitPhase);
+
+    expect(playerPokemon.getStatStage(Stat.SPDEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.DEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.ATK)).toBe(0);
+  });
+  it("white herb should remove only the negative effects", async () => {
```
Comment (torranx) [inline src/test/abilities/defiant.test.ts:58]: very very small nit
```suggestion
  });
  
  it("white herb should remove only the negative effects", async () => {
```

File: src/phases/stat-stage-change-phase.ts [hunk 6]
```diff
@@ -36,6 +36,16 @@ export class StatStageChangePhase extends PokemonPhase {
...
   start() {
+
+    // Check if multiple stats are being changed at the same time, then run SSCPhase for each of them
+    if (this.stats.length > 1) {
+      for (let i = 0; i < this.stats.length; i++) {
+        const stat = [this.stats[i]];
+        this.scene.unshiftPhase(new StatStageChangePhase(this.scene, this.battlerIndex, this.selfTarget, stat, this.stages, this.showMessage, this.ignoreAbilities, this.canBeCopied, this.onChange));
+      }
+      return this.end();
+    }
```
Comment (torranx) [inline src/phases/stat-stage-change-phase.ts:47]: question, is it intended that it "bypasses" the existing if-conditions inside this function?

Comment (DayKev) [reply src/phases/stat-stage-change-phase.ts:47]: I suppose it's technically more efficient to do the `isActive` check first.

File: src/phases/stat-stage-change-phase.ts [hunk 7]
```diff
@@ -36,6 +36,16 @@ export class StatStageChangePhase extends PokemonPhase {
   }
 
   start() {
+
+    // Check if multiple stats are being changed at the same time, then run SSCPhase for each of them
+    if (this.stats.length > 1) {
+      for (let i = 0; i < this.stats.length; i++) {
+        const stat = [this.stats[i]];
```
Comment (DayKev) [inline src/phases/stat-stage-change-phase.ts:43]:
```suggestion
        const stat = [ this.stats[i] ];
```

File: src/test/abilities/competitive.test.ts [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+  });
+
+  beforeEach(() => {
+    game = new GameManager(phaserGame);
+
+    game.override.battleType("single")
+      .enemySpecies(Species.BEEDRILL)
+      .enemyMoveset(Moves.TICKLE)
+      .startingLevel(1)
+      .moveset([Moves.SPLASH, Moves.CLOSE_COMBAT])
```
Comment (DayKev) [inline src/test/abilities/competitive.test.ts:31]:
```suggestion
      .moveset([ Moves.SPLASH, Moves.CLOSE_COMBAT ])
```

File: src/test/abilities/competitive.test.ts [hunk 9]
```diff
@@ -0,0 +1,71 @@
...
+    const playerPokemon = game.scene.getPlayerPokemon()!;
+    game.move.select(Moves.CLOSE_COMBAT);
+    await game.phaseInterceptor.to(TurnInitPhase);
+
+    expect(playerPokemon.getStatStage(Stat.SPDEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.DEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.SPATK)).toBe(0);
+  });
+  it("white herb should remove only the negative effects", async () => {
+    game.override.startingHeldItems([{ name: "WHITE_HERB"}]);
```
Comment (DayKev) [inline src/test/abilities/competitive.test.ts:60]:
```suggestion
    game.override.startingHeldItems([{ name: "WHITE_HERB" }]);
```

File: src/test/abilities/defiant.test.ts [hunk 10]
```diff
@@ -0,0 +1,69 @@
...
+  });
+
+  beforeEach(() => {
+    game = new GameManager(phaserGame);
+
+    game.override.battleType("single")
+      .enemySpecies(Species.BEEDRILL)
+      .enemyMoveset(Moves.TICKLE)
+      .startingLevel(1)
+      .moveset([Moves.SPLASH, Moves.CLOSE_COMBAT])
```
Comment (DayKev) [inline src/test/abilities/defiant.test.ts:31]:
```suggestion
      .moveset([ Moves.SPLASH, Moves.CLOSE_COMBAT ])
```

File: src/test/abilities/defiant.test.ts [hunk 11]
```diff
@@ -0,0 +1,69 @@
...
+    const playerPokemon = game.scene.getPlayerPokemon()!;
+    game.move.select(Moves.CLOSE_COMBAT);
+    await game.phaseInterceptor.to(TurnInitPhase);
+
+    expect(playerPokemon.getStatStage(Stat.SPDEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.DEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.ATK)).toBe(0);
+  });
+  it("white herb should remove only the negative effects", async () => {
+    game.override.startingHeldItems([{ name: "WHITE_HERB"}]);
```
Comment (DayKev) [inline src/test/abilities/defiant.test.ts:59]:
```suggestion
    game.override.startingHeldItems([{ name: "WHITE_HERB" }]);
```

File: src/test/abilities/competitive.test.ts [hunk 12]
```diff
@@ -0,0 +1,72 @@
...
+    const playerPokemon = game.scene.getPlayerPokemon()!;
+    game.move.select(Moves.CLOSE_COMBAT);
+    await game.phaseInterceptor.to(TurnInitPhase);
+
+    expect(playerPokemon.getStatStage(Stat.SPDEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.DEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.SPATK)).toBe(0);
+  });
+  
+  it("white herb should remove only the negative effects", async () => {
```
Comment (DayKev) [inline src/test/abilities/competitive.test.ts:60]:
```suggestion
  });

  it("white herb should remove only the negative effects", async () => {
```

File: src/test/abilities/defiant.test.ts [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+    const playerPokemon = game.scene.getPlayerPokemon()!;
+    game.move.select(Moves.CLOSE_COMBAT);
+    await game.phaseInterceptor.to(TurnInitPhase);
+
+    expect(playerPokemon.getStatStage(Stat.SPDEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.DEF)).toBe(-1);
+    expect(playerPokemon.getStatStage(Stat.ATK)).toBe(0);
+  });
+  
+  it("white herb should remove only the negative effects", async () => {
```
Comment (DayKev) [inline src/test/abilities/defiant.test.ts:59]:
```suggestion
  });

  it("white herb should remove only the negative effects", async () => {
```

**Review by DayKev — APPROVED** [review]

**Review by torranx — APPROVED** [review]

**Review by xsn34kzx — APPROVED** [review]
