### PR TITLE
[BUG] Fix broken forms of Pichu starter

### LINKED ISSUE #5500: [Bug] Black Screen when placing cursor on Pichu
### Describe the bug

On starting a new game when selecting the team, if I move the cursor on Pichu the game instantly black screen et doesn't answer any contror, only music is still played

### Reproduction

Have Pichu
Start new game
Move cursor on Pichu
Black screen

### Expected behavior

Well, to show Pichu stats and things you know

### Screenshots / Videos

https://youtu.be/Elm0Lo_Mx6A

### Session export file

_No response_

### User data export file

_No response_

### Additional context

I'm pretty sure that's irrelevant but the more you press escape the louder the key press sound gets

### PR DESCRIPTION
**Pull request by Wlowscha**
## Why am I making these changes? / What are the changes from a developer perspective?
When a player catches a Pikachu form, the game unlocks the same form for Pichu. This leads to bugs in some cases---for example if a player only catches Cute Cosplay Pikachu, the game will be convinced that form #5 of Pichu is unlocked, which causes issues in Starter Select (for example, when trying to select mons for a monotype challenge) and in the Pokédex (throwing an error when trying to select Pichu).

The solution comes into part. First: introduce an edge case in `setPokemonSpeciesCaught` so that, if a Pikachu form is caught, form 0 of Pichu is the one and only unlocked.

Second: introduce a migrator that checks only the Pichu save data, removes any forms which are not 0 or 1, then unlocks form 0 if it was not already unlocked. All of this, naturally, only if Pichu is already caught.

This also requires a version change to 1.8.3.

Fixes #5500 

## Screenshots/Videos
<details><summary>Screenshot from a previously broken save, after the migrator has taken effect</summary>
<p>

pichu_free

</p>
</details> 
<details><summary>Catching Cute Cosplay Pikachu now unlockes the default form of Pichu</summary>
<p>

https://github.com/user-attachments/assets/3c26a660-6f8b-4c08-b497-689e0747590b

</p>
</details> 

## How to test the changes?

For the Pichu catching, these overrides:
```ts
const overrides = {
  OPP_SPECIES_OVERRIDE: Species.PIKACHU,
  OPP_FORM_OVERRIDES: {[Species.PIKACHU]: 5},
  POKEBALL_OVERRIDE: {
    active: true,
    pokeballs: {
      [PokeballType.POKEBALL]: 0,
      [PokeballType.GREAT_BALL]: 0,
      [PokeballType.ULTRA_BALL]: 0,
      [PokeballType.ROGUE_BALL]: 0,
      [PokeballType.MASTER_BALL]: 99,
    },
  }  
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

For the migrator, that's a bit more tricky, need to load a file pre 1.8.3 with only one cosplay pikachu form caught. One can be found [in the links in this thread](https://discord.com/channels/1125469663833370665/1356624026679640176).

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

### CODE REVIEW

**Review by damocleas — DISMISSED** [review]

File: src/system/version_migration/version_converter.ts [hunk 1]
```diff
@@ -204,6 +219,12 @@ class SettingsVersionConverter extends VersionConverter {
         console.log("Applying v1.7.0 settings data migration!");
         this.callMigrators(data, v1_7_0.settingsMigrators);
       }
+      if (curMinor === 8) {
+        if (curPatch <= 2) {
+          console.log("Applying v1.8.3 session data migration!");
+          this.callMigrators(data, v1_8_3.settingsMigrators);
+        }
+      }
```
Comment (DayKev) [inline src/system/version_migration/version_converter.ts:227]:
```suggestion
```

File: src/system/version_migration/version_converter.ts [hunk 2]
```diff
@@ -144,6 +147,12 @@ class SessionVersionConverter extends VersionConverter {
         console.log("Applying v1.7.0 session data migration!");
         this.callMigrators(data, v1_7_0.sessionMigrators);
       }
+      if (curMinor === 8) {
+        if (curPatch <= 2) {
+          console.log("Applying v1.8.3 session data migration!");
+          this.callMigrators(data, v1_8_3.sessionMigrators);
+        }
+      }
```
Comment (DayKev) [inline src/system/version_migration/version_converter.ts:155]:
```suggestion
```

**Review by DayKev — COMMENTED** [review]
You don't need to add the checks for migrators that don't exist.

File: src/system/version_migration/version_converter.ts [hunk 3]
```diff
@@ -174,6 +177,12 @@ class SystemVersionConverter extends VersionConverter {
         console.log("Applying v1.7.0 system data migration!");
         this.callMigrators(data, v1_7_0.systemMigrators);
       }
+      if (curMinor === 8) {
+        if (curPatch <= 2) {
+          console.log("Applying v1.8.3 session data migration!");
```
Comment (DayKev) [inline src/system/version_migration/version_converter.ts:182]:
```suggestion
          console.log("Applying v1.8.3 system data migration!");
```

**Review by DayKev — APPROVED** [review]

**Review by damocleas — APPROVED** [review]
