### PR TITLE
[Bug] Fix Beat Up dealing NaN damage with Multi-Lens

### LINKED ISSUE #2767: [BUG] Beat Up deals no damage with the additional hits from Multi-Lens
**Describe the bug**

When using Beat Up on a Pokemon with Multi-Lens, the additional hits created by Multi-Lens deal no damage.

Using Beat Up with Multi-Lens in a unit test shows that Beat Up deals "NaN" damage on the additional hits.

image

**To Reproduce**

Session Data: 
[sessionData1_innerthunder.zip](https://github.com/user-attachments/files/16081075/sessionData1_innerthunder.zip)

1. Load Session Data
2. Switch to Gremsicott (Greninja + Whimsicott fusion)
3. Use Beat Up
4. See how the move deals no damage after the first 6 hits.

**Expected behavior**

Beat Up should deal damage with every hit.

**Screenshots / Videos**

See above.

**Device**

Chrome

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes?

This fixes a bug where the additional hits given to Beat Up from the user's Multi-Lens would deal no damage (more specifically, the hits would register as dealing `NaN` damage)

## Why am I doing these changes?

closes #2767 

## What did change?

- `data/move`: `BeatUpAttr` now cycles through the eligible party members when the user's total `hitCount` for the turn is more than the eligible party's size.
- `test/moves/beat_up.test`: Three new integration tests for the move Beat Up
  - "should hit once for each healthy player Pokemon"
  - "should not count player Pokemon with status effects towards hit count"
  - "should hit twice for each healthy player Pokemon if the user has Multi-Lens"

### Screenshots/Videos

N/A

## How to test the changes?

`npm run test beat_up`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [n/a] Are the changes visual?
  - [n/a] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by torranx — APPROVED** [review]
lgtm

File: src/data/move.ts [hunk 1]
```diff
@@ -2854,7 +2854,12 @@ export class BeatUpAttr extends VariablePowerAttr {
    */
   apply(user: Pokemon, target: Pokemon, move: Move, args: any[]): boolean {
     const power = args[0] as Utils.NumberHolder;
-    const allyIndex = user.turnData.hitCount - user.turnData.hitsLeft;
+
+    const party = user.isPlayer() ? user.scene.getParty() : user.scene.getEnemyParty();
+    const allyCount = party.filter(pokemon => {
+      return pokemon.id === user.id || pokemon.status?.effect === undefined || pokemon.status?.effect === StatusEffect.NONE;
```
Comment (ben-lear) [inline src/data/move.ts:2860]: Nit: it’s good practice to handle both null and undefined cases together when handling one or the other.

Comment (innerthunder) [reply src/data/move.ts]: Changed to 
```ts
  return pokemon.id === user.id || !pokemon.status?.effect
```
which covers `null`, `undefined`, and `StatusEffect.NONE` (when `pokemon.status.effect === 0`)
