### PR TITLE
[Ability][Move] Rewrite Type Resolution and Effectiveness Calculation Functions

### LINKED ISSUE #3166: [Bug] Thousand Arrows "reveals" Levitate when Type Hints is enabled
### Describe the bug

Thousand Arrows "reveals" the opponent having Levitate when Type Hints is enabled.

### User data export file

_No response_

### Session export file

_No response_

### Expected behavior

Type Hints should only apply to what is known/revealed.

### Screenshots / Videos

_No response_

### What OS did you observe the bug on?

PC/Windows

### If other please specify

_No response_

### Which browser do you use?

Chrome

### If other please specify

_No response_

### Additional context

Discord bug reports:
https://discord.com/channels/1125469663833370665/1266076559316357120
https://discord.com/channels/1125469663833370665/1265154857455583334

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?

This fixes several bugs related to type-changing effects and move type effectiveness calculations for both the UI type hints and damage calculations within `Pokemon.apply`. This rewrite fixes the following:
- Variable-type moves now reflect their resolved type in the move selection UI (overlapping #3417 )
- Type hints are generally more accurate, accounting for immunities from *revealed* enemy abilities, powder moves not affecting Grass-types, Prankster-boosted status moves not affecting Dark types, and so on.
- Type hints no longer account for unrevealed abilities (closes #3166 )
- Tera Blast's effectiveness calculation is now accurate to mainline when the user is terastallized with the Stellar tera type (fixes a leftover issue from #3469 )
- Multi-hit moves boosted by Aerilate, etc. are no longer restricted to 1 hit when attacking a Ghost type (closes (#3570 )
- The enemy AI should not be aware of the player Pokemon's abilities until they are revealed in the current battle.

## Why am I making these changes?

In its current form, type effectiveness calculations for simulated calls or otherwise are needlessly convoluted. `Pokemon.apply` alone uses two different functions to calculate type effectiveness and, outside of those functions, applies several checks for effects that provide type or move immunities. Even worse, type effectiveness for status moves is entirely checked outside of the helper functions.

Because these type checks are so fragmented, a clean implementation of simulated effectiveness checks is virtually impossible. However, until recently, these checks were really difficult to reorganize because of two major roadblocks:
1. Before abilities supported simulated calls, there was no way to incorporate abilities into type effectiveness logic without showing unnecessary pop-up messages and potentially changing the state of battle.
2. When a Pokemon uses a move, the game reads the move's properties from `allMoves`, a globally shared cache with a `Move` object for every move. In other words, when two Pokemon decide to use the same move, they reference the same `Move` object from `allMoves`. With this setup, it's important for the data of each object in `allMoves` to remain consistent between different Pokemon's turns. However, all `VariableMoveType` move attributes and `MoveTypeChange` ability attributes broke this requirement by changing `move.type` directly in their implementations. As a result, these attributes needed to be applied at very specific times in the game's sequential logic, and any changes to their location in the code risked introducing game-breaking bugs.

With the first roadblock removed with #3529, and ideas to fix the second roadblock introduced (to some degree) in #3417 and #3643, I figured that now is the best time to decouple the leftover fragmented immunity checks from the rest of `Pokemon.apply` and develop a single all-encompassing type effectiveness calculation function, for both applied *and* simulated use with logic covering attack moves *and* status moves together.

## What are the changes from a developer perspective?

There are a lot to keep track of, so this might not be exhaustive:
- `data/move`:
  - `Move#type` and `Move#category` are now read-only, adding a restriction that removes the second roadblock from above.
  - `VariableMoveTypeAttr` and its subclasses have been updated to follow the new read-only restrictions on `Move#type`
  - Tera Blast is now only set to 100 power (instead of 200 power) when the user is Stellar-terastallized to reflect the Stellar type's new effectiveness logic.
  - `MultiHitAttr` no longer has logic to reduce hit count based on type effectiveness, as that's already handled by calls to `Pokemon#stopMultiHit()` when the associated move takes effect.
  - `StatusMoveTypeImmunityAttr` has been replaced by `RespectAttackTypeImmunityAttr`, meaning Thunder Wave can now affect Ground types if the user has Normalize.
- `data/ability`:
  - `MoveTypeChangeAttr` (now `MoveTypeChangeAbAttr`) has been updated to follow the new read-only restrictions on `Move#type`
  - Protean/Libero no longer make a copy of the checked move when checking the move's final type for the user's type change.
- `field/pokemon`:
  - `Pokemon#getMoveEffectiveness` and `Pokemon#getAttackMoveEffectiveness` are now merged into a single function (`getMoveEffectiveness`) with a `simulated` argument. This function has also been enhanced to account for the following effectiveness modifiers:
    - Type immunities from the defending Pokemon's abilities (Levitate, Volt Absorb, etc.)
    - Flag-based immunities from abilities (Soundproof, Overcoat, etc.)
    - Grass types' immunity to powder moves
    - Dark types' immunity to Prankster-boosted moves
    - The Ground-type immunity granted by Magnet Rise
    - Immunity to priority moves granted by Armor Tail, Dazzling, and Queenly Majesty on the defending Pokemon or its active ally.

    Checks for these effects are, in turn, no longer directly called in `Pokemon#apply`. This is still WIP, as there are other move-based effectiveness checks that can be moved into `getMoveEffectiveness`.

### Screenshots/Videos

The tests below use the following overrides:

```ts
const overrides = {
  OPP_SPECIES_OVERRIDE: Species.BRONZONG,
  OPP_MOVESET_OVERRIDE: Array(4).fill(Moves.SPLASH),
  OPP_ABILITY_OVERRIDE: Abilities.LEVITATE,
  MOVESET_OVERRIDE: [Moves.EARTHQUAKE, Moves.THOUSAND_ARROWS, Moves.TACKLE, Moves.HIDDEN_POWER],
  ABILITY_OVERRIDE: Abilities.GALVANIZE // only for the last test
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

#### Variable Type Display

Bulbasaur's Hidden Power shows as Steel type in the Fight menu:

image

It also shows as Steel type in the Pokemon's summary:

image

Charmander's Hidden Power, on the other hand, shows as Flying type:

image

#### Improved Type Hints

Earthquake shows as Super Effective at the start of the battle...

image

...but after using Earthquake, Bronzong's ability Levitate is revealed, causing Earthquake's type hint to change on the next turn:

image

(note that Thousand Arrows is still buggy as of these screenshots...)

**Another case:** Notice that Tackle is currently shown to be resisted by Bronzong...

image

...but after overrides are changed to give Bulbasaur Galvanize:

image

## How to test the changes?

To run new unit tests:

`npm run test effectiveness`
`npm run test galvanize`
`npm run test tera_blast` (1 new test)
`npm run test thunder_wave`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
  - #3643 
  - #3417 
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I add placeholders for them in locales?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by innerthunder** [comment]
### Update: Thousand Arrows Type Hint Fix

Thousand Arrows now correctly calculates its type effectiveness with and without Levitate revealed.

Turn 1:

image

Turn 2: After using Earthquake to reveal Levitate

image

**Review by frutescens — APPROVED** [review]
Would it be alright if you added flx and I as co-authors to the PR? It's up to you though.

File: src/data/ability.ts [hunk 1]
```diff
@@ -2910,16 +2913,20 @@ function getAnticipationCondition(): AbAttrCondition {
...
     for (const opponent of pokemon.getOpponents()) {
       for (const move of opponent.moveset) {
-        // move is super effective
-        if (move!.getMove() instanceof AttackMove && pokemon.getAttackTypeEffectiveness(move!.getMove().type, opponent, true) >= 2) { // TODO: is this bang correct?
+        // ignore null/undefined moves
+        if (!move) {
+          continue;
+        }
+        // move is super effective (not accounting for )
+        if (move.getMove() instanceof AttackMove && pokemon.getAttackTypeEffectiveness(move!.getMove().type, opponent, true) >= 2) { // TODO: is this bang correct?
```
Comment (torranx) [inline src/data/ability.ts:2921]: can probably remove the bang here by adding a condition `move`

**Review by torranx — COMMENTED** [review]
looks good so far, just a few questions:
- Is there a reason why we're using `IntegerHolder` instead of `NumberHolder`?
- I didn't see any way for this but confirming otherwise, would these changes make it possible to get the move's type in the context of tests?

**Comment by innerthunder** [comment]
> * Is there a reason why we're using `IntegerHolder` instead of `NumberHolder`?

It's just what's used for variable-category moves, and I wanted to keep the two consistent. If we're looking to phase out `IntegerHolder`, I can change them both, though.

> * I didn't see any way for this but confirming otherwise, would these changes make it possible to get the move's type in the context of tests?

`Pokemon#getMoveType` should do exactly this, so you can do something like:

```ts
const playerPokemon = game.scene.getPlayerPokemon()!;
vi.spyOn(playerPokemon, "getMoveType");

// have playerPokemon use Moves.TACKLE...

expect(playerPokemon.getMoveType).toHaveReturnedWith(Type.ELECTRIC);
```

(...in fact, I can add something like this to the Galvanize tests 🤔 )

**Comment by torranx** [comment]
> It's just what's used for variable-category moves, and I wanted to keep the two consistent. If we're looking to phase out IntegerHolder, I can change them both, though.

I haven't looked at the 2 holders yet if they have significant difference but we're phasing out `integer` type in favor of `number` so..

> Pokemon#getMoveType should do exactly this, so you can do something like:

nice, would love to see it in action here (so there would also be a reference for other contributors/devs)

**Comment by DayKev** [comment]
> > It's just what's used for variable-category moves, and I wanted to keep the two consistent. If we're looking to phase out IntegerHolder, I can change them both, though.
> 
> I haven't looked at the 2 holders yet if they have significant difference but we're phasing out `integer` type in favor of `number` so..

They're identical (and IH has no reason to exist lmao).

image

File: src/data/move.ts [hunk 2]
```diff
@@ -1082,15 +1087,11 @@ export class PreMoveMessageAttr extends MoveAttr {
...
-  constructor(immuneType: Type) {
-    super(false);
-
-    this.immuneType = immuneType;
-  }
-}
+/**
+ * Attribute for Status moves that take attack type effectiveness
+ * into consideration (i.e. {@linkcode https://bulbapedia.bulbagarden.net/wiki/Thunder_Wave_(move) | Thunder Wave})
+ */
```
Comment (xsn34kzx) [inline src/data/move.ts:1093]:
```suggestion
 * into consideration (i.e. {@linkcode https://bulbapedia.bulbagarden.net/wiki/Thunder_Wave_(move) | Thunder Wave})
 * @extends MoveAttr
 */
```
NIT: Minor additional doc line

**Review by xsn34kzx — COMMENTED** [review]
Pretty much only had one NIT. I'll follow up after a play-testing later 🫡

**Review by torranx — APPROVED** [review]
looks good

File: src/test/moves/effectiveness.test.ts [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+  it(
+    "Electric-type attacks are doubly super-effective against Water/Flying-type Pokemon",
+    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.GYARADOS, 4)
+  );
+
+  it(
+    "Electric-type attacks are negated by Volt Absorb",
+    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.GYARADOS, 0, Abilities.VOLT_ABSORB)
+  );
+});
```
Comment (DayKev) [inline src/test/moves/effectiveness.test.ts:83]:
```suggestion
import { allMoves } from "#app/data/move";
import { getPokemonSpecies } from "#app/data/pokemon-species";
import { TrainerSlot } from "#app/data/trainer-config";
import { Abilities } from "#app/enums/abilities";
import { Moves } from "#app/enums/moves";
import { Species } from "#app/enums/species";
import * as Messages from "#app/messages";
import GameManager from "#test/utils/gameManager";
import Phaser from "phaser";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";

function testMoveEffectiveness(game: GameManager, move: Moves, targetSpecies: Species,
  expected: number, targetAbility: Abilities = Abilities.BALL_FETCH): void {
  // Suppress getPokemonNameWithAffix because it calls on a null battle spec
  vi.spyOn(Messages, "getPokemonNameWithAffix").mockReturnValue("");
  game.override.enemyAbility(targetAbility);
  const user = game.scene.addPlayerPokemon(getPokemonSpecies(Species.SNORLAX), 5);
  const target = game.scene.addEnemyPokemon(getPokemonSpecies(targetSpecies), 5, TrainerSlot.NONE);

  expect(target.getMoveEffectiveness(user, allMoves[move])).toBe(expected);
}

describe("Moves - Type Effectiveness", () => {
  let phaserGame: Phaser.Game;
  let game: GameManager;

  beforeAll(() => {
    phaserGame = new Phaser.Game({
      type: Phaser.HEADLESS,
    });
    game = new GameManager(phaserGame);
    game.override.ability(Abilities.BALL_FETCH);
  });

  afterEach(() => {
    game.phaseInterceptor.restoreOg();
  });

  it("Normal-type attacks are neutrally effective against Normal-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.SNORLAX, 1)
  );

  it("Normal-type attacks are not very effective against Steel-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.REGISTEEL, 0.5)
  );

  it("Normal-type attacks are doubly resisted by Steel/Rock-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.AGGRON, 0.25)
  );

  it("Normal-type attacks have no effect on Ghost-type Pokemon",
    () => testMoveEffectiveness(game, Moves.TACKLE, Species.DUSCLOPS, 0)
  );

  it("Normal-type status moves are not affected by type matchups",
    () => testMoveEffectiveness(game, Moves.GROWL, Species.DUSCLOPS, 1)
  );

  it("Electric-type attacks are super-effective against Water-type Pokemon",
    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.BLASTOISE, 2)
  );

  it("Electric-type attacks are doubly super-effective against Water/Flying-type Pokemon",
    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.GYARADOS, 4)
  );

  it("Electric-type attacks are negated by Volt Absorb",
    () => testMoveEffectiveness(game, Moves.THUNDERBOLT, Species.GYARADOS, 0, Abilities.VOLT_ABSORB)
  );
});

```
Before:
image
After:
image

File: src/test/moves/thunder_wave.test.ts [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+
+      game.move.select(Moves.THUNDER_WAVE);
+      await game.move.forceHit();
+      await game.phaseInterceptor.to(TurnEndPhase);
+
+      expect(enemyPokemon.status).toBeUndefined();
+    },
+    TIMEOUT
+  );
+});
```
Comment (DayKev) [inline src/test/moves/thunder_wave.test.ts:121]:
```suggestion
import { StatusEffect } from "#app/data/status-effect";
import { Abilities } from "#app/enums/abilities";
import { EnemyPokemon } from "#app/field/pokemon";
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
import GameManager from "#test/utils/gameManager";
import Phaser from "phaser";
import { afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { SPLASH_ONLY } from "../utils/testUtils";

const TIMEOUT = 20 * 1000;

describe("Moves - Thunder Wave", () => {
  let phaserGame: Phaser.Game;
  let game: GameManager;

  beforeAll(() => {
    phaserGame = new Phaser.Game({
      type: Phaser.HEADLESS,
    });
  });

  afterEach(() => {
    game.phaseInterceptor.restoreOg();
  });

  beforeEach(() => {
    game = new GameManager(phaserGame);
    game.override
      .battleType("single")
      .starterSpecies(Species.PIKACHU)
      .moveset([Moves.THUNDER_WAVE])
      .enemyMoveset(SPLASH_ONLY);
  });

  // References: https://bulbapedia.bulbagarden.net/wiki/Thunder_Wave_(move)

  it("paralyzes non-statused Pokemon that are not Ground types", async () => {
    game.override.enemySpecies(Species.MAGIKARP);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status?.effect).toBe(StatusEffect.PARALYSIS);
  }, TIMEOUT);

  it("does not paralyze if the Pokemon is a Ground-type", async () => {
    game.override.enemySpecies(Species.DIGLETT);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status).toBeUndefined();
  }, TIMEOUT);

  it("does not paralyze if the Pokemon already has a status effect", async () => {
    game.override.enemySpecies(Species.MAGIKARP).enemyStatusEffect(StatusEffect.BURN);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status?.effect).not.toBe(StatusEffect.PARALYSIS);
  }, TIMEOUT);

  it("affects Ground types if the user has Normalize", async () => {
    game.override.ability(Abilities.NORMALIZE).enemySpecies(Species.DIGLETT);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status?.effect).toBe(StatusEffect.PARALYSIS);
  }, TIMEOUT);

  it("does not affect Ghost types if the user has Normalize", async () => {
    game.override.ability(Abilities.NORMALIZE).enemySpecies(Species.HAUNTER);
    await game.startBattle();

    const enemyPokemon: EnemyPokemon = game.scene.getEnemyPokemon()!;

    game.move.select(Moves.THUNDER_WAVE);
    await game.move.forceHit();
    await game.phaseInterceptor.to("BerryPhase");

    expect(enemyPokemon.status).toBeUndefined();
  }, TIMEOUT);
});

```
I realize at the end of this I could made a PR for these test changes separate from the rest of my review but... oh well.

**Review by DayKev — CHANGES_REQUESTED** [review]

**Review by DayKev — APPROVED** [review]

**Review by frutescens — APPROVED** [review]

**Review by torranx — APPROVED** [review]
