### PR TITLE
[Bug] Fix Lingering Arena Trap if Pokemon Switches Out

### LINKED ISSUE #3713: [Bug] Arena Trap, Shadow Tag and Magnet Pull Lingers After a Pokemon has been Forced Out
### Describe the bug

Link to Discord's Bug report (Shadow Tag - 2 bugs in double battles)
https://discord.com/channels/1125469663833370665/1275424376103374968/1275973836453449889

-Videos are too big so they're on Discord

1. Enter a Double Battle where one of the pokemon active has Arena Trap, Shadow Tag, or Magnet Pull
2. Have one of your pokemon use Dragon tail, Circle Throw, or roar on the pokemon with the above ability
3. Attempt to run away the next turn with your grounded steel type (Not ghost type)

-This does not occur if the pokemon with that ability has fainted, rather than been forced out.
-This could apply if that pokemon used U-turn, Volt Switch, etc.

### Session export file

_No response_

### User data export file

_No response_

### Expected behavior

The player is freed from trapping abilities after phasing that pokemon and can run away or switch freely.

### Screenshots / Videos

_No response_

### What OS did you observe the bug on?

Other

### If other please specify

gameplay

### Which browser do you use?

Other

### If other please specify

gameplay

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by geeilhan**
## What are the changes the user will see?
The user can now switch Pokemon or Run away if enemy Pokemon with Arena Trap gets forced out of the field during a double battle.

## Why am I making these changes?
Countering Arena Trap with switch out attacks is unrewarding since it does not work.
Fixes #3713 

## What are the changes from a developer perspective?
1. [apply()](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/field/pokemon.ts#L2728-L2752) checks if a move with the ForceSwitchOutAttr is used and sets [switchOutStatus](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/field/pokemon.ts#L106) according to the move effect
2. [isTrapped()](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/field/pokemon.ts#L1522-L1540) now filters out Pokemon on the opposing field that are not on the field anymore

### Screenshots/Videos
No recording of before the changes but @Snailman11 recorded a video and I can confirm its content:
https://discord.com/channels/1125469663833370665/1275424376103374968/1275973836453449889

After changes (Right Pokemon has Arena Trap):
[Lingering_Arena_Trap_After_Changes_Doubles.webm](https://github.com/user-attachments/assets/4656689e-bc32-447a-b2bb-6dc68f8a3f23)

## How to test the changes?
Use:
```
const overrides = {
  BATTLE_TYPE_OVERRIDE: "double",
  MOVESET_OVERRIDE: [ Moves.ROAR, Moves.EXTREME_SPEED, Moves.SPLASH ],
  OPP_SPECIES_OVERRIDE: Species.DIGLETT,
  STARTING_BIOME_OVERRIDE: Biome.BADLANDS,
  OPP_MOVESET_OVERRIDE: [ Moves.SPLASH ],
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

And start with at least 3 Pokemon. After that you have to manually find an encounter with 1 Arena Trap Diglett and 1 Sand Veil Diglett.
Note: I saved my game during the wave I found the matching Digletts. That way I could always easily retest some edge case behaviour.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by geeilhan** [comment]
One test started to fail randomly for some reason after the latest commit on the beta branch (src/test/mystery-encounters/encounters/clowning-around-encounter.test.ts). I reran this specific test 20 times and i always got a rogueCounter value from 5 to 7 instead of 7 for the test in line [250](https://github.com/geeilhan/pokerogueFork/blob/6cf047aa1f831f531a83dfde6e0e1becb20affb6/src/test/mystery-encounter/encounters/clowning-around-encounter.test.ts#L250-L296)

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -349,10 +349,18 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+   * @param onField overrides if this Pokemon is on the field or not
+   * @returns returns false if there is no scene otherwise it returns true
+   */
   isActive(onField?: boolean): boolean {
     if (!this.scene) {
       return false;
     }
+    if (this.switchOutStatus && !this.isPlayer) {
+      return false;
+    }
```
Comment (innerthunder) [inline src/field/pokemon.ts:363]: I think this would be better placed in `Pokemon.isOnField()`.

Also, is there a reason this only applies to enemies?

File: src/field/pokemon.ts [hunk 2]
```diff
@@ -2715,6 +2728,29 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+        this.switchOutStatus = true;
+      }
+      /**
+       * Teleport = 100, Baton Pass = 226, U-Turn = 369, Volt Switch = 521, Parting Shot = 575, Flip Turn = 812, Shed Tail = 880
+       */
+      if (move.id === 100 || move.id === 226 || move.id === 369 || move.id === 575 || move.id === 812 || move.id === 880) {
+        source.switchOutStatus = true;
+      }
+    }
+
```
Comment (innerthunder) [inline src/field/pokemon.ts:2753]: Not sure if this is necessary. `Pokemon.leaveField` already sets `switchOutStatus` to `true`, and that's already called after applying any forced switch-out.

**Review by innerthunder — CHANGES_REQUESTED** [review]
Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

**Comment by geeilhan** [comment]
> Collaborator

Thank you for your fast reply. I was just taking a break since I have been sitting here for this for a long time :D but I will be writing a test case as soon as I can.

**Comment by geeilhan** [comment]
> Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

Thank you for your fast reply. I was just taking a break since I have been sitting here for this for a long time :D but I will be writing a test case as soon as I can.

File: src/field/pokemon.ts (hunk 1 above)
Comment (geeilhan) [reply src/field/pokemon.ts:363]: This is my mistake. I failed the automated u-turn test and added this limit to fix one problem at a time. It seems I forgot about this since this should work for both sides (isPlayer and not). I will review my code again and try to clean it up.

File: src/field/pokemon.ts (hunk 2 above)
Comment (geeilhan) [reply src/field/pokemon.ts:2753]: I have not noticed that Thank you. I was looking somewhere different but after seeing `Pokemon.leaveField` it does everything I needed.

**Comment by geeilhan** [comment]
> Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

I have implemented your improvements. Thanks for the help!

Do you perhaps know a command for my automated tests where I can force one enemy Pokemon in double battles to have Arena Trap and the other enemy some other ability? I have not found one yet. Maybe I can use `vi.spyOn()` for this?

**Review by geeilhan — COMMENTED** [review]
Changes for improvement have been implemented with the latest commit.

File: src/field/pokemon.ts [hunk 3]
```diff
@@ -349,6 +352,11 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
     return challengeAllowed.value;
   }
 
+  /**
+   * Checks if the Pokemon is allowed to be in battle and if it is on the field
+   * @param onField overrides if this Pokemon is on the field or not
+   * @returns returns false if there is no scene otherwise it returns true
+   */
   isActive(onField?: boolean): boolean {
```
[the remark this answers is not in the document]
Comment (geeilhan) [reply src/field/pokemon.ts:360]: It would seem that way for me too but after checking the tests using `!!onField` instead of `!onField` many tests failed.
(Screenshot) This might be a Problem for an additional PR or Issue.
I have only looked into it a bit but it seems so far that `this.isOnField()` usually returns the correct boolean.
Additionally, only `isActive(true)` or `isActive()` are used in pokerogue. `isActive(false)` is never used.
I think because `this.isOnField()` returns the correct value and the input param is always undefined or true (in `isActive()` true would be false) in works correctly.

[the remark this answers is not in the document]
Comment (flx-sta) [reply src/field/pokemon.ts:360]: image
Of course last person touched was sam..

Maybe the naming of the variable is just wrong then?

[the remark this answers is not in the document]
Comment (DayKev) [reply src/field/pokemon.ts:360]: I already have a fix for this in another PR.

**Comment by DayKev** [comment]
> > Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.
> 
> I have implemented your improvements. Thanks for the help!
> 
> Do you perhaps know a command for my automated tests where I can force one enemy Pokemon in double battles to have Arena Trap and the other enemy some other ability? I have not found one yet. Maybe I can use `vi.spyOn()` for this?

Yeah, you can use `vi.Spyon(enemyPokemon, "getAbility", "get").mockReturnValue(allAbilities[Abilities.ARENA_TRAP]);` (might be slightly different, just typing that from memory) to "change" the ability of a specific Pokémon when the overrides can't be used.

**Comment by geeilhan** [comment]
> > > Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.
> > 
> > 
> > I have implemented your improvements. Thanks for the help!
> > Do you perhaps know a command for my automated tests where I can force one enemy Pokemon in double battles to have Arena Trap and the other enemy some other ability? I have not found one yet. Maybe I can use `vi.spyOn()` for this?
> 
> Yeah, you can use `vi.Spyon(enemyPokemon, "getAbility", "get").mockReturnValue(allAbilities[Abilities.ARENA_TRAP]);` (might be slightly different, just typing that from memory) to "change" the ability of a specific Pokémon when the overrides can't be used.

Thanks for the hint :+1:

**Comment by geeilhan** [comment]
> Along with my other comments, please write a test in `arena_trap.ts` to cover this edge case.

Automated test case in `src/test/abilities/arena_trap.test.ts` implemented

File: src/field/pokemon.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (PigeonBar) [reply src/field/pokemon.ts:360]: I think `onField` is meant to tell the function whether or not to filter for Pokemon being on the field?

File: src/field/pokemon.ts [hunk 4]
```diff
@@ -349,6 +352,11 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
     return challengeAllowed.value;
   }
 
+  /**
+   * Checks if the Pokemon is allowed to be in battle and if it is on the field
+   * @param onField overrides if this Pokemon is on the field or not
+   * @returns returns false if there is no scene otherwise it returns true
+   */
```
Comment (DayKev) [inline src/field/pokemon.ts:359]:
```suggestion
```
Since a more accurate tsdoc is added in another PR, you can remove this one.

File: src/test/abilities/arena_trap.test.ts [hunk 5]
```diff
@@ -55,4 +56,40 @@ describe("Abilities - Arena Trap", () => {
 
     expect(game.scene.getEnemyField().length).toBe(2);
   });
+
+  /**
+   * This checks if the Player Pokemon is able to switch out/run away after the Enemy Pokemon with {@link Abilities.ARENA_TRAP}
+   * is forcefully moved out of the field from moves such as Roar {@link Moves.ROAR}
```
Comment (DayKev) [inline src/test/abilities/arena_trap.test.ts:62]:
```suggestion
   * This checks if the Player Pokemon is able to switch out/run away after the Enemy Pokemon with {@linkcode Abilities.ARENA_TRAP}
   * is forcefully moved out of the field from moves such as Roar {@linkcode Moves.ROAR}
```

File: src/test/abilities/arena_trap.test.ts [hunk 6]
```diff
@@ -55,4 +56,40 @@ describe("Abilities - Arena Trap", () => {
...
+  it("should lift if pokemon with this ability leaves the field", async () => {
+    game.override.battleType("double");
+    game.override.enemyMoveset(Moves.SPLASH);
+    game.override.moveset([ Moves.ROAR, Moves.SPLASH ]);
+    await game.classicMode.startBattle([ Species.MAGIKARP, Species.SUDOWOODO, Species.LUNATONE ]);
+
+    const enemy1 = game.scene.getEnemyField()[0];
+    const enemy2 = game.scene.getEnemyField()[1];
+    const player1 = game.scene.getPlayerField()[0];
+    const player2 = game.scene.getPlayerField()[1];
```
Comment (DayKev) [inline src/test/abilities/arena_trap.test.ts:75]:
```suggestion
    const [ enemy1, enemy2 ] = game.scene.getEnemyField();
    const [ player1, player2 ] = game.scene.getPlayerField();
```

File: src/test/abilities/arena_trap.test.ts [hunk 7]
```diff
@@ -55,4 +56,40 @@ describe("Abilities - Arena Trap", () => {
...
+  /**
+   * This checks if the Player Pokemon is able to switch out/run away after the Enemy Pokemon with {@link Abilities.ARENA_TRAP}
+   * is forcefully moved out of the field from moves such as Roar {@link Moves.ROAR}
+   *
+   * Note: It should be able to switch out/run away
+   */
+  it("should lift if pokemon with this ability leaves the field", async () => {
+    game.override.battleType("double");
+    game.override.enemyMoveset(Moves.SPLASH);
+    game.override.moveset([ Moves.ROAR, Moves.SPLASH ]);
```
Comment (DayKev) [inline src/test/abilities/arena_trap.test.ts:69]:
```suggestion
    game.override
      .battleType("double")
      .enemyMoveset(Moves.SPLASH)
      .moveset([ Moves.ROAR, Moves.SPLASH ])
      .ability(Abilities.BALL_FETCH);
```

File: src/test/abilities/arena_trap.test.ts [hunk 8]
```diff
@@ -55,4 +56,40 @@ describe("Abilities - Arena Trap", () => {
...
+
+    const enemy1 = game.scene.getEnemyField()[0];
+    const enemy2 = game.scene.getEnemyField()[1];
+    const player1 = game.scene.getPlayerField()[0];
+    const player2 = game.scene.getPlayerField()[1];
+
+    vi.spyOn(enemy1, "getAbility").mockReturnValue(allAbilities[Abilities.ARENA_TRAP]);
+    vi.spyOn(enemy2, "getAbility").mockReturnValue(allAbilities[Abilities.BALL_FETCH]);
+    vi.spyOn(player1, "getAbility").mockReturnValue(allAbilities[Abilities.BALL_FETCH]);
+    vi.spyOn(player2, "getAbility").mockReturnValue(allAbilities[Abilities.BALL_FETCH]);
```
Comment (DayKev) [inline src/test/abilities/arena_trap.test.ts:80]:
```suggestion
```

File: src/test/abilities/arena_trap.test.ts [hunk 9]
```diff
@@ -55,4 +56,40 @@ describe("Abilities - Arena Trap", () => {
...
+
+    game.move.select(Moves.ROAR);
+    game.move.select(Moves.SPLASH);
```
Comment (DayKev) [inline src/test/abilities/arena_trap.test.ts:83]:
```suggestion
    game.move.select(Moves.SPLASH, 1);
```

File: src/test/abilities/arena_trap.test.ts [hunk 10]
```diff
@@ -55,4 +56,40 @@ describe("Abilities - Arena Trap", () => {
...
+
+    // This runs the fist command phase where the moves are selected
+    await game.toNextTurn();
+    // During the next command phase the player pokemons should not be trapped anymore
+    await game.toNextTurn();
```
Comment (DayKev) [inline src/test/abilities/arena_trap.test.ts:88]:
```suggestion
    game.move.select(Moves.SPLASH);
    game.move.select(Moves.SPLASH, 1);
    await game.toNextTurn();
```

File: src/test/abilities/arena_trap.test.ts [hunk 11]
```diff
@@ -55,4 +56,40 @@ describe("Abilities - Arena Trap", () => {
...
+
+    expect(game.scene.getPlayerField()[0].isTrapped()).toBe(false);
+    expect(game.scene.getPlayerField()[1].isTrapped()).toBe(false);
+    expect(game.scene.getEnemyField()[0].isOnField()).toBe(false);
+    expect(game.scene.getEnemyField()[1].isOnField()).toBe(true);
```
Comment (DayKev) [inline src/test/abilities/arena_trap.test.ts:93]:
```suggestion
    expect(player1.isTrapped()).toBe(false);
    expect(player2.isTrapped()).toBe(false);
    expect(enemy1.isOnField()).toBe(false);
    expect(enemy2.isOnField()).toBe(true);
```

**Comment by geeilhan** [comment]
@DayKev I have reviewed your changes and tested them on my device too. Everything seems to be working for me too.

**Comment by geeilhan** [comment]
Are there still some issues with the tests or is there a weird interaction between my implementation and mystery encounters? The automated tests here keep failing.

**Review by MokaStitcher — APPROVED** [review]
