### PR TITLE
[Bug] Fixing Baton Pass passing

### LINKED ISSUE #1997: [BUG] Baton Pass + Yawn bug
**Describe the bug**

Baton Pass carries Yawn effect over.
**To Reproduce**

1. Have Baton Pass
2. Opponent uses Yawn
3. Player uses Baton Pass
4. The Pokemon you send out will fall asleep

**Expected behavior**

"Baton Pass does not pass non-volatile status conditions, infatuation, drowsiness (from Yawn or G-Max Snooze), a type change, Ability change, a move learned by Mimic, or a transformation (from Transform or Imposter)." From [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Baton_Pass_(move)#:~:text=Baton%20Pass%20does%20not%20pass,(from%20Transform%20or%20Imposter).)
**Screenshots / Videos**

**Device**

PC
**Additional context**

### PR DESCRIPTION
**Pull request by DustinLin**
## What are the changes?

Per [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Baton_Pass_(move)#:~:text=Baton%20Pass%20does%20not%20pass,(from%20Transform%20or%20Imposter).) some stuff shouldn't be passed by Baton Pass. Currently the code simply pushes every tag, some filtering needs to be done

- Note that Baton Pass does not transfer type-lossness (from moves like burn-up, magic powder), this is already behaving correctly:

https://github.com/pagefaultgames/pokerogue/assets/39450497/9e386fa7-1f5b-4dae-9ed2-e0da3681110a

https://github.com/pagefaultgames/pokerogue/assets/39450497/bf2b426c-ce1d-4428-9989-8991a8cb5b40

- Note that Baton Pass does not transfer disabled moves, this is already behaving correctly

https://github.com/pagefaultgames/pokerogue/assets/39450497/ec841d1c-a696-4b89-80f5-06b8b3d9fd8e

- Baton Pass also doesn't pass on Imprison (but that's not implemented as of yet)

## Why am I doing these changes?

Closes #1997 

## What did change?

Adding filtering for:
- Yawn
- Infatuation

### Screenshots/Videos

The current behavior videos can be found on issue #1997 

PR videos: Baton Pass works correctly
- yawn

https://github.com/pagefaultgames/pokerogue/assets/39450497/3bad6951-0405-40b5-ab94-65fdb1e38c7e

- attract/infatuation
 

https://github.com/pagefaultgames/pokerogue/assets/39450497/a7674482-a1a5-4f6d-a02e-c63bea9c7b1c

## How to test the changes?

Can add yawn/attract in `overrides.ts`

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -2167,12 +2167,22 @@ export default abstract class Pokemon extends Phaser.GameObjects.Container {
...
+   */
   transferSummon(source: Pokemon): void {
     const battleStats = Utils.getEnumValues(BattleStat);
     for (const stat of battleStats) {
       this.summonData.battleStats[stat] = source.summonData.battleStats[stat];
     }
     for (const tag of source.summonData.tags) {
+
+      // bypass yawn, and infatuation as those can not be passed via Baton Pass
+      if (tag.sourceMove === 281 || tag.tagType === BattlerTagType.INFATUATED) {
```
Comment (Tempo-anon) [inline src/field/pokemon.ts:2182]: instead of 281 can you use the more readable version?

**Review by Tempo-anon — APPROVED** [review]
