### PR TITLE
[P1] Fix freeze after replacing first pokemon

### LINKED ISSUE #762: All Pokemon become invisible when capturing then switching with your only pokemon that was not fainted.
Was against castform Boss, with my Patrat who was the only one alive. I captured the castform and switch it for my patrat and now all Pokemon are invisible in future challenges.
image

### PR DESCRIPTION
**Pull request by flx-sta**
## What are the changes the user will see?

Game will no longer crash when replacing a newly caught pkm with the fist one (and all other being fainted).
<sub>Hopefully. There seems to be some edge cases</sub>

## Why am I making these changes?
When switching the active pokemon (slot 1) with the new one, the new ones visibility is `true` causing a crash with animation frames

## What are the changes from a developer perspective?

When the newly caught pkm is put on slot 1 the visibility is set to `false` to fix initial "spawning"

Fixes #762 (hopefully for good)

### Screenshots/Videos

<details>
    <summary>Videos 🎥</summary>

#### Single Battles

https://github.com/user-attachments/assets/912a234d-0d92-4120-8509-9066853c4b03

#### Double Battles

https://github.com/user-attachments/assets/67ed4d72-3f0a-4bc3-b341-d829a7a22321

</details>

## How to test the changes?

<details>
    <summary>How to test the changes 🔬 </summary>

#### Session FIle

[762-testing-session.txt](https://github.com/user-attachments/files/16874301/762-testing-session.txt)
<sup>Replace file-extension with `.prsv` to import</sup>

<sub>[Source](https://github.com/pagefaultgames/pokerogue/issues/762#issuecomment-2329562059)</sub>

#### Overrides:
```ts
const overrides = {
  STARTING_LEVEL_OVERRIDE: 100,
  BATTLE_TYPE_OVERRIDE: "single",
  POKEBALL_OVERRIDE: {
    active: true,
    pokeballs: {
      [PokeballType.POKEBALL]: 99,
      [PokeballType.GREAT_BALL]: 99,
      [PokeballType.ULTRA_BALL]: 99,
      [PokeballType.ROGUE_BALL]: 99,
      [PokeballType.MASTER_BALL]: 99,
    },
  }
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

#### `GameMode.isWaveTrainer()`

```ts
  isWaveTrainer(waveIndex: integer, arena: Arena): boolean {
    return false;
 }
 ```
 So you can keep on catching

</details>

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?
- ~~[ ] Have I considered writing automated tests for the issue?~~ => **Idk how this would work here**

### CODE REVIEW

File: src/field/pokemon.ts [hunk 1]
```diff
@@ -4899,6 +4899,7 @@ export class EnemyPokemon extends Pokemon {
 
   /**
    * Add a new pokemon to the player's party (at `slotIndex` if set).
+   * If the first slot is replaced, the new pokemons visibility will be set to `false`.
```
Comment (torranx) [inline src/field/pokemon.ts:4902]:
```suggestion
   * If the first slot is replaced, the new pokemon's visibility will be set to `false`.
```

**Review by Tempo-anon — APPROVED** [review]
