### PR TITLE
[Bug] The pokemon that set an arena hazard shouldn't ignore it

### LINKED ISSUE #935: Arena hazards are incorrectly ignored by the Pokemon that set them
Not sure if it's intended but arena trap doesn't work against teleport, Skorupi also not absorbing poison spikes.

Edit: Block also does not stop teleport.

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
Arena hazards will properly affect the Pokémon that set them (which can happen due to the hazards being swapped with Court Change, for example). This also means Toxic Spikes will be removed if the Pokémon that set them was a poison type and switches in to them.

## Why am I making these changes?
Fixes #935 

## What are the changes from a developer perspective?
Removed the `this.sourceId === pokemon.id` check in `ArenaTrapTag.apply()`.

## How to test the changes?
`npm run test toxic_spikes`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- ~[ ] Have I tested the changes (manually)?~
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

### CODE REVIEW

File: src/data/arena-tag.ts [hunk 1]
```diff
@@ -626,7 +626,7 @@ export class ArenaTrapTag extends ArenaTag {
    * @returns `true` if this hazard affects the given Pokemon; `false` otherwise.
    */
   override apply(arena: Arena, simulated: boolean, pokemon: Pokemon): boolean {
```
Comment (Tempo-anon) [inline src/data/arena-tag.ts:628]: Why is this named ArenaTrapTag? Surely something like HazardTag would make more sense?

**Review by Tempo-anon — APPROVED** [review]
Why was there a `this.sourceId === pokemon.id` case to begin with? You'll always be targeting the opponent's field and all that did was cause problems for things that reflect hazards like court change and magic bounce

File: src/data/arena-tag.ts (hunk 1 above)
Comment (DayKev) [reply src/data/arena-tag.ts:628]: The answer to both questions is "because sam". 🤣
