### PR TITLE
[Bug] Fix Berserk and Anger Shell from crashing the game when pokemon is forced to switch out

### LINKED ISSUE #1689: Game frozen on level 25 trainer battle
**Describe the bug**
At level 25, there is a rival battle. In it the rival brings out Throh which uses circle throw causing my pokemon to switch out. After switching in the next pokemon, the game freezes afterwards. I have tried clearing browser cache and cookies and also tried in Chrome, Edge and Firefox. But still nothing works

Error log:
```
TypeError: Cannot read properties of undefined (reading 'damage')
    at Ak.applyPostDefend (index-4637969b.js:14852:3011)
    at index-4637969b.js:14874:5092
    at applyAbAttr (index-4637969b.js:14874:4582)
    at applyNextAbAttr (index-4637969b.js:14874:4092)
    at index-4637969b.js:14874:4663
    at new Promise (<anonymous>)
    at applyAbAttrsInternal (index-4637969b.js:14874:3804)
    at applyPostDefendAbAttrs (index-4637969b.js:14874:5076)
    at index-4637969b.js:14985:1174
    at executeIf (index-4637969b.js:6363:75932)
```

**To Reproduce**
1. Reach level 25 in classic mode
2. Start the battle and defeat the first pokemon
3. Trainer brings out the second pokemon, Throh and it uses Circle Throw as its first move
4. User's pokemon switches out. User sends out the next pokemon
5. Thee game freezes and the following error log is visible on the browser console

**Expected behavior**
Game shouldn't freeze

**Screenshots / Videos**
image

https://github.com/pagefaultgames/pokerogue/assets/53526184/cf2d0580-4325-4c15-a162-0054f733d8ca

**Device**
Playing on PC. Issue happens in Chrome, Firefox and edge

**Additional context**
Possibly the error is on [this line](https://github.com/pagefaultgames/pokerogue/blob/060b1b2cccf7a8b2f7451c684f8a9e0dadcffde2/src/data/ability.ts#L643)

### PR DESCRIPTION
**Pull request by torranx**
Fixes #1689 

## What are the changes?
- Fixed Berserk and Anger Shell abilities

## Why am I doing these changes?
- Game crashes/freezes when Berserk/Anger Shell is triggered with force switch move targeting the opposing side.

## What did change?
- added optional chain before checking `damage`

### Screenshots/Videos
- Game no longer crashes/freezes

https://github.com/pagefaultgames/pokerogue/assets/68144167/4a96d907-3df5-4119-963c-a62698bf73a5

## How to test the changes?
- Import the session data [here](https://discord.com/channels/1125469663833370665/1125662770629709935/1246535325967319040)
- Kill the first mon, opponent should use Circle Throw then

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
- [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
- [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

File: src/data/ability.ts [hunk 1]
```diff
@@ -640,7 +640,7 @@ export class PostDefendHpGatedStatChangeAbAttr extends PostDefendAbAttr {
   applyPostDefend(pokemon: Pokemon, passive: boolean, attacker: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean {
     const hpGateFlat: integer = Math.ceil(pokemon.getMaxHp() * this.hpGate);
     const lastAttackReceived = pokemon.turnData.attacksReceived[pokemon.turnData.attacksReceived.length - 1];
-    if (this.condition(pokemon, attacker, move.getMove()) && (pokemon.hp <= hpGateFlat && (pokemon.hp + lastAttackReceived.damage) > hpGateFlat)) {
+    if (this.condition(pokemon, attacker, move.getMove()) && (pokemon.hp <= hpGateFlat && (pokemon.hp + lastAttackReceived?.damage) > hpGateFlat)) {
```
Comment (Tempo-anon) [inline src/data/ability.ts:643]: Won't this be adding a number to undefined? I think it'd be better to do a check for lastAttackReceived and just make it not add or add 0 instead

**Review by Tempo-anon — CHANGES_REQUESTED** [review]

File: src/data/ability.ts [hunk 2]
```diff
@@ -640,7 +640,8 @@ export class PostDefendHpGatedStatChangeAbAttr extends PostDefendAbAttr {
   applyPostDefend(pokemon: Pokemon, passive: boolean, attacker: Pokemon, move: PokemonMove, hitResult: HitResult, args: any[]): boolean {
     const hpGateFlat: integer = Math.ceil(pokemon.getMaxHp() * this.hpGate);
     const lastAttackReceived = pokemon.turnData.attacksReceived[pokemon.turnData.attacksReceived.length - 1];
-    if (this.condition(pokemon, attacker, move.getMove()) && (pokemon.hp <= hpGateFlat && (pokemon.hp + lastAttackReceived.damage) > hpGateFlat)) {
+
+    if (lastAttackReceived && this.condition(pokemon, attacker, move.getMove()) && (pokemon.hp <= hpGateFlat && (pokemon.hp + lastAttackReceived.damage) > hpGateFlat)) {
```
Comment (XGSleepWalker) [inline src/data/ability.ts:644]: Please default lastAttackReceived to 0 instead of cancelling the whole condition.

**Review by XGSleepWalker — CHANGES_REQUESTED** [review]

**Review by Tempo-anon — APPROVED** [review]
