### PR TITLE
Fix issue #312 -> set proper french name for move "smog"

### LINKED ISSUE #312: Mistranslation of Smog and Clear Smog in the French locale
Hello,

I came to report a mistranslation of two of the attack

Smog & Clear Smog are both translated as "Bain de Smog".

Bain de Smog is the translation of Clear Smog.

Smog should be called Purédpois.

baindesmog
puredpois

### PR DESCRIPTION
**Pull request by dpMelian**
Fixes #312

### CODE REVIEW

File: src/locales/fr/move.ts [hunk 1]
```diff
@@ -490,7 +490,7 @@ export const move: MoveTranslationEntries = {
     effect: "Un grand coup de langue qui inflige des dégâts à la cible et peut aussi la paralyser (30% de chances)."
   },
   "smog": {
-    name: "Bain de Smog",
+    name: "Purédpois",
     effect: "Le lanceur projette de la boue bizarre sur la cible. Les changements de stats de la cible sont annulés."
```
Comment (Dakurei) [inline src/locales/fr/move.ts:494]: You forgot to change the description that doesn't fit, since it's now a duplicate with `clearSmog` line 1997

The description of "Purédpois" is:
> Le lanceur attaque à l'aide d'une éruption de gaz répugnants qui peuvent aussi empoisonner la cible.

Comment (dpMelian) [reply src/locales/fr/move.ts]: True! Thank you, I just added that

**Review by Dakurei — APPROVED** [review]

**Review by Flashfyre — APPROVED** [review]
