### PR TITLE
fix(move): Paldea Tauros and Rotom can no longer have incorrect moveset in rival fights

### LINKED ISSUE #7116: [Bug] Pokemon with form exclusive moves (Rotom, Paldea Tauros) generate them on the wrong form
Bug report initiated by Discord user **kazapple_**
### Describe the bug

[Related Discord message](https://discord.com/channels/1125469663833370665/1474071538335617055/1474071538335617055)

98% sure it shouldnt have blizzard

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by macwellbz**
## What are the changes the user will see?

Users can no longer run into multi-form Pokemon with the wrong movesets during rival fights.

## Why am I making these changes?

Fixes #7116 

## What are the changes from a developer perspective?

When post processing the rival's party, multi-form Pokemon are set to specific forms. Before, the form would be overridden but the moveset stayed the same. This could pose a problem if certain Pokemon had different abilities based on forms but this Isn't the case for Rotom or Paldea Tauros. 

Ideally there should be no post processing needed here and any restrictions should be placed when creating the Pokemon but that requires a large redesign.

## Screenshots/Videos

<details><summary>Before</summary>

image

</details>
<details><summary>After</summary>

image

</details>

## How to test the changes?

I've tested using these overrides:

```
const overrides = {
  STARTING_LEVEL_OVERRIDE: 1000,
  STARTING_WAVE_OVERRIDE: 145,
  ENEMY_SPECIES_OVERRIDE: SpeciesId.PALDEA_TAUROS,
} satisfies Partial<InstanceType<OverridesType>>;
```

Then, to ensure the post processing is run, in `rival-party-config.ts` replace `const RIVAL_5_POOL` with:

```
export const RIVAL_5_POOL: RivalPoolConfig = [
  { pool: SLOT_1_FINAL, postProcess: p => postProcessSlot4Fight4(p, SLOT_4_FIGHT_5_LEVEL), },
  { pool: SLOT_2_FINAL, postProcess: p => postProcessSlot4Fight4(p, SLOT_4_FIGHT_5_LEVEL), },
  {
    pool: SLOT_3_FINAL,
    postProcess: p => postProcessSlot4Fight4(p, SLOT_4_FIGHT_5_LEVEL),
    balanceTypes: true,
    balanceWeaknesses: true,
  },
  {
    pool: SLOT_4_FINAL,
    postProcess: p => postProcessSlot4Fight4(p, SLOT_4_FIGHT_5_LEVEL),
    balanceTypes: true,
    balanceWeaknesses: true,
  },
  { pool: SLOT_5_FINAL, postProcess: p => postProcessSlot4Fight4(p, SLOT_4_FIGHT_5_LEVEL), },
  { pool: SLOT_6_FINAL, postProcess: p => postProcessSlot4Fight4(p, SLOT_4_FIGHT_5_LEVEL) },
];
```

## Checklist

- The PR content is correctly formatted:
  - [x] **I'm using `beta` as my base branch**
  - [x] **The current branch is not named `beta`, `main` or the name of another long-lived feature branch**
  - [x] I have provided a clear explanation of the changes within the PR description
  - [x] The PR title matches the Conventional Commits format (as described in [CONTRIBUTING.md](https://github.com/pagefaultgames/pokerogue/blob/beta/CONTRIBUTING.md#pr-title-format))
- [x] The PR is self-contained and cannot be split into smaller PRs
- [x] There is no overlap with another open PR
- The PR has been confirmed to work correctly:
  - [x] I have tested the changes manually
  - [x] The full automated test suite still passes (use `pnpm test:silent` to test locally)
  - [ ] I have created new automated tests (`pnpm test:create`) or updated existing tests related to the PR's changes if necessary
- [x] I have provided screenshots/videos of the changes (if applicable)
  - [x] I have made sure that any UI changes work for both the default and legacy UI themes (if applicable) N/A

### CODE REVIEW

**Review by DayKev — DISMISSED** [review]

File: src/data/trainers/rival-party-config.ts [hunk 1]
```diff
@@ -451,15 +463,27 @@ function postProcessSlot4Fight4(pokemon: EnemyPokemon, level = SLOT_4_FIGHT_4_LE
   pokemon.level = level;
   switch (pokemon.species.speciesId) {
     case SpeciesId.BASCULEGION:
-      pokemon.formIndex = randSeedIntRange(0, 1);
+      // Male, Female
+      pokemon.formIndex = randSeedItem([1, 2]);
```
Comment (DayKev) [inline src/data/trainers/rival-party-config.ts]:
```suggestion
      pokemon.formIndex = randSeedItem([0, 1]);
```
0 is male, 1 is female.
...Though I don't know why this is being done in the first place.

Comment (macwellbz) [reply src/data/trainers/rival-party-config.ts]: I see now that the formIndexes are all set in `battle-scene.ts`. This is correct, ty.

As for why it's done, theres a comment here:

`SpeciesId.BASCULEGION, // Ensure gender does not change`

Although I'm not sure how this guarantees that.

Comment (DayKev) [reply src/data/trainers/rival-party-config.ts]: > Although I'm not sure how this guarantees that.

It doesn't, which is why I said that. That comment isn't very good anyway, it's too vague.
