### PR TITLE
[Bug][Mystery] Force Clowning Around Blacephalon to roll two different types

### LINKED ISSUE #5168: [Bug] Clowning Around Blacephalon can Roll the Same Type Twice
### Describe the bug

The Clown in the Clowning Around Mystery Encounter can choose to be the same type twice, resulting in it being monotype.

Link to Discord's Bug Report (Clowning Around Blacephalon is dual Poison Type)
https://discord.com/channels/1125469663833370665/1294754049069154415

### Reproduction

Load the session data so you don't need to roll until the clown chooses two types.

### Expected behavior

Clowning Around should not be able to roll the same type on the Clown twice.

Image

### Screenshots / Videos

Types used to be Split

Image

Types are now merged into one icon.

Image

### Session export file

[ClownDoubleType.txt](https://github.com/user-attachments/files/18515863/ClownDoubleType.txt)

### User data export file

_No response_

### PR DESCRIPTION
**Pull request by EscaShark**
## What are the changes the user will see?

The Blacephalon in the Clowning Around encounter will now always roll two different random types, and can no longer be monotyped.

## Why am I making these changes?

Fixes #5168 

## What are the changes from a developer perspective?

The types are now randomized before the custom data is set rather than during. The second type is only rolled out of 17 options and incremented if it is "at least higher" than the first type, simulating a d18 roll that skips the first type.

## Screenshots/Videos

Proof the encounter still works I guess:

https://github.com/user-attachments/assets/b8db661e-fe1c-4995-b16a-1ebb9c1eadbc

## How to test the changes?

The inherently very random nature of the fix makes it tough to "test". Run the encounter a lot and notice that it's never monotyped 🤷 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [ ] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [ ] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [ ] If so, please leave a link to it here: 
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

File: src/data/mystery-encounters/encounters/clowning-around-encounter.ts [hunk 1]
```diff
@@ -127,6 +127,13 @@ export const ClowningAroundEncounter: MysteryEncounter =
       encounter.setDialogueToken("ability", new Ability(ability, 3).name);
       encounter.misc = { ability };
 
+      // Decide the random types for Blacephalon. They should not be the same.
+      const firstType: number = randSeedInt(18);
+      let secondType: number = randSeedInt(17);
+      if ( secondType >= firstType ) {
+        secondType++;
+      }
```
Comment (DayKev) [inline src/data/mystery-encounters/encounters/clowning-around-encounter.ts:135]: This makes it so the second type can never be Fairy unless both roll Dark. I'd go with this instead:
```suggestion
      let secondType: number = randSeedInt(18);
      while (secondType === firstType) {
        secondType = randSeedInt(18);
      }
```

**Review by DayKev — APPROVED** [review]

**Review by Madmadness65 — APPROVED** [review]
